### ISSUE TITLE
Analogue Switches not working

### ISSUE THREAD

**Issue by ItDidntCatchFire** [sharpie7/circuitjs1#104]
Found a bug where Analogue Switches don't change their output based on their inputs. See screen shot for details

![image](https://cloud.githubusercontent.com/assets/28661573/26019370/cce369b8-376c-11e7-952a-6d9a418c100c.png)

**Comment by pfalstad** [comment]
Hi, analog switches act like large resistors when they are open.  So if you want the output to be low when the switch is open, you'll have to pull it down somehow.

**Comment by sharpie7** [comment]
Thanks Paul - yes, the behaviour is as expected.
