### ISSUE TITLE
Convergence failed when adding voltmeter or test point

### ISSUE THREAD

**Issue by coder20980** [sharpie7/circuitjs1#105]
What does this mean or what can be done to avoid it?  Here's an example:
[http://tinyurl.com/lm767bl](url)

**Comment by pfalstad** [comment]
Hi,

the test points are not wires.  they don't conduct.  you need something like this:

http://tinyurl.com/lqdvjqn

although there's no reason to put a test point there because it will always read 0 voltage, but it shows how to use the test point.

**Comment by coder20980** [comment]
Thanks

**Comment by sharpie7** [comment]
Behaviour is as intended.
