### ISSUE TITLE
bug: oncontextmenu

### ISSUE THREAD

**Issue by annopnod** [sharpie7/circuitjs1#106]
if click back circuit data loss
![screenshot from 2017-05-18 20-24-35](https://cloud.githubusercontent.com/assets/6957642/26204852/489326ce-3c0a-11e7-8071-e6b12a49e4c9.png)

**Add code**
 window.onbeforeunload = function(){
    return 'You have made some changes which you might want to save.';
}

**Comment by pfalstad** [comment]
Yes, it would be good to have the simulator to warn you before navigating away if you have unsaved changes.

**Comment by pfalstad** [comment]
Fixed
