### ISSUE TITLE
feature: JFET forward-biased

### ISSUE THREAD

**Issue by Felthry** [sharpie7/circuitjs1#107]
Currently, the simulation errors if you try to forward-bias the gate-source diode of a JFET. In reality, this would result in diode-like behavior, plus the parasitic resistance of the body semiconductor. I feel like it would be better to simulate this behavior, even if it's almost always unintended, than to simply throw an error and halt.

**Comment by pfalstad** [comment]
The issue here is that I have had trouble finding specifics on what the correct behavior should be in that case.

**Comment by Felthry** [comment]
Have you tried looking at SPICE models?
I would imagine it would function as a diode of some sort, though I don't know what sort of forward voltage it would have. The channel resistance would come into play too, but that is ideally zero.

**Comment by pfalstad** [comment]
SPICE models tend to be much too complicated to translate into code.  But I could certainly run some test circuits in SPICE and see what sort of behavior I get.

**Comment by Felthry** [comment]
[This](http://edadocs.software.keysight.com/pages/viewpage.action?pageId=5926333) page and [this](http://www.ee.bgu.ac.il/~circlab/experiments/JFETmodel.pdf) document might be helpful. Both contain general-purpose models of JFETs, for forward- and reverse-biased modes. It also might be useful to ask around on e.g. https://electronics.stackexchange.com or a similar website for someone with more experience with JFET modelling.

**Comment by sharpie7** [comment]
Fixed (I believe!)
