### ISSUE TITLE
Feature: Reset while paused

### ISSUE THREAD

**Issue by Felthry** [sharpie7/circuitjs1#110]
Occasionally, it would be useful to be able to reset the simulation, but not immediately start it. This is especially good for if you want to save something to be used as an example, as you can be sure it will start at zero time with no initial conditions at all. Current behavior is that clicking the reset button sets the simulation to run mode, even if it was paused before resetting.

**Comment by pfalstad** [comment]
yeah I've wanted this too.  I think the original reason the reset button starts the simulation is that I was worried first-time users wouldn't know how to start the simulation if it got stopped.  But with the old checkbox replaced with a giant red button, I think this isn unnecessary.

**Comment by Felthry** [comment]
It is a nice convenience feature, even if it's inconvenient to not be able to turn it off. Perhaps a separate "reset and run" button? Or just hold the state from when the reset button is pressed, perhaps.

**Comment by pfalstad** [comment]
Well, it's not that hard to press reset and then press run.  It's a bit weird to have "Reset" start the simulator if it's stopped.

**Comment by pfalstad** [comment]
Actually I could make it so pressing Reset twice starts the simulator.

**Comment by sharpie7** [comment]
Fixed.
