### ISSUE TITLE
Bug: Tunnel diodes spontaneously create voltage

### ISSUE THREAD

**Issue by Felthry** [sharpie7/circuitjs1#112]
See, for example,
$ 1 0.000005 10.20027730826997 50 5 50
175 288 192 400 192 0

Tunnel diodes seem to spontaneously generate a voltage of -1.96mV when not connected to anything.
Furthermore, shorting one out gives a 255μA current. Even worse, putting a 10Ω resistor across a tunnel diode seemingly creates 124nW of power out of nowhere, as in
$ 13 0.0000049999999999999996 10.20027730826997 50 0.005 99
175 288 192 400 192 0
w 400 144 400 192 0
w 288 144 288 192 0
r 288 144 400 144 0 10
o 0 64 0 4099 0.0048828125 0.000390625 0 2 0 3
o 3 64 0 4099 0.0048828125 0.000390625 1 2 3 3

**Comment by sharpie7** [comment]
Fixed
