### ISSUE TITLE
Feature: Pan

### ISSUE THREAD

**Issue by Felthry** [sharpie7/circuitjs1#114]
I'd like to see the ability added to pan around your circuit. Middle mouse button and drag would be a good control option for this. It could be implemented as "select all and move" but would likely be better to just have a proper pan; the window can be recentered already as evidenced by the zoom feature, so I don't think this would be too much of a problem.

**Comment by pfalstad** [comment]
Isn't that what alt-drag does?

**Comment by Felthry** [comment]
...so it does. I somehow missed that control.
