### ISSUE TITLE
Downloading the app?

### ISSUE THREAD

**Issue by Aridarmus** [sharpie7/circuitjs1#116]
Is there a way to download the new version for offline use? I was able to download and start only the older java version.

**Comment by sharpie7** [comment]
Offline use is not supported and I do not intend to work on addressing it. I have added an explantion of why under "Offline Use" here: http://lushprojects.com/circuitjs/

**Comment by gitgrimbo** [comment]
Hi, small typo in the new "Offline Use" section:

> The **limiation** of this method is that it is not a simple process and probably requires some familiarity with web development and hosting to make it work.

**Comment by sharpie7** [comment]
Thanks - fixed.
