### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by jarrodatt** [sharpie7/circuitjs1#118]
Hello,
Not sure if this is the place to ask. But I need some help please I cannot get the master branch to compile I  downloaded The tools you will need to build the project are:

    Eclipse - I am using the Kepler version.
    Google plugin for Eclipse to provide GWT. (from eclipse extension store)

but a google button never shows up or gwt for that matter. 
Sorry I have never done this before.  then do you just import unzipped folder i'm confused.

**Comment by sharpie7** [comment]
I have added links to the README file to help with the installation of Eclipse and the Google plugin. That might help you.

The Google icon is a blue circle with a white "g" in it on the Eclipse taskbar. It is not very obvious among all the other stuff already on there. 

Probably this is not a good project to start with unless you already have some familiarity with how to use Integreated Development Environments (IDEs) like Eclipse.
