### ISSUE TITLE
Possibility of current source with waveforms

### ISSUE THREAD

**Issue by kiromaisus** [sharpie7/circuitjs1#125]
Would it be possible to make a current source with waveforms, like the voltage sources we already have?
Thank you very much!
I really appreciate your work and your great simulator!

**Comment by sharpie7** [comment]
It would be possible but may not be a very common requirement.

You can effectively do the same thing by connecting a voltage source to a voltage controlled current source like this: [http://tinyurl.com/ycwkm2bs](url)

**Comment by pfalstad** [comment]
or just: http://tinyurl.com/y3neldgn

**Comment by sharpie7** [comment]
Solutions provided - no plan to change application.
