### ISSUE TITLE
Feature: improvements of noise

### ISSUE THREAD

**Issue by BurSer** [sharpie7/circuitjs1#139]
There is only a 1-terminal noise source, but it would be useful sometimes to use a 2-terminal one (for example, while modelling op-amps I could just add it to the output).

**Comment by pfalstad** [comment]
Yes, that would be good.  In the meantime you can use a VCVS as an adder like this: http://tinyurl.com/yd7erj78

**Comment by pfalstad** [comment]
done in 90886a68eca737821cfcb73a20d50a0479357ac9
