### ISSUE TITLE
Ah yes, I found the best transistor for thousands of ampere application

### ISSUE THREAD

**Issue by DarkBabylon** [sharpie7/circuitjs1#143]
Too bad like perfect circles, they do not exist.
![image](https://user-images.githubusercontent.com/7856752/28286587-61713ef4-6b41-11e7-8556-cff53309c9f9.png)
Apparently this happened when I disconnected some random wires in the incorrect order?

**Comment by sharpie7** [comment]
The simulation doesn't place any limits on the current, power etc. handled by components. Obviously a disconnected component shouldn't have 12kA going through it though! If you can show us how to reproduce the problem we could look in to it.
