### ISSUE TITLE
Please add an Instrumentation amplifier block

### ISSUE THREAD

**Issue by ewiebe1** [sharpie7/circuitjs1#147]
Please add an Instrumentation amplifier (like INA333) as a single block.
IA: https://en.wikipedia.org/wiki/Instrumentation_amplifier

Thans in advance!
Good Job!

**Comment by sharpie7** [comment]
That could be possible - not the INA333 specifically, but the ideal IA. I guess I would just do it as an ideal differential amp with a (low) gain that can be set by the user.

**Comment by pfalstad** [comment]
You can use an op-amp for this.  The gain can be set by the user now.
