### ISSUE TITLE
Feature: Make adding/removing scopes less disruptive

### ISSUE THREAD

**Issue by sharpie7** [sharpie7/circuitjs1#148]
Note to self really:

Currently if you add or remove a scope it causes all other scopes to be reset (due to the width being changed). This blanks the traces and resets the scale for "max scale" scopes. 

This makes it quite disruptive to probe circuits at different points. It might be nicer if stored data values were interpolated to the new scope scale and range value cached.

**Comment by pfalstad** [comment]
I have a fix for this

**Comment by sharpie7** [comment]
Fixed in latest version.
