### ISSUE TITLE
Copypaste between two different windows, paste import, compact circuit blocks?

### ISSUE THREAD

**Issue by Harvie** [sharpie7/circuitjs1#15]
Hello,
i think that copypaste between two different windows would be nice feature :-)

Also it would be really usefull if importing schematic from file would allow me to import one schematic to another (like copypaste, but from file), so i can import reusable circuit blocks to bigger composite circuit.

Another step might be adding support for real blocks: Eg. i make full bridge rectifier, add "pin components" with labels to it's endpoints and save it to file. Then i "import as block" which would show whole rectifier as single component with 4 pins. With connection being dynamic, so i can modify the block without breaking the super circuits that are using such blocks.

**Comment by pfalstad** [comment]
I added copy paste between windows to my branch

**Comment by sharpie7** [comment]
Fixed in "one-year-updates" branch. Will merge to master in due course.

**Comment by Harvie** [comment]
What about the blocks?
