### ISSUE TITLE
Shift-click is bugged with power supplies

### ISSUE THREAD

**Issue by eric8he** [sharpie7/circuitjs1#152]
When I place down a single connection power supply, then try to move it with Shift+drag, it moves one of the ends of the component instead of the component as a whole.
 My computer/OS/specs
MacBook Air running MacOS Sierra
Using Google Chrome 60.0.3112.90

**Comment by pfalstad** [comment]
Yeah that seems like a bug.  It works for me if you are careful not to select one of the ends of the component when you drag it.  But if you use shift-drag, it should always drag the component and not the terminals.

**Comment by pfalstad** [comment]
fixed!  see, I didn't forget.
