### ISSUE TITLE
Feature Request - JT / Bifilar Toroid

### ISSUE THREAD

**Issue by jac335** [sharpie7/circuitjs1#155]
Great simulator, thank you for all the effort put into making this great site.

One request: a Joule Thief / bifilar wound toroid component.

Would this be possible to create?

Thanks again!
J

**Comment by pfalstad** [comment]
Hi,

There is a joule thief example in the circuits menu, under Circuits->Transistors->Joule Thief.

You can make a bifilar wound component using a transformer.

**Comment by jac335** [comment]
Did not see that, thanks Paul!
