### ISSUE TITLE
mosfet's Rds is too high

### ISSUE THREAD

**Issue by yunuzk** [sharpie7/circuitjs1#157]
Hi, i tried to simulate mosfet transistor, i supplied the gate about 5-10 volt,
the D-S resistance is about several ohm.
I calculate the Rds = Vds / Ids.
The actual Rds of actual mosfet generally about 10-100 mili ohm (0.010-0.100 ohm).
for low powered application that's ok, but for several watt it is inaccurate.

there are no option for Ids, only threshold voltage.

**Comment by pfalstad** [comment]
hi,

you can adjust the "beta" parameter to change Rds.  set beta = 1/(RdsON*(Vgs-Vt))

**Comment by OmegaHaxors** [comment]
Most modern MOSFETs have a Beta higher than 2 if my calculations are correct. Considering the default value in the sim is 20m, it just goes to show how far we've come in MOSFET technology since this program was originally made.

**Comment by emilfihlman** [comment]
If most modern mosfets have a beta of around 800m, then something is still broken with the model. A very simple p80nf55 should conduct many tens of amperes at 6Vds and 6Vgs, yet at 800m it conducts barely 10A.

**Comment by pfalstad** [comment]
A beta of around 35 is more appropriate for that device.

**Comment by pfalstad** [comment]
Ordinary MOSFETs like the ZVP3306A have a beta of around .027.  Power MOSFETs have beta that are much higher.
