### ISSUE TITLE
feature: add component code.

### ISSUE THREAD

**Issue by yunuzk** [sharpie7/circuitjs1#158]
I want the componen code can be added.
for example adding diode, transistor, ic, ... ,
I should googling the datasheet manually for every components and edit the parameters in the simulator.
it is impractical, wasting my time.

the componen's parameter dialog box should have a dropdownlist or searchbox for popular componen codes. when selected, the other parameters filled automatically.

**Comment by sharpie7** [comment]
This application is primarily about showing how electronics works using the essential building blocks. We don't really try and have precise models for specific components unless they have really had an enormous impact on the practice or teaching of electronics. If you want specific simulation of particular components then the industry standard is to use a SPICE-based simulator for which manufacturers often provide component models.
