### ISSUE TITLE
Feature: Audio Download

### ISSUE THREAD

**Issue by Infinitum23** [sharpie7/circuitjs1#159]
I've been using this plugin a lot for developing guitar effects, and have created a number of circuits that I like. I'd like to be able to download the signal from audio out so as to create an impulse response for use with an audio convolver. This would allow circuits to be used in a DAW in real time without the need to purchase costly equipment.

**Comment by sharpie7** [comment]
That's actually a really cool idea. Simulation of simulation of analog audio FX.

I think the feature you need is already available on Draw -> Outputs and Labels -> Add Data Export
