### ISSUE TITLE
Both Multiplexer and Demultiplexer say Multiplexer when hovering

### ISSUE THREAD

**Issue by Benur21** [sharpie7/circuitjs1#161]
Probably just a typo. It looks like Demultiplexer is who has the wrong name when hovering.
![image](https://user-images.githubusercontent.com/29681989/30061789-a9821198-9240-11e7-90e1-c1b5a781e8b5.png)
![image](https://user-images.githubusercontent.com/29681989/30061823-cbc0a436-9240-11e7-904d-73abeca54a85.png)

**Comment by sharpie7** [comment]
Thanks. Fixed in lastest version on my site.
