### ISSUE TITLE
Offline run (after Version 1.6i) circuitjs?

### ISSUE THREAD

**Issue by Qubc** [sharpie7/circuitjs1#165]
Hi,
Do you can do tutorial how run circuitjs (after Version 1.6i) offline?
I live in place with bad internet and use old java version, cause I don't understand readme with kepler and gwt plugin..
Thanks for circuitjs !)

**Comment by sharpie7** [comment]
See under "Offline Use" here:
http://lushprojects.com/circuitjs/
