### ISSUE TITLE
Request feature: thermal view

### ISSUE THREAD

**Issue by yunuzk** [sharpie7/circuitjs1#167]
It is better if the simulator have an thermal view, so the temperature/power leakage can be observed.

**Comment by OmegaHaxors** [comment]
Go over to options and click Show Power. It's not perfect but it will give you a good approximation on how much power is being bled away by your resistors. Green means power is being created (like from a capacitor or source) and Red means it's being destroyed. Slide the Power Brightness for more clear results.

**Comment by sharpie7** [comment]
@OmegaHaxors If you hover the mouse over a component then the info box on the bottom right of the main panel will (normally) show the instantaneous power dissipation ("P=....")

**Comment by OmegaHaxors** [comment]
It won't on the various transistors, Voltage Sources, and the digital switches. You don't realize how much you appreciate its existence until it's not included on the part you want to examine.

**Comment by sharpie7** [comment]
Power info added for transistors, diodes and DC sources in latest version on my site.
