### ISSUE TITLE
Led Vf over 36.7170597 causes singular matrix error

### ISSUE THREAD

**Issue by emilfihlman** [sharpie7/circuitjs1#173]
$ 1 0.000005 10.20027730826997 50 5 43
v 80 288 80 128 0 1 50 325 0 0 0.5
162 528 176 528 288 1 36.7170597 1 0 0 0.1

vs

$ 1 0.000005 10.20027730826997 50 5 43
v 80 288 80 128 0 1 50 325 0 0 0.5
162 528 176 528 288 1 36.7170598 1 0 0 0.1

**Comment by pfalstad** [comment]
I think this works now but you have to create a new diode (use Custom model, then Create Simple Model).  If you use the circuit text above, it will create a diode with the old model for backward compatibility, and you'll get the same error.

**Comment by sharpie7** [comment]
Fixed for new circuits.
