### ISSUE TITLE
Request feature: add varactors (varicap) diodes

### ISSUE THREAD

**Issue by Iacob-Cezar-Catalin** [sharpie7/circuitjs1#175]
As far as I know there is no easy way to use other components to model the comportament of a varicap diode thus it is impossible to make up something for the lack of a varicap inside a single simulation page. Please add varicaps or allow users to create custom components using some lines of code and a custom component symbol.png with custom connectors sticking out of it.

**Comment by pfalstad** [comment]
added in fe1caeb860438cfe43359731e875e076760a8a26
