### ISSUE TITLE
Feature - Small signal diode support

### ISSUE THREAD

**Issue by fodha** [sharpie7/circuitjs1#177]
Hi,
The bulk resistance of the small signal diode is greater then rectifier diode. This will impact the simulation for example in the case of stiff clipper of an AC signal circuit where the following condition should be satisfied:  100Rb < Rs  < 0.01Rl. So as workaround I put a small 30 Ohm resistance in series with the diode. Could you please add resistance feature in case of small signal diode?
I attached good (with correction: adding resistance to the diode) and not good circuits.
Thank you!
![good](https://user-images.githubusercontent.com/32953787/31813874-c013a0ea-b57f-11e7-8b27-9af967fb6ea3.png)
![not_good](https://user-images.githubusercontent.com/32953787/31813887-c70c2bec-b57f-11e7-8606-643bc617bd69.png)

**Comment by pfalstad** [comment]
added in e9c801a424af8a8de2d20c3f201653f2cae9ebc4
