### ISSUE TITLE
Ohm meter

### ISSUE THREAD

**Issue by iceman2894** [sharpie7/circuitjs1#178]
I don't know if it's available or not but i searched the index and there's not
please add ohm meter like the voltmeter but it measures the equivalent resistance in output menu

**Comment by pfalstad** [comment]
For now you can create a current source with current = 1A, then read the voltage across it and think ohms where it says volts. 🙂

**Comment by hayksk** [comment]
Hi Paul,
I tried the workaround suggested by you and it worked. 
It would be much better, however, if ohmmeter is made available.

**Comment by sharpie7** [comment]
Fixed in latest version.
