### ISSUE TITLE
LED brightness vs current curve

### ISSUE THREAD

**Issue by endolith** [sharpie7/circuitjs1#18]
In reality, I have an LED with 0.3 mA going through it, and another with 1.4 mA, and they're plenty bright.  I can't simulate this, though, because in the simulator, it looks like you need 10 mA to get full brightness, and it quickly dims to invisibility below this:

![led brightness](https://cloud.githubusercontent.com/assets/58611/18147851/79c15a28-6fa4-11e6-9e79-e05a7b7e4d65.png)

Is there some way to make the LED more realistic?  I'm not sure if this is because the brightness vs current curve should be nonlinear or if it's just efficiency differences between different LEDs, but I'd like to be able to have the LED at full brightness when the real LED is at "full" brightness, rather than using inaccurately small resistors in the simulation to make it visible, that then don't behave like reality.

**Comment by pfalstad** [comment]
Would it be enough to have a LED parameter to specify the current at max brightness?  This will vary depending on the LED.

**Comment by pfalstad** [comment]
fixed on my branch

**Comment by sharpie7** [comment]
Fixed in "one-year-updates" branch. Will merge to master in due course.

**Comment by pfalstad** [comment]
Ok I've been playing with some real LED's and it seems that the brightness should be a logarithmic function of current, not just linear.  I'll have a fix soon.
