### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by SebCanet** [sharpie7/circuitjs1#187]
Hello,
I like this project and wanted to use it for my students, but they are french and not very ease with english. How can I translate it ?
Could you enable a multi lang capabilities in Circuit ?
Thanks.

**Comment by sharpie7** [comment]
Bonjour!

The application does support localization. I haven't tried it myself, but @pfalstad knows how it works.

I think you just have to create a file similar to the locale_de.txt (but called locale_fr.txt) that is in the directory /src/com/lushprojects/circuitjs1/public/

**Comment by SebCanet** [comment]
Thanks a lot !

**Comment by pfalstad** [comment]
That's right, just translate that file and send it to me and I can help incorporate it into the site.

**Comment by SebCanet** [comment]
And the real will be to install Eclipse, understand Eclipse, anger and shout on Eclipse, try to install GWT, anger and shout on Eclipse, try to compile, anger and shout on Eclipse...
I'm not ease at all with this paritcular environnment.
Could it be possible for 'eclipse newbie' to have relkeases on Github ?
Thanks.

**Comment by pfalstad** [comment]
You don’t need to bother with eclipse, if you just want a French version of the simulator.  Just translate that file and send it to me.
