### ISSUE TITLE
better filename than "my circuit.txt"

### ISSUE THREAD

**Issue by endolith** [sharpie7/circuitjs1#19]
1. The default filename should contain a timestamp so the browser doesn't keep trying to overwrite the last one.
2. It should have a file extension other than `something.txt`, like `something.circuitjs`.  I was calling them `something.falstad.txt` for a while, but a real file extension would probably be better.

**Comment by sharpie7** [comment]
Fixed in my one-year-update branch. Will transfer to main brance later.
