### ISSUE TITLE
Transformer with zero inductance results in freeze

### ISSUE THREAD

**Issue by flarn2006** [sharpie7/circuitjs1#197]
Really simple, just place a transformer and set its primary inductance to 0 H. Then it won't respond to anything else.

**Comment by pfalstad** [comment]
Thanks for reporting.  We'll fix the freeze, but you still won't be able to set the inductance to 0.

**Comment by flarn2006** [comment]
You're welcome!

**Comment by sharpie7** [comment]
Fixed in latest version.
