### ISSUE TITLE
T flip flop is not toggling when it should

### ISSUE THREAD

**Issue by endolith** [sharpie7/circuitjs1#20]
I think this is a bug.  When T input is high and clock rises, the output should toggle to low, but it doesn't always do that.  Sometimes it waits until the _next_ rising edge to toggle.

```
$ 1 0.000005 10.200277308269968 50 5 50
R 256 400 224 400 1 2 100 2.5 2.5 0 0.5
w 256 400 256 272 0
w 256 272 336 272 0
L 272 240 224 240 0 0 true 5 0
M 432 240 464 240 0 2.5
193 336 240 384 240 4 0
w 336 304 272 240 0
152 432 160 336 160 0 2 0
w 336 160 336 240 0
w 432 144 432 80 0
w 432 80 272 80 0
w 272 240 272 80 0
w 432 176 432 240 0
o 3 64 0 551 5 0.00009765625 0 -1
o 0 64 0 551 5 0.00009765625 0 -1
o 4 64 0 550 5 0.00009765625 0 -1
```

![i think this is a bug the tff should toggle when clk goes high](https://cloud.githubusercontent.com/assets/58611/18364864/074d4c6e-75de-11e6-9e94-f67d2a490b16.png)

Tested that this happens in the original Java version, too.

**Comment by pfalstad** [comment]
yeah that's a bug.  It looks like the flip flop has the potential to have the wrong state on the next transition after set/reset is used.

**Comment by pfalstad** [comment]
fixed on my branch

**Comment by sharpie7** [comment]
Fixed in "one-year-updates" branch. Will merge to master in due course.
