### ISSUE TITLE
Bug - Op-Amp positive feedback behavior unreliable

### ISSUE THREAD

**Issue by Gearat** [sharpie7/circuitjs1#205]
Currently op-amp circuits behave oddly in situations where there should be positive feedback.  For example, swapping the terminals of a basic follower circuit results in no change in the circuit's output (i.e., the output in the simulation is unchanged).  Momentarily disconnecting the non-inverting terminal produces the correct behavior, until the simulation is reset.  Several other circuits similarly do not exhibit the expected behavior when the op-amp's inputs are reversed.

The same issues also can be reproduced in the Java version of the simulation from 2010.

[An example of the bug for follower circuits](http://www.falstad.com/circuit/circuitjs.html?cct=$+1+0.000005+10.20027730826997+57+5+50%0Av+96+224+96+80+0+1+40+5+0+0+0.5%0Ag+96+224+96+272+0%0Aw+192+176+192+224+0%0Aa+192+160+320+160+1+15+-15+1000000+-4.20468086456276+-4.204722911371405%0Aw+320+160+320+224+0%0Aw+96+80+192+80+0%0Aw+192+80+192+144+0%0Aw+192+224+320+224+0%0AO+384+160+432+160+0%0Aw+320+160+384+160+0%0Ar+384+160+384+224+0+1000%0Ag+384+224+384+272+0%0Ag+384+448+384+496+0%0Ar+384+384+384+448+0+1000%0Aw+320+384+384+384+0%0AO+384+384+432+384+0%0Aw+192+448+320+448+0%0Aw+192+304+192+368+0%0Aw+96+304+192+304+0%0Aw+320+384+320+448+0%0Aw+192+400+192+448+0%0Ag+96+448+96+496+0%0Av+96+448+96+304+0+1+40+5+0+0+0.5%0Aa+192+384+320+384+0+15+-15+1000000+-4.204722911371405+-4.204764959020996%0Ao+0+64+0+4098+5+0.00009765625+0+2+0+3%0Ao+8+64+0+4098+5+0.00009765625+0+1%0Ao+22+64+0+4098+5+0.00009765625+1+2+22+3%0Ao+15+64+0+12290+5.000050000500005+0.0001+1+1%0A)

**Comment by sharpie7** [comment]
Yes, it seems that there is a position where the static equations for the opamp are satisfied, but it is the equivalent of a cone balancing on its point (ie completely unstable). Unfortunately the sim currently converges to this point instead of going towards the edge-cases like it should do. Any ideas to address this @pfalstad ?

**Comment by pfalstad** [comment]
Wow this is a weird one.  Not sure if there is a simple way to fix this but I’ll look into it.

**Comment by felipenmartins** [comment]
I got that too: [http://tinyurl.com/yb2sawzm](http://tinyurl.com/yb2sawzm) 
The problem persists even after removing the connection to the non-inverting pin or reseting the simulation.

**Comment by pfalstad** [comment]
I haven't forgotten about this..  I've been racking my brain trying to think of a way to fix it.  I tried some really complex fixes, but I think I finally managed to find a simple way to resolve it.

**Comment by pfalstad** [comment]
Can't fix this.  Use an Op Amp (real) instead.
