### ISSUE TITLE
Realtime Simulation?

### ISSUE THREAD

**Issue by tinuxman** [sharpie7/circuitjs1#212]
I was just wondering if it's possible to simulate in real time? I built a switch-on delay and would like to test the "real" seconds. Thanks.

**Comment by NPG-3466** [comment]
maybe a changeable simulation speed.

**Comment by NPG-3466** [comment]
I just found out that if you do that ac sources won't work properly anymore. their frequency will change to 0.125 Hz

**Comment by sharpie7** [comment]
As you have found, the timestep needs to be small compared to the period of the highest frequency in the circuit of interest. That is how the simulation works: by looking at how the circuit changes over very small increments of time and summing these up to produce the long term behaviour.

Realtime simulation is no problem. You just need a fast enough computer. Good luck finding one!
