### ISSUE TITLE
Feature - websockets connection to local code (e.g. python)

### ISSUE THREAD

**Issue by raplin** [sharpie7/circuitjs1#218]
Lovely tool! 

**Short version:**
Ability to interact with browser simulation from locally running user code.

**Long version**
What would be awesome;
1) Make a circuit in circuitJS in browser
2a) Write a python (or whatever) program running locally in a console; say it's a simple CPU simulation that has an ADC input and a GPIO output, and turns on the "LED" when ADC>blah.
2b) include a websockets/circuitjs library in my python script
4) Have a "connect to localhost" button in circuitJS which opens a websocket
5) stream inputs and outputs from circuitjs to my code realtime; my locally running code can interact (with some accepted limitations) with the simulation in the browser.  

Implementation ideas;
a) A simple "pub/sub" model for monitoring/changing circuit node parameters would be great, plus start/stop/reset simulation.  I could say add a voltmeter or a current source (and maybe give them a friendly name) and then access them from my python code.  
b) I can imagine "async" and "sync" modes; async just blasts data back and forth over the websocket and doesn't pause the simulation (so a stimulus-response over the websocket has a minimum delay in terms of circuit time but the browser visuals run nice and smoothly (often this would be fine for many uses), conversely "sync mode" where the simulation is paused each tick and the user program can read/write as much as it wants before the simulation is continued (if that makes sense).
c) It'd be cool to be able to edit+restart the user script (which would be the websockets host) while the browser simulation remains running.  

It really doesn't have to be a perfect solution; even something quite basic (and with known issues) would still be most useful I think.  
Thank you!

**Comment by pfalstad** [comment]
Added.  See https://github.com/pfalstad/circuitjs1/tree/master/websocket
