### ISSUE TITLE
Feature - Printing

### ISSUE THREAD

**Issue by exekutive** [sharpie7/circuitjs1#224]
When one is finished creating and simulating a circuit, the next step is to build it! 

It is currently really difficult to get a circuit to print nicely with just the browser options. It would be great if there were a function to scale, crop, layout, and other wise format to look nice on a page.

**Comment by pfalstad** [comment]
Good idea, I'm looking into this.

**Comment by pfalstad** [comment]
done in 3e949813b842b3a82d2f566b64c7e62eba8f66ae
