### ISSUE TITLE
op amp simulation without voltage pins

### ISSUE THREAD

**Issue by her6betz** [sharpie7/circuitjs1#227]
I would like to support the voltage pin request on the op-amp. I got a setup here with an LM324 using +O---9V---O-ground-O---9V---O- as voltage source. However there seems no possibility to connect this to your op-amp-simulation.
[circuit-20180601-0715_OPV_blink.txt](https://github.com/sharpie7/circuitjs1/files/2061188/circuit-20180601-0715_OPV_blink.txt)
![no_opv_volt_pins_bug](https://user-images.githubusercontent.com/39820107/40823805-0cb60af8-6572-11e8-8336-8de31b22c947.jpg)

**Comment by pfalstad** [comment]
Hi, if the + and - voltages are fixed like in this example, you can just right click, Edit, change the max and min voltages to +9 and -9.

**Comment by her6betz** [comment]
Thanks, but I cannot see, how to connect the voltage source to the op-amp and so make a run possible?

**Comment by billcollis** [comment]
I made a model with power pins to show students that opamps weren't magic

OpAmpSwapPwrElm.java
`package com.lushprojects.circuitjs1.client;

//import java.awt.*;
//import java.util.StringTokenizer;


/* Bill Collis June 2015
 * 
 * want to show current to/from power supply connections
 * 
 * ID = 352
 * */

    class OpAmpPwrElm extends CircuitElm {
	int opsize, opheight, opwidth, opaddtext;
	double maxOut, minOut, gain, gbw;
	boolean reset;
	final int FLAG_SWAP = 1;
	final int FLAG_SMALL = 2;
	final int FLAG_LOWGAIN = 4;
	public OpAmpPwrElm(int xx, int yy) {
	    super(xx, yy);
	    noDiagonal = true;
	    maxOut = 15;
	    minOut = -15;
	    gbw = 1e6;
	    setSize(sim.smallGridCheckItem.getState() ? 1 : 2);
	    setGain();
	    compLabel="U"; //BC compID will be generated in CirSim.java
	}
	public OpAmpPwrElm(int xa, int ya, int xb, int yb, int f,
			StringTokenizer st) {
	    super(xa, ya, xb, yb, f);
	    maxOut = 15;
	    minOut = -15;
	    // GBW has no effect in this version of the simulator, but we
	    // retain it to keep the file format the same
	    gbw = 1e6;
	    try {
		maxOut = new Double(st.nextToken()).doubleValue();
		minOut = new Double(st.nextToken()).doubleValue();
		gbw = new Double(st.nextToken()).doubleValue();
	    } catch (Exception e) {
	    }
	    noDiagonal = true;
	    setSize((f & FLAG_SMALL) != 0 ? 1 : 2);
	    setGain();
	    compLabel="U"; //BC
	    compID=0;
	    if (st.hasMoreTokens()){
		    String tok = st.nextToken(); 
		    if (tok.indexOf('@')>-1)
		    	compID = new Integer (tok.replace('@', ' ').trim()).intValue();
	    }

	}
	void setGain() {
	    // gain of 100000 breaks e-amp-dfdx.txt
	    // gain was 1000, but it broke amp-schmitt.txt
	    gain = ((flags & FLAG_LOWGAIN) != 0) ? 1000 : 100000;
	    
	}
	String dump() {
		if (compID>0)//BC
			return super.dump() + " " + maxOut + " " + minOut + " " + gbw + " @" + compID;//BC
		else
			return super.dump() + " " + maxOut + " " + minOut + " " + gbw;
	}
	boolean nonLinear() { return true; }
	void draw(Graphics g) {
	    setBbox(point1, point2, opheight*2);
	    //input 1
	    setVoltageColor(g, volts[0]);
	    drawThickLine(g, in1p[0], in1p[1]);
	    //input 2
	    setVoltageColor(g, volts[1]);
	    drawThickLine(g, in2p[0], in2p[1]);
	    //body
	    g.setColor(needsHighlight() ? selectColor : lightGrayColor);
	    setPowerColor(g, true);
	    drawThickPolygon(g, triangle);
	    //text + -
	    g.setFont(plusFont);
	    drawCenteredText(g, "-", textp[0].x, textp[0].y-2, true);
	    drawCenteredText(g, "+", textp[1].x, textp[1].y  , true);
	    //output
	    setVoltageColor(g, volts[2]);
	    drawThickLine(g, lead2, point2);
	    curcount = updateDotCount(current, curcount);
	    drawDots(g, point2, lead2, curcount);
	    drawPosts(g);
	    
	    	    
	    //added these points vposp[], vnegp[], vtextp[]
	    setVoltageColor(g, maxOut);
	    drawThickLine(g,vposp[0],vposp[1]);
	    drawCenteredText(g, "+"+getVoltageText(maxOut), vtextp[0].x, vtextp[0].y-10, true);
	    
	    setVoltageColor(g, minOut);
	    drawThickLine(g,vnegp[0],vnegp[1]);
	    drawCenteredText(g, getVoltageText(minOut), vtextp[1].x, vtextp[1].y+10, true);
	    //depends on  current direction and polarity of output
	    if (current<0)
	    drawDots(g, vposp[1], vposp[0], curcount);
	    else
	    drawDots(g, vnegp[1], vnegp[0], curcount);
	}
	double getPower() { return volts[2]*current; }
	Point in1p[], in2p[], textp[];
	Point vposp[], vnegp[], vtextp[]; //****
	Polygon triangle;
	Font plusFont;
	void setSize(int s) {
	    opsize = s;
	    opheight = 8*s;
	    opwidth = 13*s;
	    flags = (flags & ~FLAG_SMALL) | ((s == 1) ? FLAG_SMALL : 0);
	}
	void setPoints() {
	    super.setPoints();
	    if (dn > 150 && this == sim.dragElm)
		setSize(2);
	    int ww = opwidth;
	    if (ww > dn/2)
		ww = (int) (dn/2);
	    calcLeads(ww*2);
	    int hs = opheight*dsign;
	    vposp = newPointArray(2); //**calculate the extra line positions- dont swap
	    vnegp = newPointArray(2);
	    vtextp = newPointArray(2);
	    interpPoint2(lead1 , lead2, vposp[0], vnegp[0], 0.5, hs*2); //find halfway between 
	    interpPoint2(lead1 , lead2, vposp[1], vnegp[1], 0.5, hs);
	    interpPoint2(lead1 , lead2, vtextp[0], vtextp[1], 0.6, hs*2);
	    
	    if ((flags & FLAG_SWAP) != 0) 
	    	hs = -hs;
	    in1p = newPointArray(2);
	    in2p = newPointArray(2);
	    textp = newPointArray(2);	    
	    interpPoint2(point1, point2, in1p[0],  in2p[0], 0, hs); //calc in1p[0] in2p[0], 0=left
	    interpPoint2(lead1 , lead2,  in1p[1],  in2p[1], 0, hs);
	    interpPoint2(lead1 , lead2,  textp[0], textp[1], .2, hs); //0.2 means to the right a little
	    Point tris[] = newPointArray(2);
	    interpPoint2(lead1,  lead2,  tris[0], tris[1],  0, hs*2);
	    triangle = createPolygon(tris[0], tris[1], lead2);
	    plusFont = new Font("SansSerif", 0, opsize == 2 ? 14 : 10);
	    
	    
	}
	int getPostCount() { return 5; } //added 2 extra points
	Point getPost(int n) {
	    return (n == 0) ? in1p[0] : (n == 1) ? in2p[0] : (n == 2) ? point2 : (n == 3) ? vposp[0] : vnegp[0];
	}
	int getVoltageSourceCount() { return 1; }
	void getInfo(String arr[]) {
		if (compID == 0)
			arr[0] = "op-amp";
		else
			arr[0] = "op-amp" +" U" + compID;
	    arr[1] = "V+ = " + getVoltageText(volts[1]);
	    arr[2] = "V- = " + getVoltageText(volts[0]);
	    // sometimes the voltage goes slightly outside range, to make
	    // convergence easier.  so we hide that here.
	    double vo = Math.max(Math.min(volts[2], maxOut), minOut);
	    arr[3] = "Vout = " + getVoltageText(vo);
	    arr[4] = "Iout = " + getCurrentText(-current);
	    arr[5] = "range = " + getVoltageText(minOut) + " to " + getVoltageText(maxOut);

	}

	double lastvd;

	void stamp() {
	    int vn = sim.nodeList.size()+voltSource;//create virtual node?
	    sim.stampNonLinear(vn);					//indicate that doStep changes these values
	    sim.stampMatrix(nodes[2], vn, 1);		//initial value?rel between nodes[2] and vn is 1(equal)?
	}
	void doStep() {
	    double vd = volts[1] - volts[0];
	    if (Math.abs(lastvd-vd) > .1)
	    	sim.converged = false;
	    else if (volts[2] > maxOut+.1 || volts[2] < minOut-.1)
	    	sim.converged = false;
	    double x = 0;
	    int vn = sim.nodeList.size()+voltSource;
	    double dx = 0;
	    if (vd >= maxOut/gain && (lastvd >= 0 || sim.getrand(4) == 1)) {
	    	dx = 1e-4;
	    	x = maxOut - dx*maxOut/gain;
	    } else if (vd <= minOut/gain && (lastvd <= 0 || sim.getrand(4) == 1)) {
	    	dx = 1e-4;
	    	x = minOut - dx*minOut/gain;
	    } else
		dx = gain;
	    //System.out.println("opamp " + vd + " " + volts[2] + " " + dx + " "  + x + " " + lastvd + " " + sim.converged);
	    
	    // newton-raphson
	    sim.stampMatrix(vn, nodes[0], dx); //put gain into matrix
	    sim.stampMatrix(vn, nodes[1], -dx);
	    sim.stampMatrix(vn, nodes[2], 1); //vn and nodes[2] are the same pt
	    sim.stampRightSide(vn, x);			//x is vout
	    
	    lastvd = vd;
	    /*if (sim.converged)
	      System.out.println((volts[1]-volts[0]) + " " + volts[2] + " " + initvd);*/
	}
	// there is no current path through the op-amp inputs, but there
	// is an indirect path through the output to ground.
	boolean getConnection(int n1, int n2) { return false; }
	boolean hasGroundConnection(int n1) {
	    return (n1 == 2);
	}
	double getVoltageDiff() { return volts[2] - volts[1]; }
	int getDumpType() { return 352; }
	public EditInfo getEditInfo(int n) {
	    if (n == 0)
		return new EditInfo("Max Output (V)", maxOut, 1, 20);
	    if (n == 1)
		return new EditInfo("Min Output (V)", minOut, -20, 0);
	    if (n == 2)
	    	return new EditInfo("Component ID", compID, 0, 0).setDimensionless();
	    return null;
	}
	public void setEditValue(int n, EditInfo ei) {
	    if (n == 0)
		maxOut = ei.value;
	    if (n == 1)
		minOut = ei.value;
	    if (n == 2)
	    	compID = (int)ei.value;
	}
	@Override double getCurrentIntoPoint(int xa, int ya) { 		
	    if (xa == x2 && ya == y2)		
		return -current;		
	    return 0;		
	}
}
`

OpAmpSwapPwrElm.java
`package com.lushprojects.circuitjs1.client;

class OpAmpSwapPwrElm extends OpAmpPwrElm {
	public OpAmpSwapPwrElm(int xx, int yy) {
	    super(xx, yy);
	    flags |= FLAG_SWAP;
	}
	Class getDumpClass() { return OpAmpPwrElm.class; }
    }
`

**Comment by pfalstad** [comment]
Sorry for the late response her6betz, I didn't see your latest message for some reason.

I got your circuit working.  The problem is that the time step was way too small to show anything happening in the circuit in a reasonable amount of time.

http://tinyurl.com/ycb5tg55

The op amps in the simulator are always connected to an external voltage, but this isn't shown, just to simplify the view of the circuit.

**Comment by pfalstad** [comment]
Thanks billcollis, can I use this?

**Comment by Exaeta** [comment]
Hello. I wanted to use one of these to test a voltage regulator design. But it wont be a very good test if the voltage is already regulated.

Would it be possible to add these pins?

**Comment by ormaaj** [comment]
If the CCVS expression accepted a function that takes an input name and returns its voltage then it might be possible to have supply pins that sink current correctly. Still circuits that have multiple sources are trouble because there's no way to assert what proportion of current at an input is supplied by which source and ensure the output equals the sum of the input currents at all times.

Also the op amps have no option to choose DC offset like the sources do (and those have some weird behaviours). The only way I've found to eliminate side effects from magic sources is to ensure only 2-termanal sources are used and make sure nothing generates negative voltages. Sometimes the mere presence of the ground symbol or a 1-terminal source alters the circuit, even if it's a floating node.

**Comment by pfalstad** [comment]
You can use Op Amp (real) now.
