### ISSUE TITLE
Optocoupler and output function not in menu

### ISSUE THREAD

**Issue by her6betz** [sharpie7/circuitjs1#228]
I was looking for an optocoupler (like issue #193), but found none in the menu. In one of the comments I came accross an "output function", also not in the menu ...

1) Why can I not find some optocoupler in the menu?

2) What is an output fct.? Probably simply a black box? I found, a value of "-0.2*i" in this device worked (see image below), but "0.2*i" did not so well?

3) Could I mimic an optocoupler using an output function?

output_fct.txt:
$ 1 0.000005 10.20027730826997 50 5 43
215 0 128 48 128 0 2 -0.2*i

![out_fct](https://user-images.githubusercontent.com/39820107/40885789-8245cdfa-672d-11e8-96aa-71e8939460f0.jpg)

**Comment by pfalstad** [comment]
Hi, that's a current-controlled current source (CCCS), and it's in the menu.  "Output function" isn't being translated to German, which is a bug.  The output function is just an expression for the output current in terms of the input current.  Why doesn't 0.2i work?  It seems to work for me.

**Comment by her6betz** [comment]
Thanks for the fast reply. I'm a hobbyist and very enthusiastic about your simulator and your support ...

So obviously CCCS has nothing to do with an optocoupler ...

**Comment by sharpie7** [comment]
Correct - a CCCS is nothing to do with an optocoupler. I will close this issue as #193 already contains a request to add an optocoupler.
