### ISSUE TITLE
Feature request: DC motor / DC brushless fan

### ISSUE THREAD

**Issue by Uzer1** [sharpie7/circuitjs1#235]
Hello. I am making a simple circuit to control my PC fans voltages depending on the temperature on a thermal resistor. 
The program Circuit Simulator 1.6i does not have a thermal resistor and an electric motor / dc fan. 
These are most common parts. I can emulate the thermal resistor [NC-type] by dragging the ohm selector in resistor options. However, the closest way I found to a dc motor is a lamp or a light diode. Is there a better way to select/emulate a dc motor? Will the motor be added to the program built-in parts selection?

**Comment by parq** [comment]
+1
Please add a DC motor component.
Thank you in advance.

**Comment by annopnod** [comment]
add stepper motor
https://www.youtube.com/watch?v=TWMai3oirnM

**Comment by pablorq** [comment]
Ok. I'll see it later.

**Comment by DmitriKhanoukaev** [comment]
Hi, I'm trying to simulate circuit with DC motor and it seems not implemented. Or is there a trick how to add it?

**Comment by pfalstad** [comment]
Added DC motor contributed by Francisco Campos.
