### ISSUE TITLE
Bug - Do-nothing resistor changes behavior when removed

### ISSUE THREAD

**Issue by skylord-a52** [sharpie7/circuitjs1#247]
This circuit is a simple oscillator, equipped with a switchable voltage source connected with MOSFETs (yes, I know I could just use a single switch, but the MOSFETs are a holdover from a more complicated design and the bug disappears when you remove them). When the switch is open, the transistors allow power through to the inductor, building up more and more stored energy as the current increases, and when it's closed, the inductor releases that energy and the capacitor/inductor loop oscillates.

Inside the big loop created by the lines from the switch to the MOSFETs, there's a single wire segment connected to a resistor that doesn't go anywhere. Neither the wire or the resistor should have any affect on the rest of the circuit at all, but if you delete either of them the behavior of the circuit changes drastically. When the switch is opened, the voltage source and the oscillator sort of fight against one another and end up stalling almost completely.

```$ 1 0.000005 10.20027730826997 50 5 50
r 176 256 176 352 0 10
l 368 208 368 144 0 1 0
w 304 144 304 176 0
w 304 176 176 176 0
w 176 208 176 256 0
w 112 192 112 224 0
s 112 224 48 224 0 0 false
R 48 224 0 224 0 0 40 5 0 0 0.5
w 304 144 368 144 0
c 432 144 432 208 0 0.00001 0.001
w 112 384 112 224 0
w 432 144 368 144 0
f 112 192 176 192 53 1.5 0.02
f 336 288 336 208 53 1.5 0.02
w 352 208 368 208 0
w 336 288 336 384 0
w 336 384 112 384 0
w 368 208 432 208 0
w 320 208 288 208 0
r 176 208 224 208 0 10
v 224 208 288 208 0 0 40 5 0 0 0.5
o 1 64 0 4099 0.00244140625 0.00009765625 0 2 1 3
o 9 64 0 4099 0.00244140625 0.00009765625 1 2 9 3
o 12 64 0 4099 10 0.00009765625 2 2 12 3
o 13 64 0 4099 10 0.00009765625 3 2 13 3
```

**Comment by pfalstad** [comment]
You should add a ground node to the circuit.  When there's no ground, the simulator arbitrarily picks one of the resistor terminals (since that's the first element).  If there's no resistor, then it picks one of the inductor terminals (since that's the second) and that changes the circuit behavior.
