### ISSUE TITLE
Bug - "Export as Link" fails when circuit uses slider

### ISSUE THREAD

**Issue by herrmanthegerman** [sharpie7/circuitjs1#255]
Hi there,

I simulated the following small circuit:

```
$ 1 6.25e-7 16.817414165184545 52 5 43
c 384 176 384 320 0 0.00021999999999999998 11.527173920823325
l 384 176 288 176 0 0.000047 -1.9398013248384707
r 480 176 480 320 0 11
w 384 176 480 176 0
v 64 320 64 176 0 0 40 24 0 0 0.5
w 240 176 288 176 0
w 128 320 64 320 0
g 64 320 64 352 0
R 128 240 128 288 0 2 50000 2 22 0 0.5545
p 480 176 544 176 1 0
d 288 256 288 176 1 0.805904783
w 288 320 288 304 0
s 288 256 288 304 0 0 false
w 160 176 160 112 0
w 192 176 160 176 0
w 240 112 240 176 0
w 240 176 224 176 0
w 160 112 160 32 0
w 240 112 240 32 0
p 160 32 240 32 1 0
w 128 320 288 320 0
w 288 320 384 320 0
w 192 240 208 240 0
s 288 96 368 96 0 1 false
w 288 96 288 176 0
w 384 176 384 96 0
w 368 96 384 96 0
r 192 240 144 240 0 140
w 128 240 144 240 0
t 208 240 208 176 1 -1 -0.627681381203189 -0.7914625260066224 100
370 64 176 160 176 1 0
370 480 320 384 320 1 0
o 2 64 0 4614 23.34298377123183 0.0001 0 1
o 8 64 0 4098 40 0.1 1 2 8 3
o 30 64 0 20997 40 3.2 2 2 30 3
o 31 64 3 20487 0.0000762939453125 3.2 2 1
& 8 5 1 100 Duty\sCycle
```
The circuit includes a *slider* to change the `Duty Cycle` of the Square Wave source:
```    & 8 5 1 100 Duty\sCycle  ```

Now with this circuit open, when I select `File > Export as Link` , and then copy the URL (click in text and type control-A) and open a new browser window using the copied URL, the URL loads but the window stays blank (completely white background).

When I remove the *slider* (last line of the circuit text file above) from the circuit,  `Export as Link` works.

My guess is that the  `&` (ampersand) is somehow the culprit. It needs to be *urlencoded*.

PS: Thanks for this great tool!

**Comment by sharpie7** [comment]
Thanks for reporting - fixed in latest version.
