### ISSUE TITLE
Feature- Compress parameter in URL export

### ISSUE THREAD

**Issue by emlun** [sharpie7/circuitjs1#257]
Hi! Thanks for making this very useful tool!

One minor issue I encountered when I exported [this circuit][circuit] as URL is that the URL ends up at 4113 characters. I'd like to suggest a technique I used previously to alleviate this exact problem: gzip and base64 encode the parameter. When done on the example above, the size of the URL drops to about 1580 characters, and it should also grow at a slower pace for larger circuits. This means that much larger assemblies could fit into the soft 2000 character limit for URLs.

I tried to implement this myself, but ran into problems since I'm not familiar with how GWT works. Specifically, I couldn't get GWT to compile the `java.io.ByteArrayInputStream` and `java.util.zip.GZIPInputStream` classes or their `OutputStream` counterparts, and Java 1.5 also doesn't include the `java.util.Base64` class. Base64 en/decoding probably wouldn't be too hard to implement myself, but I don't know how to best deal with the other problem.

In case it's useful, the way I intended to implement it is like this:

- In the [ExportAsUrlDialog][exurl] constructor, assign `String query="?cct_v2=" + compress(dump);` instead of `String query="?cct=" + URL.encode(dump);`, where pseudocode for `compress` is

    ```
    private static String compress(String input) {
      return new String(base64encode(gzip(input.getBytes("UTF-8"))), "UTF-8");
    }
    private static byte[] base64encode(byte[]);
    private static byte[] gzip(byte[]);
    ``` 
- In [CirSim.init()][cirsim], add decompression logic along the lines of

    ```
    String cct = qp.getValue("cct");
    if (cct == null) {
      String cct_v2 = qp.getValue("cct_v2");
      if (cct_v2 != null) {
        startCircuitText = decompress(cct_v2);
      }
    } else {
      startCircuitText = cct.replace("%24", "$");
    }
    ```

    where pseudocode for `decompress` is

    ```
    private static String decompress(String input) {
      return new String(gunzip(base64decode(input.getBytes("UTF-8"))), "UTF-8");
    }
    private static byte[] base64decode(byte[]);
    private static byte[] gunzip(byte[]);
    ```

I think that should be all that's necessary for this to work. I'd be happy to contribute a PR for this, but I don't know how I can implement the `gzip` and `gunzip` methods within the constraints of GWT. I'd be happy to give this another try if you can provide some advice on how to tackle that.

Thanks again for the tool!

[circuit]: http://www.falstad.com/circuit/circuitjs.html?cct=$+1+0.000005+10.20027730826997+54+5+50%0AL+144+272+144+80+0+0+false+5+0%0Aw+208+240+288+240+0%0AM+416+240+416+208+0+2.5%0AL+128+320+128+80+0+0+false+5+0%0Ar+208+192+208+240+0+1000%0Aw+208+240+208+256+0%0Ag+208+288+208+304+0%0Ag+288+288+288+304+0%0Af+144+272+208+272+32+1.5+0.02%0Af+240+272+288+272+32+1.5+0.02%0Af+240+432+288+432+32+1.5+0.02%0Af+144+432+208+432+32+1.5+0.02%0Ag+288+448+288+464+0%0Ag+208+448+208+464+0%0Aw+208+400+208+416+0%0Ar+208+352+208+400+0+1000%0Aw+208+400+288+400+0%0Aw+128+320+240+320+0%0Aw+240+320+240+272+0%0AR+208+352+176+352+0+0+40+5+0+0+0.5%0AR+208+192+176+192+0+0+40+5+0+0+0.5%0AL+592+240+592+96+0+0+false+5+0%0Af+320+432+368+432+32+1.5+0.02%0Ag+368+448+368+464+0%0Ar+368+352+368+400+0+1000%0Aw+288+400+288+416+0%0Aw+320+496+320+432+0%0Aw+368+416+368+400+0%0Aw+368+400+400+400+0%0Aw+400+400+400+480+0%0Aw+240+480+240+432+0%0Aw+288+400+288+336+0%0Aw+288+336+416+336+0%0AM+416+336+416+304+0+2.5%0Aw+208+352+256+352+0%0Aw+288+256+288+240+0%0Aw+288+240+416+240+0%0Aw+400+480+240+480+0%0Aw+256+352+368+352+0%0Aw+320+496+128+496+0%0Aw+128+496+128+320+0%0Aw+144+432+144+272+0%0Aw+144+528+144+432+0%0Aw+128+544+128+496+0%0AM+416+544+416+512+0+2.5%0Aw+288+544+416+544+0%0Aw+288+608+288+544+0%0Aw+240+544+240+640+0%0Aw+80+608+144+608+0%0Aw+80+624+80+608+0%0Aw+288+608+288+624+0%0Ar+80+560+80+608+0+1000%0Ag+80+656+80+672+0%0Af+32+640+80+640+32+1.5+0.02%0AR+80+560+48+560+0+0+40+5+0+0+0.5%0Aw+208+608+288+608+0%0Ar+208+560+208+608+0+1000%0Aw+208+608+208+624+0%0Ag+208+656+208+672+0%0Ag+288+656+288+672+0%0Af+144+640+208+640+32+1.5+0.02%0Af+240+640+288+640+32+1.5+0.02%0Aw+144+528+32+528+0%0Aw+32+528+32+640+0%0Aw+80+560+208+560+0%0Aw+144+608+144+640+0%0Aw+240+544+128+544+0%0Aw+128+544+128+704+0%0Af+240+800+288+800+32+1.5+0.02%0Af+160+800+208+800+32+1.5+0.02%0Ag+288+816+288+832+0%0Aw+208+752+208+784+0%0Ar+208+704+208+752+0+1000%0Aw+288+768+288+784+0%0AR+208+704+176+704+0+0+40+5+0+0+0.5%0Aw+208+816+224+816+0%0Aw+224+816+224+768+0%0Aw+224+768+288+768+0%0Aw+128+704+128+832+0%0Aw+128+832+240+832+0%0Aw+240+832+240+800+0%0Aw+160+800+160+688+0%0Aw+160+688+160+528+0%0Aw+160+528+144+528+0%0Aw+208+752+320+752+0%0AM+416+752+416+720+0+2.5%0Af+320+800+368+800+32+1.5+0.02%0Ag+368+816+368+832+0%0Aw+320+752+320+800+0%0Ar+368+704+368+752+0+1000%0Aw+208+704+368+704+0%0Aw+368+752+368+784+0%0Aw+368+752+416+752+0%0Ag+544+256+544+272+0%0Af+496+240+544+240+32+1.5+0.02%0Ag+544+352+544+368+0%0Af+496+336+544+336+32+1.5+0.02%0Ag+544+560+544+576+0%0Af+496+544+544+544+32+1.5+0.02%0Ag+544+768+544+784+0%0Af+496+752+544+752+32+1.5+0.02%0Aw+416+752+496+752+0%0Aw+416+544+496+544+0%0Aw+416+336+496+336+0%0Aw+416+240+496+240+0%0Af+704+240+752+240+32+1.5+0.02%0Af+704+336+752+336+32+1.5+0.02%0AL+624+336+624+96+0+1+false+5+0%0Af+704+544+752+544+32+1.5+0.02%0AL+656+544+656+96+0+0+false+5+0%0Af+704+752+752+752+32+1.5+0.02%0AL+688+752+688+96+0+0+false+5+0%0Ar+784+144+784+192+0+1000%0AR+784+144+752+144+0+0+40+5+0+0+0.5%0Aw+784+192+784+224+0%0Aw+784+224+752+224+0%0Aw+784+224+784+320+0%0Aw+784+320+784+528+0%0Aw+784+528+784+736+0%0Aw+784+736+752+736+0%0Aw+752+528+784+528+0%0Aw+752+320+784+320+0%0Aw+752+256+752+272+0%0Aw+752+272+576+272+0%0Aw+576+272+576+224+0%0Aw+576+224+544+224+0%0Aw+608+320+544+320+0%0Aw+608+368+608+320+0%0Aw+752+368+608+368+0%0Aw+752+576+608+576+0%0Aw+608+576+608+528+0%0Aw+608+528+544+528+0%0Aw+752+784+608+784+0%0Aw+608+784+608+736+0%0Aw+608+736+544+736+0%0Aw+752+352+752+368+0%0Aw+752+560+752+576+0%0Aw+752+768+752+784+0%0Af+880+240+928+240+32+1.5+0.02%0Ag+928+256+928+272+0%0Aw+784+224+880+224+0%0Aw+880+224+880+240+0%0AR+928+144+896+144+0+0+40+5+0+0+0.5%0Ar+928+144+928+192+0+1000%0Aw+928+192+928+224+0%0Aw+928+224+976+224+0%0AM+976+224+1040+224+0+2.5%0Ax+100+62+130+65+4+24+S0%0Ax+141+61+171+64+4+24+S1%0Ax+399+265+430+268+4+24+SA%0Ax+404+363+435+366+4+24+SB%0Ax+401+574+433+577+4+24+SC%0Ax+400+778+433+781+4+24+SD%0Ax+583+76+599+79+4+24+A%0Ax+615+76+631+79+4+24+B%0Ax+647+75+664+78+4+24+C%0Ax+680+77+698+80+4+24+D%0Ax+1030+208+1049+211+4+24+O%0Aw+592+240+704+240+0%0Aw+704+336+624+336+0%0Aw+656+544+704+544+0%0Aw+688+752+704+752+0%0A
[exurl]: https://github.com/sharpie7/circuitjs1/blob/6c5f60b2bcbe48e150bc4feebe1dbe6aee116f8c/src/com/lushprojects/circuitjs1/client/ExportAsUrlDialog.java#L93
[cirsim]: https://github.com/sharpie7/circuitjs1/blob/c2fa42257baca9388ae5f8d66fd736d065d5ce27/src/com/lushprojects/circuitjs1/client/CirSim.java#L329-L331

**Comment by sharpie7** [comment]
Updated
