### ISSUE TITLE
Bug - voltage source in parallel reports error

### ISSUE THREAD

**Issue by jgfoster** [sharpie7/circuitjs1#258]
A simple circuit with one voltage source works fine. A simple circuit with two voltage sources in series works fine. A simple circuit with two voltage sources in parallel reports an error: "Voltage source/wire loop with no resistance!" See http://tinyurl.com/y79p8lgl.

I'm not an electrical engineer, so I may misunderstand this, but I'm copying an example from a text and I believe that batteries in parallel should work fine.

**Comment by pfalstad** [comment]
Hi, you need to add resistance into the loop.  This is a limitation of the simulator that would be very hard to fix.

The voltage sources in this app are ideal, but a real voltage source would have some resistance.  So if you add a small resistor in series with each voltage source, it will work.
