### ISSUE TITLE
SCR doesn't seem to latch

### ISSUE THREAD

**Issue by tavdog** [sharpie7/circuitjs1#261]
I've tried using the SCR component but it doesn't seem to work as an SCR is supposed to.  All the current just goes through the gate and then stops as soon as the gate is detached. Isn't the current supposed to continue even after the gate signal is removed ?
<img width="856" alt="screen shot 2018-10-03 at 3 wed 11 40 06 am" src="https://user-images.githubusercontent.com/8324295/46441120-3bfaff80-c701-11e8-8d54-725159e1e227.png">

**Comment by pfalstad** [comment]
Hi, if you put a small resistor in series with the gate, it works.  This may be a bug..  I'd have to test with a real SCR or another simulator to be sure.

http://tinyurl.com/y6uzshtr
