### ISSUE TITLE
CircuitJS Crowdin Project

### ISSUE THREAD

**Issue by Marino108** [sharpie7/circuitjs1#263]
I would like to translate the app into Croatian language. I think other users would like to do the same. Can you create a Crowdin project?

Thak you,
Marino

**Comment by pfalstad** [comment]
That costs money, doesn't it?  :)

**Comment by Marino108** [comment]
I assumed it was free.

**Comment by pfalstad** [comment]
It's not free, it would cost me $50 per month since there are >1000 source strings.  If anyone wants to do a translation, here is a sample strings file: https://github.com/sharpie7/circuitjs1/blob/master/src/com/lushprojects/circuitjs1/public/locale_es.txt
