### ISSUE TITLE
Example circuit: Novel Full-Wave Rectifier (Single Transistor Rectifier)

### ISSUE THREAD

**Issue by ocouch** [sharpie7/circuitjs1#268]
I have to say, this little circuit simulator is awesome!

Looking around for a precision rectifier circuit, I discovered a paper from 1979 describing a single transistor rectifier. It's essentially a special version of a common emitter amplifier. It's such an awesome little circuit it's definitely worth chucking in there!. https://ieeexplore.ieee.org/document/1455569

It's good for rectifying an AC input down to about ±100mV according to the paper!

Link to circuit: http://tinyurl.com/y8wrp73l

**Comment by pfalstad** [comment]
Thank you!  (a bit late)
