### ISSUE TITLE
Cannot set voltage on zener diode

### ISSUE THREAD

**Issue by janwest2** [sharpie7/circuitjs1#279]
Seems like the diode model change also defunct the setting of zener voltage.

**Comment by pfalstad** [comment]
You can still change the zener voltage but there's more steps involved.  Right click edit, select custom model, change the model name to something else (like custom-zener), click Edit Model, then change the breakdown voltage to whatever you want and click Ok.

**Comment by janwest2** [comment]
Thanks, it works perfectly :-)
