### ISSUE TITLE
Add:Prevent Accidentally Closing Your Browser 

### ISSUE THREAD

**Issue by annopnod** [sharpie7/circuitjs1#281]
**add onbeforeunload function**

&lt;body onbeforeunload=&quot;return closewinfn()&quot;&gt;
  
&lt;script&gt;
function closewinfn() {
    return &quot;Confirm Exit Data Loss&quot;;
}
&lt;/script&gt;
&lt;/body&gt;

**Comment by pfalstad** [comment]
For now, you can do File->Recover Auto-Save when you accidentally close your browser.

**Comment by pfalstad** [comment]
You get a confirmation dialog now.
