### ISSUE TITLE
Cutoff Frequency on afilter applet

### ISSUE THREAD

**Issue by AdvelC** [sharpie7/circuitjs1#284]
For the afilter applet if you bring in a Low-Pass filter (RC) there is Cutoff Frequency slider control that is shown to the right and linked to the capacitor value. The frequency response chart shows the Cutoff frequency. If I design my own circuit, or export then import the circuit I can't seem to get the cutoff frequency value to show.

**Comment by pfalstad** [comment]
Yes, when you bring up one of the predefined filters, it lets you set the filter parameters, like cutoff frequency.  But if you make your own circuit, it won't do that..  It lets you modify the components yourself, and shows you the frequency response, but you can't change the cutoff frequency with a slider.  It would have to analyze the circuit and try to figure out what kind of filter it is, but right now it doesn't do that.

**Comment by AdvelC** [comment]
I didn't realise the cutoff frequency was calculated from the specific components in the schematic, I thought it would have been determined from -3db data on the frequency response plot. It makes sense now you've explained how it's implemented. Great tool BTW, and pleased to see that it's still being developed and maintained. The gear icon on the scope plots are new since I last used it.
