### ISSUE TITLE
Odd LED flashing problem in simulation

### ISSUE THREAD

**Issue by rosshwheeler** [sharpie7/circuitjs1#286]
Can't see why these LEDs are flashing, can you?
http://tinyurl.com/y8rbst4m

Also, would it be possible/practical to have a direct way to enter LEDs Vf directly?

**Comment by E3V3A** [comment]
Yeah, that look funny!
Would be great to hear if this is a real effect or just due to simulation artifacts

**Comment by pfalstad** [comment]
That's a simulation artifact.   The problem is that the LED model has a saturation current that is way too small, and that is causing numerical error.  That's why you're seeing phantom currents across the resistors, etc.

I added a direct way to enter LED Vf's.

**Comment by pfalstad** [comment]
Fixed
