### ISSUE TITLE
mouse wheel zoom goes in wrong direction

### ISSUE THREAD

**Issue by pfalstad** [sharpie7/circuitjs1#288]
Someone pointed out that rolling the mouse wheel down zooms in, while in other applications (like google maps, chrome, ms word) it zooms out.  Should we reverse the direction?

**Comment by SgtSchultz71** [comment]
I don't find it a problem when I build. Also, I wanted to say thank you so much for keeping this project alive and well by fixing bugs and adding great content!

**Comment by E3V3A** [comment]
Since nobody else seem to care, I vote for changing to standard. 
Zoom out is also down for Acrobat.
