### ISSUE TITLE
Feature - Add dinistor (diac)

### ISSUE THREAD

**Issue by CEBA77** [sharpie7/circuitjs1#296]
One of the users did not find a varistor and dinistor in the program.

If I understand correctly, the question of varistors can be attributed to this issue: https://github.com/sharpie7/circuitjs1/issues/70

It seems to me that the name "dinistor" may be incorrect in English. In different literature, a dinistor may have the name "trigger diode" and "diac". Thanks.

**Comment by sharpie7** [comment]
Done in latest version
