### ISSUE TITLE
Feature request: more than 2 states for logic input

### ISSUE THREAD

**Issue by archivewarrior** [sharpie7/circuitjs1#299]
I have noticed that in a couple of circuits (like in F210 under Ternary Logic Families), there are logic inputs that have not two states, but three, or even more (0, 1, and 2, in the case of F210). I haven't found anything in the Edit Component screen that stands out as relating to this, other than that the Numeric box is checked. It would be nice to have a way to get this in a custom circuit.

**Comment by pfalstad** [comment]
For now you can copy and paste one of the magic outputs from the F210 circuit.

**Comment by pfalstad** [comment]
Added
