### ISSUE TITLE
Resize circuit

### ISSUE THREAD

**Issue by mannanj** [sharpie7/circuitjs1#3]
Hi first off thank you very much for making this port. It works great! Is it possible to resize the simulation shown in the browser i.e. make it not full-screen? I can't seem to do it by adjusting the width/height in the iframe. Would this be done Java side before compiling?

Sincerely,
Mannan

**Comment by sharpie7** [comment]
If the simulation is contained in an iframe it should adjust to the size of the iframe unless the iframe is too small. For example:
<iframe src="circuitjs.html" width="816" height="640">

From http://lushprojects.com/circuitjs/

The page circuitjs.html will always fill any iframe that contains it, but the iframe doesn't have to be full screen.

**Comment by mannanj** [comment]
Beautiful. I got it to work by having an iframe link to the circuitjs.html
```
<iframe src="/home/samsung/Documents/Projects_Active/omf/omf/static/war/circuitjs.html" height="640" width="816"> 
```
Thanks so much!

**Comment by sharpie7** [comment]
Great. I think that closes this issue!
