### ISSUE TITLE
Connector support?

### ISSUE THREAD

**Issue by JamesCoyle** [sharpie7/circuitjs1#30]
I'd personally find it useful to have support for connectors. These would act like multiple switches that all toggle on and off at the same time. It could be a simple thick-ish line that crosses over the wires that when clicked on splits into two thinner parallel lines to show it is disconnected.

![image](https://cloud.githubusercontent.com/assets/10384436/20075196/24729700-a52b-11e6-97ec-c9791d80260e.png)

As a bonus it would be awesome if it was possible to simulate the connections being shorted together (as is the case with 3.5mm audio connectors) or wires disconnecting at slightly different times (as can happen with many of the long multi-pin connectors).

**Comment by sharpie7** [comment]
It's not obvious unless you know it, but SPDT switches can be assigned groups which gang them together so that they switch simultaneously. This could be used to simulate the electrical behaviours that you want, though not as pretty as your solution.

**Comment by limitedAtonement** [comment]
This can probably be closed as it's almost four years old. @JamesCoyle Please feel free to create a PR with your cool-looking multi-pole switch!

**Comment by pfalstad** [comment]
I think SPDT switches are the way to go here.
