### ISSUE TITLE
Add and Use Githubs issue labels

### ISSUE THREAD

**Issue by E3V3A** [sharpie7/circuitjs1#308]
It doesn't make sense to spam the issue titles with things like: `Feature`, `Bug`, etc, when github has a great issue labeling functions already built-in. 

I've found that this is very useful, even for projects with small number of issues, and an absolute essential for project like this, with hundreds of open issues. It keeps it very easy to sort, delegate and maintain. It also help flagging issues as developer issues (for those who already know all about the project) and Q/A style issues that can be easily solved or answered in an FAQ wiki (for example). It also allow you to track Todo lists and so on. 

I suggest at least adding the following issue labels (here shown in todo list style):

- [ ] `Bug` - This is a bug
- [ ] `Feature Request` - ask for new features
- [ ] `internal/development` - issue is part of internal developer discussions
- [ ] `investigating` -currently investigating the issue
- [ ] `info`
- [ ] `FAQ`
- [ ] `ToDo`
- [ ] `Will Not Fix` - will not or cannot fix
- [ ] `Duplicate`
- [ ] `Invalid` 
- [ ] `Need More Info` - Need more info to address issue
- [ ] `Documentation` - Useful documentation for the project
- [ ] `References` - Useful external references for the project (sci literature, papers etc.)
- [ ] `Awaiting Response` - waiting for response from OP

---

It will then look like this: 

![firefox_2019-02-27_12-24-17](https://user-images.githubusercontent.com/194392/53483693-f527f080-3a79-11e9-8c64-d7a161709685.png)

**Comment by sharpie7** [comment]
Overkill much!

I am not planning on making my hobby in to an exercise in issue management. 

In general, my opinion is that the choice of tooling and how tools are used entirely belongs to those who are committed to the project. I use this definition of committed: ""The difference between involvement and commitment is like ham and eggs. The chicken is involved; the pig is committed."
