### ISSUE TITLE
Download for Offline Use?

### ISSUE THREAD

**Issue by ctstannard** [sharpie7/circuitjs1#31]
Hello,

First off I want to say that I love this circuit simulator. It has served me very well during my time as a student. Keep up the great work!

Second, I know it was originally possible to download a version of the Circuit Simulator that could be used "offline". Is that still possible? I often find myself in situations where I may or may not have a reliable internet connection and I would love to be able to use your wonderful program in those cases.

Thanks again!

**Comment by sharpie7** [comment]
The bottom of Paul's page contains a link to the Java version when can be run offline. http://www.falstad.com/circuit/ 

As far as I know there is no convenient technical option to allow the Javascript version to run offline.
