### ISSUE TITLE
Analog SPDT not flipping on click

### ISSUE THREAD

**Issue by E3V3A** [sharpie7/circuitjs1#310]
Not sure what is the issue, but it seem that the Analog SPDT switch doesn't work as expected, in the circuit `R-2R Ladder DAC`. Clicking on the switch does nothing. 

Or did I miss something?

**Comment by pfalstad** [comment]
Those switches are controlled by the logic inputs below them.  Click on those instead.

**Comment by E3V3A** [comment]
:man_facepalming: 
:+1:
