### ISSUE TITLE
Improvement: Add sensible component default values for sliders

### ISSUE THREAD

**Issue by E3V3A** [sharpie7/circuitjs1#312]
As an improvement to prevent unexpected and nonsensical results when adding a slider to components, I suggest to add the components default values (as found under the components `Edit` menu), also to the default slider range. 

In this respect I think the following [function](https://github.com/sharpie7/circuitjs1/blob/master/src/com/lushprojects/circuitjs1/client/Adjustable.java#L19-L24) need to be modified to also accept (or take) other default values. 
```java
    Adjustable(CircuitElm ce, int item) {
	minValue = 1;
	maxValue = 1000;
	elm = ce;
	editItem = item;
}
```

Such an implementation would partially address issues such as:
* issue #301 
* issue #243

**Comment by pfalstad** [comment]
fixed
