### ISSUE TITLE
Feature: Show power-frequency spectrum

### ISSUE THREAD

**Issue by E3V3A** [sharpie7/circuitjs1#313]
I came across [this](http://www.falstad.com/circuit/e-notch.html) older circuitjs version, of the `notch-filter` and found this very nice power-spectrum:
 
![image](https://user-images.githubusercontent.com/194392/53908055-70733e80-4046-11e9-964d-5bbe08a1e8a2.png)

How can this scope presentation be done in current version?

**Comment by pfalstad** [comment]
It's not an older version, it's a separate applet.  Go here and import your circuit:

http://www.falstad.com/afilter/

It's a separate applet because it doesn't support as many elements, the UI is different, and the simulation approach is completely different.

**Comment by E3V3A** [comment]
Aha, I see. That is a very cool applet.
Would have been very nice to be able to see that type of plot, also in circuitjs. 
Is there any way that the plot engine could be beaten into something like that?

> he simulation approach is completely different

What approach is that?
