### ISSUE TITLE
Automatic conversion to Maven or Gradle builds

### ISSUE THREAD

**Issue by E3V3A** [sharpie7/circuitjs1#315]
Hi Guys!

Much thanks to @briangordon 's closed PR #303...

I have made a Bash script and gradle build script, that will automatically convert your Eclipse based source paths into a Maven or Gradle based build environment. I still need to do some tests before I hand it over, but you can expect this shortly. So I will provide:

1. a Bash path conversion script
2. an updated and corrected `pom.xml` (for **Maven** builds)
3. a working **`build.gradle`** script that will build entire site (for **Gradle** builds)

Let me know if you're interested. 

You can also follow my development here:
* https://github.com/E3V3A/circuitjs1

Where all procedures have been documented.

**Comment by E3V3A** [comment]
Done!

If you already have Maven or Gradle installed, you can now build your site with 2-3 lines:
```bash
./ecl2mvn.sh
# mvn install
gradle compileGwt
gradle makeSite
```

:tada:  :balloon:  :+1:

**Comment by pfalstad** [comment]
Thanks!  I incorporated your build.gradle into my repository (finally).
