### ISSUE TITLE
Add register

### ISSUE THREAD

**Issue by gjwehnes** [sharpie7/circuitjs1#318]
Eight bit. Would be very useful when I am demonstrating various aspects of a Von Neuman architecture (data bus, CPU)

**Comment by pfalstad** [comment]
Is there a particular device you have in mind?  Could you post a link to the datasheet?

**Comment by sharpie7** [comment]
There is a 4 bit latch already - is an 8 bit version of that what you are thinking of?

**Comment by pfalstad** [comment]
latches have adjustable number of bits now
