### ISSUE TITLE
Relay bug

### ISSUE THREAD

**Issue by staviq** [sharpie7/circuitjs1#322]
Relay is bugged:

https://i.imgur.com/tkIjHgo.png

How is there 1V?

$ 1 0.000005 10.20027730826997 50 5 50
178 640 208 736 208 0 1 0.2 -3.3040237212843386e-17 0.05 1000000 0.02 20
w 640 208 640 160 0
w 640 160 736 160 0
w 736 160 736 192 0
R 640 240 576 240 0 0 40 12 0 0 0.5
s 640 256 640 320 0 1 false
g 640 320 576 320 0
w 736 224 880 224 0
w 736 192 880 192 0
R 880 160 800 160 0 0 40 12 0 0 0.5
g 880 256 800 256 0
w 880 160 880 192 0
r 880 224 1040 240 0 100000
r 880 256 1040 240 0 100000
g 1104 240 1104 272 0
p 1040 240 1104 240 1 0

**Comment by pfalstad** [comment]
When simulating relays, we don't actually simulate them as switches that are either on or off.  Instead an "off" relay circuit is simulated as a large resistor (1M by default, but you can change this in the edit dialog).  If we simulate it as an open circuit, then we may run into singular matrix problems.  1M is probably too small of a default, but you can make it as large as you need if this is an issue.
