### ISSUE TITLE
[Feature Request] E24 series resistors values

### ISSUE THREAD

**Issue by bjtftw** [sharpie7/circuitjs1#323]
It would be great to have resistors values from e24 series (10, 11, 12, 13, 15, 16, 18, 20, 22, 24, 27, 30, 33, 36, 39, 43, 47, 51, 56, 62, 68, 75, 82, 91) with scrolling method for changing this.

**Comment by sharpie7** [comment]
I added the scrolling behaviour to select common resistor values quickly and easily. IMHO the E24 series is less-helpful than the existing set because it adds a lot of new values which are not widely used.
