### ISSUE TITLE
Speed of simulator

### ISSUE THREAD

**Issue by nbbm26** [sharpie7/circuitjs1#326]
When running a simple Prime Number detector with CMOS NAND gates something like 16 NAND gates, would run, zoom and scroll very slowly.

Also, not present in code in repo now, but had a master with </module> chopped out of circuitjs1.gwt.xml and not sure how

**Comment by pfalstad** [comment]
Could you post the circuit?  Use either File->Export as Link or Export as Text.  Thanks.

Don't understand your second sentence?

**Comment by sharpie7** [comment]
Closed as example not provided.
