### ISSUE TITLE
Handling of Three-phase phenomenon

### ISSUE THREAD

**Issue by StrogoffM** [sharpie7/circuitjs1#336]
For example if I draw a delta circuit of sources with the usual phase offsets it gives me an error note.
For example if I draw a voltmeter between two AC sources (with 2 poles, one poles connected) and set the offset it does not show properly the line voltage.

**Comment by pfalstad** [comment]
Hi, could you post example circuits created with either File->Export as Text or File->Export As Link?  thanks

**Comment by pfalstad** [comment]
Need more information.
