### ISSUE TITLE
bug Open, Import, text or link, if text component with special char

### ISSUE THREAD

**Issue by Elias1958** [sharpie7/circuitjs1#343]
Circuit Simulator version 2.2.6js (pfalstad).
--

If you have 1 or more special char like Ω or ã etc.. in a **text element** each time you open or  Import a Circuit it will truncate a few chars of the last line, more especial chars more it will truncate, if the last line é some electronic part it will eliminate that part.

In the example below, it will truncate the **890**
The circuit is only a text  with **Test 1kΩ 2kΩ 1234567890**

**Import By text**
$ 1 0.000005 10.20027730826997 50 5 50
x 512 291 797 294 4 24 Test\s1kΩ\s2kΩ\s1234567890

**Or With a Link**
[http://www.falstad.com/circuit/circuitjs.html?cct=$+1+0.000005+10.20027730826997+50+5+50%0Ax+512+291+797+294+4+24+Test%5Cs1k%E2%84%A6%5Cs2k%E2%84%A6%5Cs1234567890%0A](url)

**Comment by pfalstad** [comment]
Fixed
