### ISSUE TITLE
Transmission line with zero impedance results in endless freeze

### ISSUE THREAD

**Issue by flarn2006** [sharpie7/circuitjs1#346]
If you place a transmission line and set the impedance to zero, it will hang endlessly. In case you're wondering, I was trying to simulate how a superconductor can sustain a current without a power source, which doesn't appear to be possible with regular wires (despite being simulated with zero resistance) because for some reason it doesn't allow wire loops.

**Comment by pfalstad** [comment]
fixed, it doesn't hang anymore.
