### ISSUE TITLE
Bug - junctions won't be printed

### ISSUE THREAD

**Issue by kamarado** [sharpie7/circuitjs1#347]
Problem: junctions look the same way as crossing wires do when printed.

Example: the pictures below show a schematic in "editor mode" (left) and in "print mode" (right).

![cs_editor](https://user-images.githubusercontent.com/3162751/60430780-d04db080-9c06-11e9-9426-02c83b72ea18.png) ![cs_print](https://user-images.githubusercontent.com/3162751/60429007-cc1f9400-9c02-11e9-839e-a470411c8140.png)

Proposal: mark junctions with circles in "print mode".

Edit: exporting a schematic as image shows the same behavior.

**Comment by sharpie7** [comment]
Thanks. Fix has been merged
