### ISSUE TITLE
BAD Connexion

### ISSUE THREAD

**Issue by caracole** [sharpie7/circuitjs1#352]
When there is a bad connection, it is almost impossible to identify the wrong connection.
How to solve this problem ?
Tanks

**Comment by pfalstad** [comment]
It's highlighted in red.  Aren't you seeing that?  Could you post an example circuit?

**Comment by caracole** [comment]
As I start with this wonderful tool, I did not know!
Indeed, the extremities of the connection are in red! Perfect
Thank you

Le lun. 8 juil. 2019 à 21:02, Paul Falstad <notifications@github.com> a
écrit :
