### ISSUE TITLE
Can't exit LED model customization

### ISSUE THREAD

**Issue by altimumdelta** [sharpie7/circuitjs1#354]
Clicking on "Custom" in the bottom of the drop down menu of the Model for LED Diodes, after it says that customization is not possible, I found no obvious way to return to the dropdown menu as it doesn't exist anymore, but the rename box appears and stays.

**Comment by sharpie7** [comment]
I think this is a bug in the user interface, but if you type a new name in the "Model name" box and click "Edit Model" it will work.
