### ISSUE TITLE
No description for custom transformer

### ISSUE THREAD

**Issue by recovarie** [sharpie7/circuitjs1#359]
Could someone explain what the numbers under "description" correspond to? When I click on description it takes me to a 404 page.
<img width="313" alt="Screen Shot 2019-07-11 at 10 41 21 AM" src="https://user-images.githubusercontent.com/52792013/61060741-076f4f00-a3c9-11e9-9c40-abef3baaaa6b.png">

**Comment by pfalstad** [comment]
The word description is a link..  click on it.

**Comment by recovarie** [comment]
Hi!

I tried doing that, but I keep getting this error message attached below:

>

**Comment by pfalstad** [comment]
sorry, I hadn't seen your email.  try it now.

**Comment by recovarie** [comment]
Thank you Mr. Falstad!
