### ISSUE TITLE
Bug: Glitching simulation on the path when severing connection with LEDs

### ISSUE THREAD

**Issue by ghost** [sharpie7/circuitjs1#361]
So I managed to isolate this glitch, when the connection is severed my moving a LED then all the A/V labels on wires will start glitching some ridicolous low or high number/unit very fast as if the sim still half-thinks it is connected, might also be a source of the lag.

But when moving an actual **Wire** or other items out of the way to disconnect a circuit, it more properly disconnects and doesn't produce a glitch.

EDIT: I see now it happens only if there's one or more LEDs in front that are still connected to the positive lead, might actually be something normal, but if it is a source of lag and an eyesore it may be pointless to simulate it (or show it).

Also so far I only tested this using DC and Voltage Source.

**Comment by pfalstad** [comment]
Could you send a sample circuit using File->Export As Link?

**Comment by altimumdelta** [comment]
Sorry it may take a bit for me to recall that and find the saved example if I did it with this at all, I might have to recreate it if I can't find it in my archives, it's been some time.

**Comment by pfalstad** [comment]
I should have asked you sooner..  Your message must have slipped through the cracks.
