### ISSUE TITLE
Feature Request: Add options to export oscilloscope data

### ISSUE THREAD

**Issue by Fellypao** [sharpie7/circuitjs1#363]
First of all, congratulations for this very useful tool!

On missing feature that I think to be important is the ability to export the oscilloscope waveforms/data. Is it possible to add this?

Best regards

**Comment by pfalstad** [comment]
Under "Outputs and Labels" there is a data export element you can attach to any node to collect voltage data and export it.

**Comment by Fellypao** [comment]
OK. Thanks for the tip. And sorry for the noise.
I'll close the issue.
