### ISSUE TITLE
[Feature Request]: LED Color Value

### ISSUE THREAD

**Issue by Geocube101** [sharpie7/circuitjs1#370]
Add capabilities for LED's to use RGB and Hex color values

**Comment by pfalstad** [comment]
You can already do this..  right click and edit any LED

**Comment by Geocube101** [comment]
True, but there is only a boolean value for each value. I had meant a using values from 0 to 255

**Comment by pfalstad** [comment]
You can use fractional values, like 0.5

**Comment by Geocube101** [comment]
Thanks
