### ISSUE TITLE
[Feature Request]: Op-Amp Gain Pins

### ISSUE THREAD

**Issue by Geocube101** [sharpie7/circuitjs1#371]
Add option to connect gain and ground pins to Op-Amp

**Comment by pfalstad** [comment]
Use “Add op-amp (real)” to get an op amp with a ground pin.  Don’t know any opamps with a gain pin, could you give an example?

**Comment by Geocube101** [comment]
The "real" one is ok, the gain pin was the pin to control the op-amps output voltage

**Comment by sharpie7** [comment]
I think we have cover this then!
