### ISSUE TITLE
Bug: Transformer shows extra big voltages when 1 of its coils is disconnected (Trapezoidal mode)

### ISSUE THREAD

**Issue by dr-vij** [sharpie7/circuitjs1#378]
Hello, I've found a situation, When you take a transformer, connect it to source, and then disconnect it from source - it starts showing extra big boltages with different sign at each step. I see this bug for trapezoidal method. When back euler - everything is ok.
![Ok](https://user-images.githubusercontent.com/20922312/63833111-e19f0900-c97a-11e9-8572-3055b20fc6eb.PNG)
![NotOk](https://user-images.githubusercontent.com/20922312/63833118-e499f980-c97a-11e9-8cb9-1dcb8016debf.PNG)

**Comment by pfalstad** [comment]
Yes..  use backward Euler for transformers in combination with switches or sudden changes in current, to avoid this problem.

**Comment by SgtSchultz71** [comment]
Isn't that just the voltage spike associated with inductors when they lose voltage and the field collapses backwards?

**Comment by pfalstad** [comment]
No, since this is an ideal switch, it should stop the flow of current immediately.  If it were a non-ideal switch, there would be some capacitance across it and there would be kickback, but it wouldn't last forever like this does.

**Comment by dr-vij** [comment]
Thank you, now I understand
