### ISSUE TITLE
Assumed grounds not shown?

### ISSUE THREAD

**Issue by terminator356** [sharpie7/circuitjs1#380]
Hello. I noticed that for example in all of the transformer examples,
 the bottom wires seem to be assumed at ground but there is no ground shown.
It seems to me that alternating voltage should be shown on the bottom wires
 of the transformer primary, and most certainly the secondary.
A student might get the wrong impression here.
Am I missing something? Thanks.
![circuit_sim_1](https://user-images.githubusercontent.com/5422362/64640019-1aa59780-d3d7-11e9-8f37-519466990067.jpg)

**Comment by pfalstad** [comment]
yes, that makes sense.  we should add grounds to these.

**Comment by terminator356** [comment]
Hm, I noticed that the same thing happens with a blank canvas and simple AC source.
It seems that both wires should have alternating voltage.
Or else show the assumed ground on the lower wire.
Perhaps it is a simple error in the code, that this two-terminal AC source thinks
that it is a one-terminal source, which is supposed have an assumed ground.
![circuit_sim_2](https://user-images.githubusercontent.com/5422362/64643585-ac64d300-d3de-11e9-8114-c66c44df628a.jpg)

**Comment by pfalstad** [comment]
If there is no ground, the simulator picks a node to be ground.  You should add a ground if you don't like the simulator's choice.  I don't see a need for the simulator to show the assumed ground in user-created circuits.

If you want a split supply, use two AC sources: http://tinyurl.com/y5qfktdp

**Comment by terminator356** [comment]
Understood. Thanks.

**Comment by pfalstad** [comment]
Added grounds to transformer examples.
