### ISSUE TITLE
add the Foutan Board to the list of circuit?

### ISSUE THREAD

**Issue by lookang** [sharpie7/circuitjs1#382]
i hope you can add Foutan Board 
https://xraise.classe.cornell.edu/perch/resources/foutanboard.pdf
to the list of existing circuits please.
i was trying to make my own but it is too difficult
https://iwant2study.org/ospsg/index.php/interactive-resources/physics/01-measurements/2-uncategorised/898-foutanboard

Thanks!

**Comment by lookang** [comment]
Dear Paul, i really like your simulator, it is super.
I have another request 
I need the bulbs to show different arrows length starting from the bulbs centre as an indication of the  brightness from the bulbs.
i am using 15V for the DC supply so the bulbs voltage can be ranging from
15V for series one bulb setup
7.5 V for 2 series
5 V for 3 series 
3.75V for 4 series.
for example.
can you add the lights rays coming out from the bulb like the ones from PHET?
[https://en.wikipedia.org/wiki/File:PhETCCKScreenshot.pdf](https://en.wikipedia.org/wiki/File:PhETCCKScreenshot.pdf)
maybe just a circular fan of rays
0,30,60,60,90,120,150,180,210,240,270,300,330 degrees.

Thank for your super simulator.

**Comment by pfalstad** [comment]
Hmm..  I'm not so wild about adding those light rays.

**Comment by lookang** [comment]
Dear Paul,
The light ray's aims to allow students to visualize easily the effects of
the voltages across the bulbs.
The learning outcomes is such that it would be directly visible from your
simulator, rather than telling the students
