### ISSUE TITLE
Feature Request: negative resistor

### ISSUE THREAD

**Issue by KelenLukie** [sharpie7/circuitjs1#383]
Hi there. Would it be possible to add in negative resistance and negative resistor themselves? This is important as negative resistor is the actual memtistor proposed by Dr Chua a long time ago. The current memristor is a false one. The real property of memristor isn't "remember the current that flows through it." Instead, it is "maintains the current that is flowing through it." When you have Coulomb-Weber relationship, the most suitable one would be a negative resistor as the gradient is naturally negative rather than non-linear interaction. A negative resistor would be the true memristor in all possible way. Yes, thermodynamics is broken as thermodynamics itself is fake anyway.

By the way, is it possible to add 2 more things? Add an electrostatic field to the secondary coil of any electrical transformer. This way, the internal resistance would be positive or negative or naturally positive depends on the electrostatic field. Under the influence of positive electrostatic field, the coil behaves like an electron barrier. Hence, forcing electrons to flow positive to negative, generating natural negative power. While there is material such as mica that serves as a natural electron barrier source when induced dielectro-electromagnetically, it is rarely to almost not used as a secondary coil to generate negative power waveform where current and voltage are 180 out of phase. Hence, material change for mica would be meaningless.

Thank you :)

**Comment by pfalstad** [comment]
Negative resistor: https://tinyurl.com/y2w9ngb7
