### ISSUE TITLE
P-FET Power does not account for body diode current 

### ISSUE THREAD

**Issue by phatpaul** [sharpie7/circuitjs1#389]
P-FET Power does not account for body diode current.
Please see the example circuit:

http://www.falstad.com/circuit/circuitjs.html?cct=$+13+0.000005+10.20027730826997+50+5+43%0Av+-16+112+-16+32+0+0+40+5+0+0+0.5%0Ar+176+32+176+144+0+10%0Af+80+80+80+32+33+1.5+0.02%0Aw+-16+32+64+32+1%0Aw+128+32+176+32+0%0Aw+176+144+80+144+0%0As+80+96+80+128+0+1+false%0Ar+128+32+128+80+0+1000%0Aw+96+32+128+32+0%0Aw+80+80+128+80+0%0Aw+80+80+80+96+0%0Aw+80+128+80+144+0%0Aw+80+144+-16+144+0%0Aw+-16+144+-16+112+0%0Ap+64+0+96+0+1+0%0Aw+64+0+64+32+0%0Aw+96+0+96+32+0%0A

If the switch is open, the P-FET should be conducting all current through its body diode.  
Vsd = -0.761V and current = 424mA
So the power dissipation of the mosfet should be 0.761V * 0.424A = 0.323W

But the simulator is showing P=5.8nW (that's nanoWatts!)

**Comment by sharpie7** [comment]
I believe fixed now
