### ISSUE TITLE
Feature Request: volume on the Audio Output

### ISSUE THREAD

**Issue by tetoskare** [sharpie7/circuitjs1#390]
Hi,
I think it's good that the volume of the created file for the Audio Output is maximized, that way any signal is audible, but on listening to full-on square waves, I feel like I'm going to blow my speakers!
I know, most people have an easy reachable knob for their output volume, but I don't and I guess I'm not the only one. Plus, I have always found this simulator output to be very loud compared to what usually comes out of a computer. Comparable to creating a maximized pure waveform in an audio editor: way too loud! I guess some people using headphones may have gotten shocked already...
So I was thinking a volume slider next to the "Play Audio" button, set to 50% by default, might be a good idea.
If too complicated, maybe automatically setting the output of the file to 50% (-6dB) after maximizing would be more reasonable. And 25% (-12dB), much safer.
-12dBFS of continuous tone is already pretty loud!

Also the way the file starts and finishes randomly at non zero-crossing moments, create loud clicks that can damage tweeters.
Fade In/Fade Out can sort this out, but triggering the sampling at zero crossing can be good too. Don't know which one of the two is easier.

I hope this can be considered one general issue about the audio output, let me know if it has to be split up in two (output volume / avoiding on-off clicks).

That's my only complain, otherwise I find this simulator pretty fantastic,
I've learned a lot with it in the last couple years, and improved my electronics
by a great step. So thanks a lot!

**Comment by pfalstad** [comment]
didn't add a volume slider but I reduced the volume and fixed the click thing.
