### ISSUE TITLE
New component - coupled inductors with center tap.

### ISSUE THREAD

**Issue by andyp60** [sharpie7/circuitjs1#392]
I've been trying to model a AC to DC power supply that uses a coupled inductor with a center tap. sample diagram included.  What would it take to add this component.
![coupled inductor](https://user-images.githubusercontent.com/11356689/68323948-aa885a80-0083-11ea-900f-a998f49a1415.png)

**Comment by pfalstad** [comment]
Use a tapped transformer with nothing connected to the secondary, or a custom transformer with the description set to "1,1".
