### ISSUE TITLE
Plotting graph with certain variables

### ISSUE THREAD

**Issue by SM-Fahim** [sharpie7/circuitjs1#395]
After completing the circuit, there a option for plotting, but only for V/I vs time or V vs I. But there's options for seeing rms value, pick value, frequency and others. Is there any option that I can plot a graph of Voltage vs frequency? I'm actually in need of this option.

**Comment by sharpie7** [comment]
TBH, I think Spice is much more suitable for your requirements than this simulator. Our focus is for real-time visulisation of circuit operation. Analysis of circuit behaviour based on changing parameters is exactly what Spice is intended to provide.
