### ISSUE TITLE
voltage source/wire with no resistance!

### ISSUE THREAD

**Issue by SM-Fahim** [sharpie7/circuitjs1#397]
I build this circuit just according to the book (Fundamentals of Electronics by Alexander), but when simulating, it's showing error. Here's the text to my circuit. Please tell me what I need to solve here.

$ 1 0.000005 10.20027730826997 50 5 43
v -16 112 -112 256 0 1 50 170 0 2.0943951023931953 0.5
v -112 256 64 256 0 1 50 170 0 -2.0943951023931953 0.5
l -16 112 352 112 0 0.0954 0
r 352 112 352 192 0 21
l 64 256 272 256 0 0.0954 0
r 272 256 352 192 0 21
w -112 256 -112 304 0
l -112 304 416 304 0 0.0954 0
r 352 192 416 256 0 21
w 416 256 416 304 0
v 64 256 -16 112 0 1 50 170 0 0 0.5

**Comment by pfalstad** [comment]
You need to add a small resistor (maybe 1m) inline with one of the voltage sources.  The simulator can't handle voltage sources in a loop like that.
