### ISSUE TITLE
Polar form of a current or voltage value

### ISSUE THREAD

**Issue by SM-Fahim** [sharpie7/circuitjs1#398]
I need to find the current through a wire. But as of AC voltage supply, the current keeps varying, which I can't write down to my reports. I need a polar form of the voltage and current values that can show me the pic value and the angle, just like we give input to the AC voltage source. Is their any direct or indirect way for this?

**Comment by pfalstad** [comment]
There's no way to get the angle unfortunately.  To get the peak value of current, right click on the wire and select "View in Scope", then right click on the Scope and select "Properties..." then uncheck Show Voltage.  Then it should show the peak value of the current in the scope, assuming "Show Peak Value" is checked (which it is by default).  If you want the RMS value check "Show RMS Average".
