### ISSUE TITLE
Miscellaneous question/feature request

### ISSUE THREAD

**Issue by mannanj** [sharpie7/circuitjs1#4]
Hi thanks so much for helping in the other iFrame issue here: https://github.com/sharpie7/circuitjs1/issues/3. 

I want to be able to add a button on to my html page which effectively goes to and takes the link from "File" -> "Export as Link" and saves it to memory. I load the circuit in an iFrame method (described in the issue above):
```
<iframe src="{{pathPrefix}}/static/circuitjs/circuitjs.html" style="position: fixed; height:87%; width:100%; margin-top:-2.5%; border: none"></iframe>

``` 

I can then load the circuit right back if you left the page, without having to manually go to File and import it back. 

The difficult solution appears to be modify the original Java before it is compiled in Eclipse with GWT, I have no Java experience. Would you know of any way to do grab the URL through javascript or even HTML or have done before?

Mannan

**Comment by sharpie7** [comment]
No I don't think this is possible without modifying the Java application. The link from the "export as link" command is dynamically created by the Java when the user requests it.

**Comment by mannanj** [comment]
Aha yea I figured. Thank you for the help. This can be closed.
