### ISSUE TITLE
How to get grpah lika on teh picture? (friom sample  comb filter)

### ISSUE THREAD

**Issue by programistawpf** [sharpie7/circuitjs1#402]
How to get grpah lika on teh picture? (friom sample  comb filter)
![graph](https://user-images.githubusercontent.com/5564741/70265875-9bd4b680-179b-11ea-9720-3a4b04bf6a7d.png)

**Comment by pfalstad** [comment]
Right mouse on scope, properties, show spectrum, uncheck show Voltage and show current if desired.
