### ISSUE TITLE
What happened to the simple frequency spectrum output?

### ISSUE THREAD

**Issue by jonmdev** [sharpie7/circuitjs1#407]
I notice the design seems to have suddenly changed. How do I get a simple static frequency spectrum output like this now?

https://i.stack.imgur.com/z6kqr.png

Is that still possible? If so what do I select to produce it?

Thanks

**Comment by pfalstad** [comment]
There's a separate simulator for that.   You need to export the circuit and import it into this one:

http://www.falstad.com/afilter/

**Comment by jonmdev** [comment]
Oh thanks. I didn't realize it was a separate link.
