### ISSUE TITLE
Bug - CMOS Inverter Subcircuit does not work

### ISSUE THREAD

**Issue by giulioscattolin** [sharpie7/circuitjs1#408]
Given a subcircuit of [CMOS_Inverter.txt](https://github.com/sharpie7/circuitjs1/files/4045357/CMOS_Inverter.txt), this is what happen when it is used:

![image](https://user-images.githubusercontent.com/17877150/72149914-8b1fed80-33a4-11ea-988f-f9cd46c6f5d6.png)

It makes no sense to me since `in`, `out` and `vee` are at `4.987 V` while they shouldn't be connected to anything, yet.  Moreover, `vee` it draws a very high current (~ GA) if grounded..

Is this a bug or am I missing something? Thank you very much!

**Comment by sharpie7** [comment]
Yes, I see the same problem with your example. Odd! @pfalstad is the expert on subcircuits

**Comment by pfalstad** [comment]
Sorry, this email got lost in my inbox.  Something definitely seems wrong here.  I'll take a look.

**Comment by pfalstad** [comment]
Yeah this is a bug in the MOSFET body diode code.  The body terminal wasn't getting set when using a MOSFET in a subcircuit, so it was using the gate as the body terminal  Uncheck "simulate body diode" to work around this for now, I'll fix.
