### ISSUE TITLE
Feature request: allow setting output voltage on flip-flops

### ISSUE THREAD

**Issue by KammutierSpule** [sharpie7/circuitjs1#409]
Tested on version 2.2.10js

**Comment by PlanMan1717** [comment]
I'm not a dev, but I can provide a workaround.

1. Have your flip-flop output to the noninverting (+) terminal of an ideal op-amp.
2. Then modify it to have the upper limit at 3.3V or wherever needed.
3. Ground the invering input (-).
4. Add a diode if needed to the output

**Comment by KammutierSpule** [comment]
nice idea! for testing.. but may add too complexity on large circuits
