### ISSUE TITLE
GWT module 'circuitjs1' may need to be (re)compiled

### ISSUE THREAD

**Issue by taffarel55** [sharpie7/circuitjs1#419]
Anybody?

**Comment by pfalstad** [comment]
What?  Are you seeing this message somewhere?  More details please!

**Comment by taffarel55** [comment]
I'm seeing this message after initial compilation. That's a js alert

![photo](https://user-images.githubusercontent.com/18634201/74873008-18a81300-533d-11ea-8efd-a6188eaceb2c.png)

**Comment by pfalstad** [comment]
Not sure, haven't seen that.  How are you running it?  To run it, I right click on the root node, "circuitjs1" in the package explorer on the left, then select "Run As" and "GWT Development Mode With Jetty".  Then when it asks what to open, I select circuitjs.html.  Then double-click to open the URL it displays.  It says "compiling" and then shortly after that, the applet starts.  Is any of that happening?

You could also try following the advice here: https://stackoverflow.com/questions/5719118/gwt-module-may-need-to-be-recompiled-redux

**Comment by taffarel55** [comment]
Thanks!
