### ISSUE TITLE
Linux version/windows version on Linux mint 19

### ISSUE THREAD

**Issue by gskrish2001** [sharpie7/circuitjs1#420]
Really love circuitjs1, I tried running windows stand-alone version in linuux under wine (POL) but it would not initiate at all. I am running linuxmint 19 and wine. Several other programs function well. I wonder if it has to do with java. I have not installed that on wine yet. If it can be tested and made functional, I think the linux community would love it. Web browser version works well.
Thank you.

**Comment by pfalstad** [comment]
Hi, see https://github.com/sharpie7/circuitjs1/issues/393

**Comment by pfalstad** [comment]
See tom2238's comment at the end.

**Comment by pfalstad** [comment]
There are offline linux versions now on the website.
