### ISSUE TITLE
Feature request/UI: Spectrum scaling

### ISSUE THREAD

**Issue by Felthry** [sharpie7/circuitjs1#422]
When I look at the spectrum of a signal in a scope, it has its zero point at the center of the scope, despite the fact that negative values here are not possible (since as far as I'm aware, it's showing only the magnitude of the frequency components), meaning that half the vertical range of the scope is essentially unused for spectrum information.

Now, it makes sense that you might want that if showing both the time-domain signal and the frequency-domain spectrum, but if you're only displaying the spectrum, it would make more sense to me to have an option to put the zero point of the scale near (perhaps not *at*) the bottom of the scope.

The spectrum display seems to be not exactly a priority feature, but it's one I'd like to see given more attention, as it is pretty useful.

**Comment by pfalstad** [comment]
Fixed
