### ISSUE TITLE
Inconsistent coloration for power sources

### ISSUE THREAD

**Issue by Felthry** [sharpie7/circuitjs1#426]
Below is a screenshot of a few circuits, with the "show power" option turned on.

![image](https://user-images.githubusercontent.com/6402030/77655374-51409b00-6f40-11ea-8576-cbdb6e8ba61a.png)

As shown here, although AC voltage sources and one-terminal DC sources get properly colored green when they're supplying power, noise sources and two-terminal DC voltage sources don't get colored at all, despite providing power, and current sources get colored red. In fact, current sources show positive power *consumed* when looked at in the scope, despite *providing* power!

Not shown here, but also found to have problems:
- the AC sweep source displays as red when providing power, and displays positive power consumed in the scope; same as the current source

Not shown here, but tested to work fine:
- antenna
- AM source
- FM source
- clock
- 1-terminal AC source
- Variable voltage
- audio input

**Comment by pfalstad** [comment]
Fixed
