### ISSUE TITLE
Export V/I 

### ISSUE THREAD

**Issue by mrquincle** [sharpie7/circuitjs1#427]
Hi, we're working on load identification using V/I trajectories. It's cool how you can visualize all the different ones. For example, consider this set of loads (it's from a paper, I'll be able to get it for you if you're interested in it).

![2-Figure1-1(2)](https://user-images.githubusercontent.com/1428585/77677382-86241080-6f87-11ea-9691-82f484cfa16e.png)

It is cool to try to create the different plots. The fun ones to try to create are the higher-order ones. Something like (e) but not exactly:

![ac_and_dc_and_l_vs_c](https://user-images.githubusercontent.com/1428585/77677059-13b33080-6f87-11ea-9c40-842ea834350a.png)

We're subsequently running classifiers on those VI trajectories. What would we need to do to extract the data from the (falstad) simulator, to do so? Can we obtain it through the browser's console somehow? 

Or even better. Is it a nice idea to have export functions for current/voltage data in the menu?

**Comment by mrquincle** [comment]
Ah, I found out I can export voltages via "Draw", "Outputs and Labels", "Add Data Export". I then can export voltage information, http://tinyurl.com/wawqn4v.

Can I export current data as well? Preferably synced. :-)

**Comment by pfalstad** [comment]
You just need to use a current controlled voltage source to convert the current to voltage:

http://tinyurl.com/u83gq83

**Comment by mrquincle** [comment]
Sweet!! That works splendidly! Let's see if I can bump the resolution on this thing.

![original_data txt](https://user-images.githubusercontent.com/1428585/77683827-4f56f600-6f99-11ea-8afa-71e461e3cc92.png)

**Comment by mrquincle** [comment]
Mmm... It is not possible to sync it somehow I guess?

**Comment by pfalstad** [comment]
Options->other options will let you set the time step size to a smaller value.

**Comment by pfalstad** [comment]
If you click reset first, then both data outputs will start from the same point...

**Comment by mrquincle** [comment]
It is fabulous!! Really great. http://tinyurl.com/vgfgs5f I set it at 1us and enlarged the buffer to around 100.000 data points. This is the result.

![original_data txt](https://user-images.githubusercontent.com/1428585/77687571-ea060380-6f9e-11ea-9230-64daacc27a1e.png)

Thank you so much!

**Comment by mrquincle** [comment]
Starting with black dots, to show time progression...

![original_data txt](https://user-images.githubusercontent.com/1428585/77690169-2cc9da80-6fa3-11ea-8d5f-7dde27921290.png)

Feel free to close this issue!

**Comment by mrquincle** [comment]
If you want to play with this yourself. Here's an R script: https://gist.github.com/mrquincle/e00ebd6034a4c565446c07480ab28af6

**Comment by mrquincle** [comment]
A very low-priority request would then be to perhaps allow also for an easier way to export voltage/current simultaneously (without adjusting the circuit, clicking restart, and right clicking different export labels, and hoping that you've synced data). I often downloaded either the same data, or not synced data, or made other dumb mistakes. :-)
