### ISSUE TITLE
Polarized Capacitor?

### ISSUE THREAD

**Issue by madcountess** [sharpie7/circuitjs1#428]
I'm trying to work on some analog circuits I am yet to be confident of, and a few of the circuits I've found that I want to test have polarized capacitors, like electrolytic capacitors, and I'm wondering how I can either polarize a nonpolar cap or something. I've searched through the directions page and I'm just kinda lost.

**Comment by madcountess** [comment]
Nevermind. I am using an apparently incomplete build. I'll have to take it up with the maintainer of the arch/manjaro package

**Comment by pfalstad** [comment]
Polarized capacitors are the same as regular capacitors, except that they stop the simulation and warn you if you have a negative voltage across them.  So you don't need them unless you're designing a circuit you want to build out of real components.
