### ISSUE TITLE
Custom transformer oddity

### ISSUE THREAD

**Issue by Felthry** [sharpie7/circuitjs1#430]
![image](https://user-images.githubusercontent.com/6402030/77822890-ce951880-70c4-11ea-936d-f037453d238c.png)

As this image shows, it's possible to put a slider to the "description" field of a custom transformer. Dragging this slider does nothing (good; I was expecting a crash), but it probably shouldn't be an option in the first place.

**Comment by pfalstad** [comment]
Fixed
