### ISSUE TITLE
Feature request/missing component: ternary logic input/output

### ISSUE THREAD

**Issue by Felthry** [sharpie7/circuitjs1#433]
Although the circuit gallery includes examples of ternary logic, there appears to be no way to actually insert ternary logic inputs and outputs into one's own circuits. Additionally, the ternary logic IO that exists in the examples can't be modified to change their high and low levels.

**Comment by pfalstad** [comment]
You can add ternary logic inputs now.  But you can't change the levels.

**Comment by pfalstad** [comment]
done
