### ISSUE TITLE
Feature Request: Variable capacitors/inductors

### ISSUE THREAD

**Issue by cprobertson1** [sharpie7/circuitjs1#44]
Variable capacitors and inductors would be incredibly useful for prototyping resonant circuits including VFOs, tuning circuits and transmatches, particularly amongst the ham radio crowd

**Comment by pfalstad** [comment]
you can create a variable anything since 2a2112d9670106a2fdecf54d61f1f2805c9e8583 .  Right click on a capacitor or inductor and pick "Sliders..."
