### ISSUE TITLE
Feature Request: LM317

### ISSUE THREAD

**Issue by Daktin** [sharpie7/circuitjs1#449]
I would like to request LM317 circuit simulation, I have already put all the known parts from representative Schematic Diagram in datasheet into applet, but it needs a bit of tweaking:

[lm317.circuitjs.txt](https://github.com/sharpie7/circuitjs1/files/4733923/lm317.circuitjs.txt)

Circuit in attachment is connected as constant current source.

**Comment by pfalstad** [comment]
See #434 where I converted this to a subcircuit.  I still may add this as a separate component.
