### ISSUE TITLE
About circle analysis

### ISSUE THREAD

**Issue by FilimonovMPEI** [sharpie7/circuitjs1#450]
Hello,
I'm a student that want to make a report to class about your programm. I'm understood how it's calculating curcuits (make matrixes like SPICE) but how this programm analyse count of nodes and it's connections?
Please explain to me how this occurs.

**Comment by pfalstad** [comment]
Sorry for the late response.  I suppose you've already made your report, but this is the book that explains how the simulator works: https://books.google.com/books/about/Electronic_Circuit_System_Simulation_Met.html?id=ipJKdvRE-wEC
