### ISSUE TITLE
Problem using subcircuit

### ISSUE THREAD

**Issue by bwest81** [sharpie7/circuitjs1#455]
I created a subcircuit without any issues but when I try to create an instance of it, nothing happens.  I know I am doing everything correctly because if I create a simple circuit and do the same, it works fine.  If I add an instance of another subcircuit and then try to switch it to my problem circuit, it doesnt work and I can no longer add anymore subcircuits.  Attached is the circuit in question

[circuit-20200627-2113.circuitjs.txt](https://github.com/sharpie7/circuitjs1/files/4841689/circuit-20200627-2113.circuitjs.txt)

Thank you

Edit:  
I think I found my issue.
I had multiple pins connected internally without any components between them.  Removing extra pins or adding a resistor or other component between them solved the issue.  I didnt realize it before but this is similar to the other issue involving subcircuits.

**Comment by pfalstad** [comment]
Yes, seems to be the same as #442.  I'll fix it to give an error instead.

**Comment by sharpie7** [comment]
Fixed
