### ISSUE TITLE
Triggered SCR voltage drop is too high

### ISSUE THREAD

**Issue by minecraft2048** [sharpie7/circuitjs1#456]
In the example circuit Silicon-Controlled Rectifiers > SCR, change the load resistor from 100 ohms to 1 ohm. Then, after enabling the lower switch and the SCR is triggered, Vac is 4.915 V at Ia = 84.723 mA. I think is is too high, as the common thyristor voltage drop according to google is about 1V up to rated current, and because of this, controlled bridge rectifier circuit doesn't work.

**Comment by pfalstad** [comment]
You can edit the part and change the gate cathode resistance to something that works better.

**Comment by minecraft2048** [comment]
Ahh that's the variable that I need to change
