### ISSUE TITLE
Ring Oscillators

### ISSUE THREAD

**Issue by Roger-Hlls** [sharpie7/circuitjs1#458]
Hi all!

   I built a ring oscillator by NAND 74xx00 gates, both TTL and CMOS material; i.e. a chain of 7, at least, 74LS00 or 7aHC00 NAND gates with short-circuited inputs, forwarded their outputs to the next gate in tow. The last NAND gate, also the output of the ring, feed-backed its output to the (short-circuited together) inputs of the first one. I supply the circuit for 'electron':

[e2_3_1_a.txt](https://github.com/sharpie7/circuitjs1/files/4872400/e2_3_1_a.txt)

However, in my Lab, by using real-world gate I obtained the results shown in files:

![F2_3_1a_1](https://user-images.githubusercontent.com/67359047/86509645-247b0a00-bdf2-11ea-96cc-113e6905e976.jpg)
![F2_3_1a_2](https://user-images.githubusercontent.com/67359047/86509647-2644cd80-bdf2-11ea-8f2d-10138b5d704c.jpg)
for the 'LS' chip and files:

![F2_3_1b_1](https://user-images.githubusercontent.com/67359047/86509659-39f03400-bdf2-11ea-8165-2f2fb4068689.jpg)
![F2_3_1b_2](https://user-images.githubusercontent.com/67359047/86509661-3b216100-bdf2-11ea-9d53-41051847ce65.jpg)
for the HC ones.

I used a Tektronix TDS 2002B oscilloscope; '1a_1' / '1b_1' files show 50.0nsec time divisions, whereas '1a_2' / '1b_2' ones 25.0nsec time divisions. So, is there any chance to obtain better results in 'electron'? Also, a not so 'thick' waveform?

   Thank you,

Roger-Hlls

**Comment by pfalstad** [comment]
The NAND gates in the simulator are ideal, responding instantly (in one time step) and with an infinite slew rate.  If you’re going to build a ring oscillator like this, the behavior will depend on the real response of whatever gate implementation you are using.  So you can’t use ideal gates to model it.  You’ll have to get the schematic for the NAND gates and use it to make a sub circuit and then use that to make the ring oscillator.

**Comment by Roger-Hlls** [comment]
Hi Paul,

 

                Yep, knew it, yet I guess I hoped for another solution... Also, you didn’t give me any insight on the ‘density’ of the plot and how to further ‘spread’ it to make it more clear... Thank you for your answer,

 

Roger-Hlls

**Comment by pfalstad** [comment]
You want to zoom in on the scope more so you can see the waveform better?  Unfortunately you've zoomed in as far as possible.  Normally I'd say that you need to make the timestep smaller, but this broken circuit will go as fast as the timestep will allow, since there's no capacitors or anything.  If you set the timestep small enough, it will produce gamma rays.

**Comment by Roger-Hlls** [comment]
Thanks, Paul, a very good, humorous, answer! You’ re a pal,

 

Roger-Hlls
