### ISSUE TITLE
Unable to add bar over labeled node

### ISSUE THREAD

**Issue by bwest81** [sharpie7/circuitjs1#471]
Unabled to add bars over labeled node names, cucircuits especially should have this ability.  How can I show that a node is active low?   And honestly, the logic inputs/outputs should be selectable as being included in the list of node used by subcircuits.  If this were possible we wouldnt need bars over the labeled node names.

**Comment by pfalstad** [comment]
Logic inputs/outputs don’t have names though, so we can’t use them as is..

**Comment by sharpie7** [comment]
Fixed
