### ISSUE TITLE
Feature request: Simple CPU/Microcontroller Part

### ISSUE THREAD

**Issue by walmis** [sharpie7/circuitjs1#48]
It would be fun to play with programmable circuits. I imagine a microcontroller that interprets javascript code on every simulation iteration. It could have some GPIO pins, AD/DA pins accessible with simple syntax to interface with the rest of the circuit.

**Comment by Harvie** [comment]
What a cool idea :-D
In fact this could turn out to be new api to write simple definitions of new parts :)

**Comment by Willt125** [comment]
I apologize for the necropost, but I feel this is important enough to warrant it. This would be an amazing new feature!

**Comment by sharpie7** [comment]
I also received by email this message: "can you add arduino simulation and arduino ide please"

**Comment by TimTheToaster** [comment]
So... this exists: https://stackblitz.com/edit/avr8js-6leds?file=index.ts
Would it be possible to integrate this into it?

**Comment by TimTheToaster** [comment]
I'm a programmer with Java and Javascript experience. I'd be willing to take a whack at it.

**Comment by pfalstad** [comment]
I've been resisting this for a while, but I'm starting to warm up to it.  We just need to copy it to my site (and Iain's).  Then we could open a new tab with the CPU simulator in it, and the two tabs could communicate using local storage.  And this wouldn't bloat the core simulator very much.

**Comment by pfalstad** [comment]
Like this: https://github.com/MarkMegarry/AVR8js-Falstad

except I would probably make an chip, rather than having you create individual pins.

**Comment by TimTheToaster** [comment]
@pfalstad oh wow! someone's already done it! haha. Ahh... the joys of open source.

Great work on this project, by the way. I just recently starting trying to create bare circuits and it has taught me a TON about EE. My EE friends can explain a concept to me and then I can go into the simulator and actually see it in action and play with the concept for hands-on learning. Thanks a ton to everyone who has worked on this.

**Comment by pfalstad** [comment]
I took Mark Megarry's work and brought it into the main simulator.  It uses the javascript interface now.

http://www.falstad.com/circuit/avr8js/

**Comment by Harvie** [comment]
Cool! I guess there is no debug output yet. Also i wonder if interrupts would work in this. Might be fun to try soft serial sketch or something. For example to simulate software uart communication looping back through simulated optocoupler.

**Comment by pfalstad** [comment]
You can do Serial.println("debug text");

Not sure about interrupts.

**Comment by narimaulea** [comment]
Hi Paul, your web is to me fantastic  !!
I use it with me students.
would be difFicult to implement interrupts to avr8js?
thanks
