### ISSUE TITLE
whats the problem?

### ISSUE THREAD

**Issue by aalencarvz1** [sharpie7/circuitjs1#480]
I don't understand why there was a short circuit if there is no contact between positive and negative
[circuit-20200807-1117.circuitjs.txt](https://github.com/sharpie7/circuitjs1/files/5041916/circuit-20200807-1117.circuitjs.txt)

**Comment by pfalstad** [comment]
It’s a wire loop...  not a short circuit.  You can’t have a loop without resistance, it makes the simulator confused.  Put a small resistor in there.
