### ISSUE TITLE
Generated Links

### ISSUE THREAD

**Issue by dvdff** [sharpie7/circuitjs1#481]
The new form of generated links does not include values - which means it is not possible to update values from outside the browser.

**Comment by pfalstad** [comment]
Could you describe in more detail what you are doing, that you need to modify values in the links?  I have some javascript code that generates circuit links but it uses old-style links, which still work.

**Comment by dvdff** [comment]
We generate circuit with unique values for students in the class that we teach. Previously with the Falstad links, the values were just a component in the url that we could modify with a code script, but this seems to not be possible with the new urls as these are all letters.

If you have some code to generate these links that would be much appreciated.
________________________________

**Comment by pfalstad** [comment]
Well, if your existing code is generating circuits using old style links, it will still work.

If you need to create new circuits that you can modify with a script, you can generate the old style links by doing File->Export As Text, then replacing all the spaces with "+" and URL encoding the rest (replacing newlines with %0A).

Or, you could get the compression library we are using: https://github.com/pieroxy/lz-string/  And then do File->Export As Text, and compress the result using compressToEncodedURIComponent.  Or take a new-style link, decompress it using decompressFromEncodedURIComponent, modify it and then compress it again.

**Comment by dvdff** [comment]
Thanks for your advice on this. We have been able to regenerate these links from the suggestions you provided above, by generating a link from the exported text.

Thanks again.
________________________________
