### ISSUE TITLE
Feature: A few dc-dc converter examples

### ISSUE THREAD

**Issue by Felthry** [sharpie7/circuitjs1#482]
I don't know enough about github or javascript to make this a pull request, but I've made a few example circuits that I think would be good to add to the circuits dropdown; basic buck and boost converters, a buck-boost converter, and a couple types of more advanced converters (just to show principals of operation).

I can't seem to get it to upload here (it just gives an error, for some reason), but here's a link to it on dropbox:
https://www.dropbox.com/s/47lj60wxf771vij/converters.zip?dl=0

**Comment by pfalstad** [comment]
Thank you, those look great, I'll add them.

**Comment by pfalstad** [comment]
Added, thanks!
