### ISSUE TITLE
Bug with inductance and capacitance sliders

### ISSUE THREAD

**Issue by kreynolds112358** [sharpie7/circuitjs1#487]
Sample Circuit: [http://tinyurl.com/y4j654es](http://tinyurl.com/y4j654es)
After reaching a steady state:
Changing the Capacitance slider has no effect on the voltage across the capacitor.
Changing the Inductance slider has no effect on the voltage across the inductor nor the current through the inductor. 

Capacitor example. After charging a 1Farad capacitor to 1Volt, there should be 1 Coulombs stored in the capacitor. If the same capacitor's capacitance was changed to .1F charged to 1 Coulomb, the voltage across the capacitor would jump to 10 Volts. The concept can be seen physically demonstrated here [https://www.youtube.com/watch?v=axgG_aSLKPM ](https://www.youtube.com/watch?v=axgG_aSLKPM )except on different scales.  

I am not sure what are the appropriate equations for the inductor scenario, but I would expect that changing the permitivity of the core of a coil (change its inductance) will have an effect on the current through the coil and or voltage across the coil.

**Comment by pfalstad** [comment]
This is true...  but I'm not inclined to fix this.  A capacitor with a slider is not really a variable capacitor.  The sliders are just a shortcut for editing the parameters using the edit dialog.  When changing a capacitor's capacitance, it's like you're swapping out one capacitor for another.

If I made it work like you want it to work, then if someone changed a capacitor in the default LRC circuit from 1uF to 1nF, then the voltage would be 1000 times higher!  That would be weird and confusing.  In a real circuit, with a real variable capacitor, the capacitance would change so slowly relative to what's going on in the circuit that you wouldn't see this enormous buildup of voltage.  This simulator is not aimed at simulating static electricity experiments like in the youtube video.  It's aimed at simulating real circuits.

For the inductor, it's even less clear what to do, and I think it would depend on the type of variable inductor.  I would probably need to experiment with a real one.
