### ISSUE TITLE
Firefox Memory consumption

### ISSUE THREAD

**Issue by jeanrenaud** [sharpie7/circuitjs1#490]
The circuitjs1 applet consumes a never-ending increasing memory space in Firefox 81.0b4 (64 bits). I reach like 3 GB in a couple of minutes, then everything starts to hang, i have to close and reopen the browser (after exporting circuit data before it is too late).

It happens even with the default circuit shown at page loading. Just reloading the page does not free the memory. A browser close and reopen is necessary.

Nothing special happens in the most recent version of MS Edge.  A steady 250 MB.

**Comment by pfalstad** [comment]
And it worked fine in earlier releases?  You should report this to the firefox people.

**Comment by jeanrenaud** [comment]
I can't remember about previous versions, i was using another browser before, and did not kept history about performance of the applet through time.  Thanks anyway.  Probably some kind of bad garbage collector.

**Comment by pfalstad** [comment]
I tried this with 81.0b4 on a mac and didn't notice any memory issues.  I will try on windows.

**Comment by sharpie7** [comment]
I use Firefox as my main browser adn there doesn't seem to be an issue currently.
