### ISSUE TITLE
Feature Request: Variable Resistor

### ISSUE THREAD

**Issue by okyloky9** [sharpie7/circuitjs1#491]
Possibly just a slider on the resistor we already have, where you can change from 0ohms - xohms real-time. I'm new to circuits and not sure how often these are used, but a project I was working on lists one and I couldn't find one on the site.

Thanks,
Oky

**Comment by pfalstad** [comment]
You can use a potentiometer, or right click on a resistor and select "Sliders"

**Comment by okyloky9** [comment]
Thanks, sorry about that lol.
