### ISSUE TITLE
DPDT switch component available?

### ISSUE THREAD

**Issue by cybericius** [sharpie7/circuitjs1#497]
Hi, I want to simulate a guitar circuit of capacitors, pots with dpdt switch (push-pull pot), jack output, and a 3-way switch (+wires).
Any idea if I can do it?
Thanks.

**Comment by pfalstad** [comment]
Yes, create two SPDT switches, edit them and change the "switch group" to a nonzero number, like 1.  Then they'll be linked as a DPDT switch.

**Comment by cybericius** [comment]
Thank you. I'll check it out.
