### ISSUE TITLE
3-way switch with grounding

### ISSUE THREAD

**Issue by cybericius** [sharpie7/circuitjs1#498]
Hi,
Looking for the above realization for a guitar circuit.

Positions:
1. Neck pickup selected
2. Both pickups selected
3. Bridge pickup selected

Thanks.

**Comment by pfalstad** [comment]
Add a SPDT switch, right click, Edit, set number of throws to 3.

**Comment by pfalstad** [comment]
Actually I don't think that will do what you want.  It sounds like you want a switch with a center position that has both loads connected.  The simulator doesn't have one of those..  You could make one with analog switches and logic.

**Comment by cybericius** [comment]
Yes, that's the plan. Thank you, I'll try to figure it out what to do with
it.

**Comment by pfalstad** [comment]
You can use a make-before-break switch to do this now.
