### ISSUE TITLE
Large circuits can't be transferred via link. 

### ISSUE THREAD

**Issue by JamesNewton** [sharpie7/circuitjs1#5]
That's obvious, actually, but the point is that there may be ways to work around that. The ability to load circuits from a file on the local server is great, but what if a user just wants to link their circuit to your site? You can earn the adsense revenue... what do I care? How about an embedding option to load a circuit from a URL? Or via some other means? Perhaps your server could accept and forward post data?

**Comment by sharpie7** [comment]
ShortURL support added and also Dropbox integration to address this use-case.
