### ISSUE TITLE
Apache Tomcat integration

### ISSUE THREAD

**Issue by lucasmellos** [sharpie7/circuitjs1#50]
Is possible make integration with apache tomcat? Example of integration with apache tomcat?

**Comment by sharpie7** [comment]
Tomcat is server-side Java platform. I do not plan to migrate any of this application to the server side.

This project compiles Java to JavaScript to run on the client-side. The fact that the application runs on the client is necessary to support the highly responsive and interactive nature of the program. It also efficiently distributes the calculation load of running the circuit simulation.
