### ISSUE TITLE
Standalone version UI bug

### ISSUE THREAD

**Issue by Gautzilla** [sharpie7/circuitjs1#503]
Hi, 

thanks for the awesome app, it's helping me a lot.

I have one issue concerning the standalone version: the UI windows (tools menu, right click...) has a black baground, making everything impossible to read. I have to select all (CTRL + A) text in order to see it (see the attached pictures).

Thanks,
Gauthier
![Circuitjs](https://user-images.githubusercontent.com/72027971/94442719-928e5d80-01a4-11eb-8087-d1bd255a34a4.png)

**Comment by pfalstad** [comment]
I'm not seeing this.  Is this windows?  what version?

**Comment by pfalstad** [comment]
Can't reproduce
