### ISSUE TITLE
Potentiometer full-travel values aren't max and zero

### ISSUE THREAD

**Issue by TimMathias** [sharpie7/circuitjs1#506]
For a potentiometer, the full-travel values are not maximum and zero. For example, a 1k pot gives 995:5 and 5:995.

Is this by design?

Consider changing it 0:1000 and 1000:0

**Comment by pfalstad** [comment]
I did that to make the implementation easier.  A device with zero resistance has to be handled completely differently than one with nonzero resistance.  I could change it to 999:1 or 9999.9999:.0001.
