### ISSUE TITLE
Standalone Windows Version Not closing

### ISSUE THREAD

**Issue by TonyTWoof56** [sharpie7/circuitjs1#511]
I and my class mates use this program a lot for our school work and we have found a major problem in the newest offline version. When trying to close the application it will not shut down. The only way to do so is going into task manager and forcing the program to close. Will their be a fix for this soon? 

I am not sure about the Linux and Mac version. This problem was only found on the Windows version and happened to all my classmates running the newest version.  

New Info: This only happens when running the program for a long period of time. We ran the program for almost 2 hours. If you open the program and immediately close it, it will close. 

Also thank you for this amazing tool!

**Comment by pfalstad** [comment]
I've seen this before.  It's going to be hard to fix, I'm afraid, because it seems to be a bug in Electron (the app we're using to do the standalone versions).

**Comment by TonyTWoof56** [comment]
Thank you for the info I'll be sure to keep that in mind and let my classmates know. I also just wanted to thank ya'll for still working on the program and making it better. My professor gets me to explain how to use the program to a lot of her classes and this new update definitely made saving files a lot easier and simpler to explain.

**Comment by Lance-at85** [comment]
Hi,
This is just for your information, I have just installed the Windows standalone version and I too am experiencing this problem.. I have to go into the Windows "Resource Monitor" and end the process to close the program..
Oh, by the way. Thank you very much for supplying the DIY community with this great program..

**Comment by SEVA77** [comment]
> I've seen this before. It's going to be hard to fix, I'm afraid, because it seems to be a bug in Electron (the app we're using to do the standalone versions).

I'm not sure but I have an assumption that the program gets stuck at the moment when a warning about unsaved files should appear. Try to remove the option to show this warning.

**Comment by pfalstad** [comment]
Wow nice work SEVA77!  I removed that warning and it seems to work.  I thought for sure it would be more complicated than that.

**Comment by SEVA77** [comment]
Cool!
