### ISSUE TITLE
[Feature Request] - Please add transistor, diode, OTA support for filter applet

### ISSUE THREAD

**Issue by MrPandoman** [sharpie7/circuitjs1#513]
Thank you

**Comment by sharpie7** [comment]
Sorry, I don't understand what is being asked for. Transistor, diodes and OTAs are all in the simulation already.

**Comment by pfalstad** [comment]
He means the filter applet, http://www.falstad.com/afilter/

It would be hard to add support for nonlinear devices to that applet.

**Comment by MrPandoman** [comment]
Hello, thanks for the reply,

Yes, these are in the Analog Circuit Simulation Applet, but not in the Analog Filter Applet. It would be great if they are available there as well.

Thank you,
Ando P.

On Nov 29, 2020, at 8:11 AM, Iain Sharp <notifications@github.com> wrote:

﻿

Sorry, I don't understand what is being asked for. Transistor, diodes and OTAs are all in the simulation already.

**Comment by sharpie7** [comment]
As this is the repo for the sim and not the filter aplet I am closing this issue, but i think Paul has noted it.
