### ISSUE TITLE
[Feature Request] Unijunction Transistor

### ISSUE THREAD

**Issue by thaliondrambor** [sharpie7/circuitjs1#516]
I really like the circuit simulation and use it very often.
I want to simulate a relaxation oscillator with an unijunction transistor (UJT). Unfortunately there isn't one available. Please, can you add a general UJT (trigger voltage, holding current).

Thanks in advance.

**Comment by pfalstad** [comment]
added UJT as a component and UJT oscillator as an example circuit.
