### ISSUE TITLE
embed the simulation in a PyQt / QML app?

### ISSUE THREAD

**Issue by eMPee584** [sharpie7/circuitjs1#518]
A PyQt app could be styled more flexible and could use system libraries instead of rotten electron..
Especially replacing the current menu with a responsive grouped tabbar would be mighty awesome :rainbow: ..
Libreoffice has a few nice toolbar layouts to zap through.. I really like the notebookbar setting and think this could boost usability quite a bit..

**Comment by pfalstad** [comment]
It would have to be rewritten in python, wouldn't it?

**Comment by eMPee584** [comment]
several possibilities I think.. one way would be a qtwebengine embedded view controlled via JS / DOM interaction.. :man_shrugging:

**Comment by eMPee584** [comment]
[..]
.. but I ain't gettin eclipse for this now   😯🧟‍♂️ ⏳
could you maybe pleease upload a zipped release of the compiled app? : )

**Comment by pfalstad** [comment]
You can download the offline version here: http://www.falstad.com/circuit/offline/

**Comment by eMPee584** [comment]
thanks.. yeah cool I had found that in the meantime, will include in our https://schulstick.org/ live distro.. for now as electron app.. I'll have another look into embedding it in a PyQt app.. Best regards!
