### ISSUE TITLE
Bug - Right clicking and selecting Edit while in Edit menu diables all further mouse input

### ISSUE THREAD

**Issue by FinleyDavies** [sharpie7/circuitjs1#519]
While in a component edit window, if you attempt to edit another component by right clicking and selecting edit, the current window is reopened. After the window is closed, no mouse input is detected at all. Keyboard shortcuts such as duplicate component still work.
After this happens the project can only be interacted with by refreshing the page and selecting File --> Recover Auto-Save.

**Comment by pfalstad** [comment]
fixed in 2.3.0
