### ISSUE TITLE
Feature-Manually charging components

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [sharpie7/circuitjs1#520]
You should be able to change the power stored in capacitors or inductors or other components using a menu item. The menu wouldn't have to dynamically update, it would just need a textbox and an ok/apply/cancel.

The use case is that you don't have to perform a hack like changing a capacitors capacitance. See: https://github.com/sharpie7/circuitjs1/issues/183

**Comment by pfalstad** [comment]
How about a "reset voltage" on each capacitor so that when you click Reset, it sets each capacitor to that voltage instead of 0.  That would be useful in several of the examples I think.

**Comment by EmergencyTemporalShift** [comment]
On that note, a reload circuit might also be useful.
