### ISSUE TITLE
How to check frequency response?

### ISSUE THREAD

**Issue by SM-Fahim** [sharpie7/circuitjs1#527]
I used to like Circuitjs, but day by day it's becoming very tough to achieve my goals. 

I'm trying to build Active Low/High/Band pass first/second order filters with cutoff frequency 42Hz. But when I'm trying to view the frequency response, I can't find any option. There's no Tutorial on YouTube nor any guide I could find. [Here's what I made](http://www.falstad.com/circuit/circuitjs.html?ctz=CQAgzCAMB0l5BGArANgExJGg7NbO00AOAFiTTATDAE4iQlIGHIAoAQxBP3FJBQQpeJEPWQgAtOITx4IXIzjpkyGvhqYieEmDQkSkNUgQUiEGbNYB3LjzAp63NFiL02AJ1vPi9AUJ9QIBZw1vyCLr7hYHweXuAO4PbxbkGWAOaJQvb0aDRZCbFOXHCZxUxMaCiKrABKpQYVPA2BCPxY5YEwSKwAxnHNRSSunbCyrVrYOnoGRibRYKwZg8NF5OWs2WFZfCh5wp2sAPap-CJMJDL+FUjQQhUnC0A). 

Although I found an example of Passive Low Pass Filter., but couldn't find any way how it was made. And seems like it's an old version of circuits, so there are not enough tools to use. Here it [is.](https://www.falstad.com/circuit/e-filt-hipass-af.html) 

If circuitjs is for pros only, then I might not continue with it from my next semester. I highly look forward to YouTube tutorials for beginners like me. All the YouTube tutorials only show the premade circuits, hence, not useful.

**Comment by pfalstad** [comment]
There's no way to view the frequency response.  To do that, you can use this applet: https://www.falstad.com/afilter/

But it only works with linear elements.  There are a bunch of filter examples in the Circuits menu.
