### ISSUE TITLE
Feature- Drag all nodes at point

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [sharpie7/circuitjs1#528]
There should be a drag option for all nodes under the cursor.
Repositioning nodes in this mode would move all the nodes under the cursor, repositioning components would just move all of their nodes. (Integrated chips would not work with this.)
I copied this from https://github.com/sharpie7/circuitjs1/issues/68 so that it could be its own separate request.

**Comment by pfalstad** [comment]
added
