### ISSUE TITLE
MBB switch shortcut conflicts with normal switch

### ISSUE THREAD

**Issue by krzygorz** [sharpie7/circuitjs1#538]
Looks like the recently-added MBB switch inherited the 's' shortcut from the simple switch, so now they are assigned to the same key. Annoyingly, it's the MBB switch that gets selected when pressing 's'.

**Comment by pfalstad** [comment]
sorry about that, I'll fix it.  For now you can go to Options->Shortcuts and remove the shortcut for the make-before-break switch.

**Comment by pfalstad** [comment]
fixed in 2.3.3
