### ISSUE TITLE
(bug?) I cant resize the floating scopes anymore 

### ISSUE THREAD

**Issue by timmeh87** [sharpie7/circuitjs1#542]
I swear that as recently as a few weeks ago, when I floated a scope I could resize the floating scope window with a little dot that appeared somewhere on its perimeter. Right now I can see there is a gray dot at the bottom right when I hover, but I cannot ever click it to resize it... It disappears before I cant get my mouse to it. 

I am in chrome, I disabled my adblock

**Comment by pfalstad** [comment]
fixed
