### ISSUE TITLE
Bug-Signal and chassis ground symbols render differently when placed sideways

### ISSUE THREAD

**Issue by gosh-darn** [sharpie7/circuitjs1#546]
I’m assuming this is a bug, as they have never been rendered differently depending on orientation in any schematic that I’ve seen myself:

<img width="367" alt="Screenshot 2021-01-17 at 18 50 40" src="https://user-images.githubusercontent.com/26469320/104851410-1e173000-58f5-11eb-8e7e-5716b979bb18.png">

**Comment by pfalstad** [comment]
fixed
