### ISSUE TITLE
Feature-Add common ground symbol

### ISSUE THREAD

**Issue by gosh-darn** [sharpie7/circuitjs1#547]
It’s great to see the new signal and chassis ground symbols, but another symbol that is commonly used is what I usually refer to as the common ground symbol.

It looks like the regular earth ground symbol without the two smaller lines. Here from a 1954 radio schematic:

<img height="200" alt="Screenshot 2021-01-17 at 19 17 00" src="https://user-images.githubusercontent.com/26469320/104852012-9b906f80-58f8-11eb-948f-9fb3043cead7.png"> <img height="200" alt="Screenshot 2021-01-17 at 19 16 56" src="https://user-images.githubusercontent.com/26469320/104852013-9c290600-58f8-11eb-8b21-8056885e5bf5.png"> <img height="200" alt="Screenshot 2021-01-17 at 19 16 19" src="https://user-images.githubusercontent.com/26469320/104852014-9c290600-58f8-11eb-8a5d-ce3dc92b4e65.png">

**Comment by pfalstad** [comment]
This is already implemented, but only sideways 🙂

**Comment by gosh-darn** [comment]
Well that’s a very good start 😃
