### ISSUE TITLE
The addition of NTC resistors

### ISSUE THREAD

**Issue by Bytesforus** [sharpie7/circuitjs1#548]
They are currently not present in the simulator it seems.

**Comment by pfalstad** [comment]
They're there, under Active Components->Thermistor.  I guess they should be passive components.

**Comment by Bytesforus** [comment]
Good stuff, thanks. The standalone version I installed a few weeks ago does not, missing also the photoresistor.

A minor comment regarding the beta value for MOSFETs, to my knowledge this is a characteristic for transistors only.

**Comment by pfalstad** [comment]
It's a parameter used to model a MOSFET as well.  See here halfway down, "basic DC equations":

https://ece-research.unm.edu/jimp/vlsi/slides/chap2_1.html

**Comment by Bytesforus** [comment]
> 
> 
> It's a parameter used to model a MOSFET as well. See here halfway down, "basic DC equations":
> 
> https://ece-research.unm.edu/jimp/vlsi/slides/chap2_1.html

Some files in the standalone version seem to have paths that are too long in windows.
