### ISSUE TITLE
Incorrect Circuit: Parallel-In Serial-Out

### ISSUE THREAD

**Issue by Zhongy1** [sharpie7/circuitjs1#566]
This is specifically for the circuit in Sequential Logic > Shift Registers > Parallel-In Serial-Out.
Here is what the circuit currently looks like:
![Screen Shot 2021-03-15 at 12 21 30 PM](https://user-images.githubusercontent.com/34720343/111194725-78491000-8589-11eb-964b-b399f662f274.png)
The problem with this is the first input is unaffected by the load/shift input, causing the circuit to fill up with with a logic 1.

I added a mux in the front of the left most D flip-flop which seemed to have fixed the problem.
![Screen Shot 2021-03-15 at 12 21 06 PM](https://user-images.githubusercontent.com/34720343/111195116-ebeb1d00-8589-11eb-89b8-b55957cd90b9.png)

**Comment by pfalstad** [comment]
fixed

**Comment by pfalstad** [comment]
thanks for the fix
