### ISSUE TITLE
Add another language

### ISSUE THREAD

**Issue by ppegas** [sharpie7/circuitjs1#570]
I would like to create a translation. I can then use this file with a translation for the Czech language
http://www.falstad.com/circuit/
send somewhere to become part of this program?

thank you for answer

**Comment by pfalstad** [comment]
Sounds great!  You can go here and get an existing language file: https://github.com/pfalstad/circuitjs1/tree/master/src/com/lushprojects/circuitjs1/public

locale_ru.txt seems to be the most complete.  Then just replace the Russian with Czech.

Thanks for contributing!
