### ISSUE TITLE
NE555

### ISSUE THREAD

**Issue by Neytug** [sharpie7/circuitjs1#574]
555 плохо работает. Не правильно. При достижении на входе triger напряжения 1/3, таймер не переключается в устойчивое положение.

**Comment by pfalstad** [comment]
Hi, could you send a sample circuit showing the problem.

**Comment by Neytug** [comment]
ops.sorry. Забыл конденсатор на ctl поставить.

вс, 28 мар. 2021 г. в 20:27, Paul Falstad ***@***.***>:

**Comment by pfalstad** [comment]
Sounds like this is fixed?
