### ISSUE TITLE
subcircuit with 7 segments led output

### ISSUE THREAD

**Issue by goldenshaw** [sharpie7/circuitjs1#575]
I can build a multi-bit adder using the subcircuit feature, which can hide a lot detail inside the component, it's great. 
But when I try to combine the 7 segment decoder with the 7 segment LED, so to make a simple component which only need four logic input, how can I label the LED output? I can only label the four input node, and the resulting subcircuit component has no LED display as its output

**Comment by pfalstad** [comment]
Hi, it sounds like you want to make a subcircuit with an LED display in it, and hope that the LED display will be visible when using the subcircuit?  Unfortunately that's not possible.

**Comment by goldenshaw** [comment]
Thanks for your reply, yes, I want it be visible, sorry to hear that's impossible...
