### ISSUE TITLE
Feature- Parameter in Link for not Starting Simulation when Loaded

### ISSUE THREAD

**Issue by TimFFischer** [sharpie7/circuitjs1#576]
Is it possible to implement a parameter in a link to the simulation, in order to load a stopped simulation. So, that one has ho actively push the "RUN/Stop" button to start the simulation?

I'm happily and extensively using cicuitjs in my online script - however the pages get a bit luggy, with a lot of simulation onto it.

**Comment by pfalstad** [comment]
You can use running=false..  see https://github.com/sharpie7/circuitjs1#embedding

**Comment by TimFFischer** [comment]
wow, great! Thanks.

I could have thought of this myself.. ;-)
