### ISSUE TITLE
Bug-static RAM 

### ISSUE THREAD

**Issue by manabendra1955** [sharpie7/circuitjs1#586]
Static RAM dont follow written content for example when address -2 bit data 4-bit
![static_RAM](https://user-images.githubusercontent.com/82664457/115048567-8f339880-9e8e-11eb-80a8-ba0465dddd0a.jpg)

**Comment by pfalstad** [comment]
the contents are specified in decimal.  0:0 1 2 3
right now it's outputting 1011 which is 11 in binary.

**Comment by manabendra1955** [comment]
Wow! it worked. Thanks
Manabendra
