### ISSUE TITLE
[Feature Request] Export Audio to File

### ISSUE THREAD

**Issue by ashlynblack** [sharpie7/circuitjs1#590]
I figure this shouldn't be too complicated to implement (I could of course, be completely wrong!) Audio duplex recording using the OS can be somewhat cumbersome.

**Comment by pfalstad** [comment]
For now, if you're using chrome, open the developer tools, select Network, then click play, then the URL should show up and you can right click to open it in a new tab and download it.

**Comment by ashlynblack** [comment]
Thanks! :3

**Comment by jopdorp** [comment]
I'm willing to implement this

**Comment by pfalstad** [comment]
now if you play some audio, you can right click the audio output and select Edit, then click the link to download the last played audio.
