### ISSUE TITLE
Firefox memory hogging

### ISSUE THREAD

**Issue by dzarda** [sharpie7/circuitjs1#592]
- FF 88 64bit
- Windows 10

It appears we're allocating a lot of objects during the run. Even with the RLC circuit the memory consumption tops at 2.3/8G as seen here:

![obrazek](https://user-images.githubusercontent.com/3955056/115988054-2b108300-a5b8-11eb-8838-1656656b1406.png)

The problem manifests itself as repeating periods of normal operation followed by drastic reduction in performance characterizable as periodic denial of service. I was not able to pinpoint *what* the allocations pertain to.

![obrazek](https://user-images.githubusercontent.com/3955056/115988275-21d3e600-a5b9-11eb-9a36-8e5d4e6e9612.png)

FF profile here [profile.zip](https://github.com/sharpie7/circuitjs1/files/6371652/profile.zip)

FF memory snapshot here [45260033.zip](https://github.com/sharpie7/circuitjs1/files/6371656/45260033.zip)

Not encoutered in Chrome (different GC policy?)

![obrazek](https://user-images.githubusercontent.com/3955056/115988545-95c2be00-a5ba-11eb-8199-70e956619f05.png)

**Comment by pfalstad** [comment]
Someone reported this already as #490, but that got closed.

I think it is this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1586495

The more resistors in the circuit, the more memory is leaked.  Only happens on Windows, not Mac.

As a workaround, uncheck "Options->Show Voltage".  I'm not sure if we can work around this in the code.  The CanvasGradient objects doesn't seem to be very reusable, and there's no way to explicitly free them.

**Comment by dzarda** [comment]
Okey thanks, I was wondering if this is a FF defect after I saw low memory usage in the mem snapshot.

**Comment by dzarda** [comment]
Commented there https://bugzilla.mozilla.org/show_bug.cgi?id=1586495

**Comment by dzarda** [comment]
Wow they fixed the problem in latest Beta! Closing
