### ISSUE TITLE
open file with "circuitjs1.exe" "%1"

### ISSUE THREAD

**Issue by Metalloy** [sharpie7/circuitjs1#597]
Hello Sharpie,
Is it possible that "circuitjs1.exe" can run run a command line "circuitjs1.exe" "file_name" ?
This can help a lot with the standalone version, so that we can associate Falstad Circuits with
an extension of our choice, and automatically run the simulator by double clicking the files ???
Possible ?
Thanks

**Comment by pfalstad** [comment]
done
