### ISSUE TITLE
Current missing from some wires

### ISSUE THREAD

**Issue by ocarlsen** [sharpie7/circuitjs1#600]
Just found this site, its awesome!  I'm curios though why some circuits don't show current in all wires.  For example, 555 Timer Chip > Internals, the "trigger" and "threshold" wires never get yellow dots going in.  

Screen shot attached.
<img width="640" alt="Screen Shot 2021-05-13 at 3 55 01 PM" src="https://user-images.githubusercontent.com/2373329/118197757-6ad2c980-b404-11eb-8119-3ca9c8785825.png">

http://www.falstad.com/circuit/

**Comment by pfalstad** [comment]
The op-amps and gates are ideal, with infinite input impedance, so they don't draw any current.
