### ISSUE TITLE
Option to change selection color to something other than cyan

### ISSUE THREAD

**Issue by dullbananas** [sharpie7/circuitjs1#614]

**Comment by pfalstad** [comment]
You don’t like cyan?

**Comment by dullbananas** [comment]
I want to use cyan as the positive voltage color because it would be easier to distinguish for me, but it would be confusing if cyan is also the selection color

**Comment by dullbananas** [comment]
It might also be useful to allow different colors for current

**Comment by Felthry** [comment]
Making it an option wouldn't be a bad idea, considering accessibility needs. I imagine it wouldn't be too difficult to allow the user to set their own palette?

**Comment by pfalstad** [comment]
added
