### ISSUE TITLE
high pixel density

### ISSUE THREAD

**Issue by dullbananas** [sharpie7/circuitjs1#616]
In the area where the circuit is rendered, the resolution does not adapt to the display's pixel density or zoom. This make a huge difference in text readability.

![C956C442-A59A-4835-9D79-3EB7686EC951](https://user-images.githubusercontent.com/47706471/121058749-8fa52d00-c775-11eb-9f46-1fd55d15e832.jpeg)

In CSS and javascript, one "pixel" is equal to multiple physical pixels, if the pixel density is high. https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

**Comment by pfalstad** [comment]
Looks much better now.  Thanks for pointing that out.
