### ISSUE TITLE
Feature Request: Chokes

### ISSUE THREAD

**Issue by haydenth** [sharpie7/circuitjs1#620]
Hello all! 

I'm trying to figure out how to model a choke in circuitjs. Here's an example circuit from wikipedia.
![image](https://user-images.githubusercontent.com/1082756/122613402-67a5ab80-d04a-11eb-8419-a6164bc4b401.png)

I don't see this as an option and perhaps its related to using a transformer like in #392 

If this exists and I'm an idiot, please just close this and tell me off :)

**Comment by pfalstad** [comment]
An RF choke could be modeled as a small inductor, like 2 millihenries.

The choke in your picture is a common-mode choke, and can be implemented using a transformer with a small inductance.  According to some datasheets I found, the inductance could range from 7 microhenries to 60 millihenries.

**Comment by haydenth** [comment]
Perfect, thank you. Didn't realize it was quite that straightforward :)

**Comment by haydenth** [comment]
Shortly after I closed this, I found a good document on chokes + equivalent circuits if anyone in the future ever ends up here; 

https://www.murata.com/~/media/webrenewal/products/emc/emifil/knowhow/26to30.ashx
