### ISSUE TITLE
Monostable does not work after reset

### ISSUE THREAD

**Issue by JonasForssell** [sharpie7/circuitjs1#622]
I have a small issue with the monostable chip.
It works well until I have had a convergence fail in the model. This happens sometimes when I run outside normal operation.
When this happens I usually reset the simulation but for some reason the Monostable component stops working after this has happened. It is a bit like that it does not seem to be completely reset as it should.

If I reload the model (refresh the browser) the model works well.

If I check the box with "retriggerable", it also works again.

Is this the way it should be?

Many thanks for a fantastic program.

**Comment by pfalstad** [comment]
It's working for me, except that when I click reset, both Q and /Q are low, which is wrong.  Is that what you're referring to?  But if I trigger it, it works again.

**Comment by pfalstad** [comment]
Oh I see..  If you reset it when Q is high, it will never trigger again.

**Comment by pfalstad** [comment]
fixed
