### ISSUE TITLE
Wrong current direcion

### ISSUE THREAD

**Issue by nshell32** [sharpie7/circuitjs1#631]
In menu->schemes->general->capacitor:
When the capacitor is charging, the current direction is true, but when the switch was then switched the capacitor doesn't change the current flow direction to the opposite, but still act like an inductor. On the oscilloscope it looks like the capacitor during switch process changes its voltage direction, but the current still flow as before.

**Comment by pfalstad** [comment]
wow that was a bad one..  thanks for catching it.
