### ISSUE TITLE
Small feature request: Rotate/Flip transformers

### ISSUE THREAD

**Issue by ZVSphiler** [sharpie7/circuitjs1#635]
I apologize for the inconvenience, but in some cases I miss the ability to rotate transformers.

For example when I want to add a CT to a horizontally placed wire. 
I always have to do this ugly workaround: 

http://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWcMBMcUHYMGZIA4UA2ATmIxAUgoqoQFMBaMMAKABVkFCQAWbFcGEg9e-KFFiQIQqrImliLAO4hSAnjzzIeVDVsjLtuzZ249CIgyqFdRAoRnVhuV5I97PBwjy8PNvPJ7M2GYmrv4ifPZgaLxhfjHGWsyxCCj6CQEWXiJpGdZgIXHJYHiR8UA

Thanks in advance

**Comment by pfalstad** [comment]
fixed
