### ISSUE TITLE
Request for symbol update according to IEC-60617 

### ISSUE THREAD

**Issue by tito125** [sharpie7/circuitjs1#640]
Hello 

I see that the fuse symbol, is there any way to update it?
<a href="https://zupimages.net/viewer.php?id=21/34/vp7f.png"><img src="https://zupimages.net/up/21/34/vp7f.png" alt="" /></a>

https://knowledge.autodesk.com/fr/support/autocad-electrical/learn-explore/caas/CloudHelp/cloudhelp/2019/FRA/AutoCAD-Electrical/files/GUID-E540AE83-CEE1-4CA9-B43C-B19004025EAA-htm.html

**Comment by pfalstad** [comment]
fuse symbol can now be changed to IEC symbol
