### ISSUE TITLE
Feature Request: User adjustable setting to change the count of displayed digits for float values

### ISSUE THREAD

**Issue by ZVSphiler** [sharpie7/circuitjs1#644]
Displaying numbers rounded up to only one digit after comma that could possibly lead to mistakes.
For example if I'm using resistors of E96 series. Many of them have values of two digits after comma.

Although the values are only rounded up on display and not on their real values but in specific situations this is still a problem.
For example If I want to show my circuit to someone else via screenshot I have to manually photoshop it afterward or tell that the numbers are not correct.

It would be nice if you could can change that.

**Comment by pfalstad** [comment]
fixed
