### ISSUE TITLE
Feature Request or minor bug:? Hyberbolic functions (asin, acos, atan, sinh, cosh, tanh) are missing in the expression evaluator 

### ISSUE THREAD

**Issue by ZVSphiler** [sharpie7/circuitjs1#645]
Hi Pfalstad, it's me again 😜

I recently noted that hyberbolic functions: asin(), acos(), atan(), sinh(), cosh() and tanh() aren't implemented.
Is there is a specific reason for excluding these functions? Or were they just not yet implemented.

Thank you

**Comment by pfalstad** [comment]
That was an oversight.  I thought I added those already but I guess not.

**Comment by pfalstad** [comment]
added
