### ISSUE TITLE
Voltage Source 1 Terminal current through Labeled Node does not display

### ISSUE THREAD

**Issue by jjdnd** [sharpie7/circuitjs1#649]
Hi, love your simulator its very usual but i think this is a small bug.

if you pass current from a single terminal voltage source through a labelled node the current does not seem to come out from the output of its matching labelled node.

it seems to work fine with a 2 terminal voltage source.

please see example bellow

![_aa](https://user-images.githubusercontent.com/37413440/132522783-8442d058-5adc-4815-896c-9f487fdabe98.png)

$ 1 0.000005 10.20027730826997 50 5 43 5e-11
207 224 144 272 144 4 label1
207 416 144 352 144 4 label1
r 496 144 560 144 0 1000
w 160 144 224 144 1
w 416 144 496 144 1
g 560 144 576 144 0 0
R 160 144 128 144 0 0 40 5 0 0 0.5
g 560 208 576 208 0 0
w 416 208 496 208 1
w 160 208 224 208 1
r 496 208 560 208 0 1000
207 416 208 352 208 4 label2
207 224 208 272 208 4 label2
v 96 208 160 208 0 0 40 5 0 0 0.5
g 96 208 80 208 0 0

**Comment by pfalstad** [comment]
fixed
