### ISSUE TITLE
Disabling Mouse Wheel Changing Capacitor/Resistor Value's

### ISSUE THREAD

**Issue by jjdnd** [sharpie7/circuitjs1#666]
is there some way to disable changing of capacitance / resistor values with the mouse scroll wheel?

It is relay irritating that random capacitor and resistor values change when you zoom in and out because the mouse happened to be over a capacitor when you zoom out?

**Comment by pfalstad** [comment]
added

**Comment by jjdnd** [comment]
thanks, i just tried it and it even remembers state when the window is closed and re opend
