### ISSUE TITLE
create a title

### ISSUE THREAD

**Issue by J0AC0** [sharpie7/circuitjs1#669]
Hello, I'm using Circuits JS1, and I created a lot of circuits in the same page, and I like to put a title for the diferent circuits to explain what is every thing, but I didn't found an option for that. Maybe can be created, I don't know how, I'm sending an idea. Thanks for the software, is a very good program.

**Comment by TimFFischer** [comment]
Hi, did you had a look onto "Add text"? 
(Menu >> Draw >> Outputs and Labels >> Add Text or key shortcut "t")
