### ISSUE TITLE
Certain small circuit causes extreme performance issues

### ISSUE THREAD

**Issue by dudejuice** [sharpie7/circuitjs1#67]
I've noticed that when I build a simple square wave inverter, the applet hiccups profoundly whenever the voltage reverses direction, and will under some circumstances slow to several seconds per frame.

I've reproduced this on the JS and Java versions in both Firefox, Chromium, and local Java. Below is the circuit in linkified form. I don't know that much about discrete electronics, but I have a lot of fun messing around in this rad little applet.

http://tinyurl.com/zgwxeat

**Comment by Lemtil** [comment]
It doesn't like inductive spikes, or infinite feedback loops.

In the meantime. Here's a circuit that uses the same principles, but has smoothing components, and more sane values.
http://tinyurl.com/hk2dyoa

**Comment by dudejuice** [comment]
Thanks for responding and putting together that circuit. That's really unfortunate. I enjoy spikes and non-sane values.

I've noticed a lot of weird transformer and diode-related performance issues.

**Comment by Lemtil** [comment]
Things get weird because of the lack of parasitics, mostly. Make sure you add in series resistors, parallel capacitors, reduce transformers to milli/micro inductance values, and then you can do pretty much whatever you want.

Like, go nuts.
http://tinyurl.com/z3swc7j

**Comment by dudejuice** [comment]
Oh my god it's hideous! Thanks, I'll do some experimenting and see what I come up with. My goal is to make an inverter that you can run a load like the lamp componant on.

**Comment by pfalstad** [comment]
This seems to be fixed now.
