### ISSUE TITLE
How to measure the frequency

### ISSUE THREAD

**Issue by ivan64435** [sharpie7/circuitjs1#678]
I simulated an oscillator for high frequencies above 500kHz how can I measure the frequency, are there any tools for this besides an oscilloscope which is limited to 500 microseconds

**Comment by pfalstad** [comment]
To properly simulate a high frequency oscillator, you need a smaller timestep.

Do Options->Other Options, then set the time step size to 50n

Once you do that, the scope resolution will also be reduced,

**Comment by ivan64435** [comment]
arigato
