### ISSUE TITLE
Feature Request: asin(), acos(), atan(), sinh(), cosh(), tanh() etc. functions to VCVS, VCCS, CCVS, CCCS

### ISSUE THREAD

**Issue by ZVSphiler** [sharpie7/circuitjs1#682]
Hi there can you add some missing trigonometric functions like asin(), acos(), atan(), sinh(), cosh(), tanh() etc. to VCVS, VCCS, CCVS, CCCS?

**Comment by pfalstad** [comment]
See #645.  You filed that!  🙂

**Comment by pfalstad** [comment]
added
