### ISSUE TITLE
The state of relays are not properly reset when pressing "reset"

### ISSUE THREAD

**Issue by ferrybig** [sharpie7/circuitjs1#683]
### Steps: 

1. Load the following circuit: [https://www.falstad.com/circuit/circuitjs.html?running=false&ctz=...](https://www.falstad.com/circuit/circuitjs.html?running=false&ctz=CQAgjCAMB0l3BWcMBMcUHYMGZIA4UA2ATmIxAUgoqoQFMBaMMAKDAzxA0M9wBYQebChD8QhcFGgiqMSEjDx4UyCLQqwSOfKgsA7lx6jsE7r0gDILAOaDhxiUJHYEM3QCVDvE1x-YfsiB8tFChMAgswZx4hALCVHh4VPGhELIsAE6CsaLqMXF4lshw+tlxefYpVrb5ooVlQXBhLEA)
2. Observe the relay in the default off position.
3. Press run/stop to start the simulation
4. The simulation now pauses at 5.84ms
5. Press reset
6. Press run/stop to start the simulation

### Expected:
The simulation is reset to the initial state, with all components in their initial positions. The circuit should behave exactly the same and stop after 5.84ms

### Actual
The simulator never fully reset the relay component, it will now stop the simulation in 1.67ms

**Comment by pfalstad** [comment]
fixed
