### ISSUE TITLE
current profile

### ISSUE THREAD

**Issue by JonasForssell** [sharpie7/circuitjs1#688]
Apologies if this feature already exist.

Is there a way to create a current source with a defined profile?

time(s), current(A)
0,0;0.1,100,10,100;100,0

etc...

**Comment by JonasForssell** [comment]
Correcting myself. I guess a CCCS or VCCS can be used with the Pwl function.

**Comment by pfalstad** [comment]
Yes, exactly.

https://tinyurl.com/yxmabln3
