### ISSUE TITLE
Feature - Show node labels in scope

### ISSUE THREAD

**Issue by alanwevans** [sharpie7/circuitjs1#69]
If I right click on a labeled node and choose "view in scope" I would expect it to work like an "analog output", but it does not.

Also I would think that labeled nodes in the scope would show their name, maybe at the top/middle of the scope?  Maybe configurable?  Right click on scope, "show name", "name location".

Side note: This is my favorite sim.

**Comment by sharpie7** [comment]
The bug in your issue is fixed. I have changed the title to remind me of the 2nd part which I agree would be nice.

**Comment by alanwevans** [comment]
Yep, looks good now.  Thank you.

-Alan

**Comment by pfalstad** [comment]
The 2nd part is fixed too.
