### ISSUE TITLE
bug: current dots "out of nowhere"

### ISSUE THREAD

**Issue by TimFFischer** [sharpie7/circuitjs1#691]
Since there is also a bug report on the current dots, i have my two cents in form of a "nice bug", too.
In the following circuit, the current dots (or better charge dots) seem to be sourced from the lower left corner. 
When adding enough ammeters it gets fixed, but without it looks a implausible..
(the subcircuit resembles a battery/voltage source with internal resistance)

[https://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3AWAnC1b0DYrTAZlwBwYCsGA7AEwK7G6RIIUj7jTEjUjECmAtGGABQ0EACEAhgBdJAZQCWAWyjgQTJgB0ADquWQQvZsogAlbgGc5ZyQHsATgFEANgvVmwriutumLVu05czXFdILwA1a0dJcQBzbgDXYLcodRC2ENS3eGyM3LMEUNcwdLzCsxhiQQQwPQI9CkgCcDAmOgQVCWl5JVDythSs7LgB3oKi9PKMvsqAdyMyLAEmMAWoQTm9Faw9XAa1uaXVSmbWvch1k+Yzq71zoA](https://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3AWAnC1b0DYrTAZlwBwYCsGA7AEwK7G6RIIUj7jTEjUjECmAtGGABQ0EACEAhgBdJAZQCWAWyjgQTJgB0ADquWQQvZsogAlbgGc5ZyQHsATgFEANgvVmwriutumLVu05czXFdILwA1a0dJcQBzbgDXYLcodRC2ENS3eGyM3LMEUNcwdLzCsxhiQQQwPQI9CkgCcDAmOgQVCWl5JVDythSs7LgB3oKi9PKMvsqAdyMyLAEmMAWoQTm9Faw9XAa1uaXVSmbWvch1k+Yzq71zoA)

**Comment by pfalstad** [comment]
Yes, I noticed this a few days ago and fixed it already.  It's been there for a while.
