### ISSUE TITLE
Optional circle around transistors

### ISSUE THREAD

**Issue by K0rrid0r** [sharpie7/circuitjs1#695]
It would be nice to see transistors with the circle around them it's just to easier spot them in bigger circuits.

![image](https://user-images.githubusercontent.com/56724286/146274698-1e5eef05-eb8e-42a5-8b8d-4f031b4bf74a.png)

The circle could be an option in the window
![image](https://user-images.githubusercontent.com/56724286/146274908-7ef9671c-6ff1-459a-998b-b698cff33b63.png)

The triode somehow has this so why not transistors?
![image](https://user-images.githubusercontent.com/56724286/146274769-6405ad09-3f59-4ea9-a173-d283f715aa03.png)

thoughts? objections?

**Comment by pfalstad** [comment]
You probably want this to apply to all transistors in a circuit, right?  Rather than have a separate checkbox for every one?

**Comment by K0rrid0r** [comment]
yes i think that would be the correct option.

**Comment by K0rrid0r** [comment]
I see you completed it, I'm eager to se what it looks like :D
