### ISSUE TITLE
Transformer problem

### ISSUE THREAD

**Issue by BrennoMaturino1** [sharpie7/circuitjs1#698]
Today i was making a oscillator circuit based on a CFL ballast and the transformer suddenly started generating infinite energy and oscillating itself even without the transistors, i think you guys will understand better with the video

Edit: Here is my circuit: https://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWcMBMcUHYMGZIA4UA2ATmIxAUgoqoQFMBaMMAKADcRsUQUFDPuzblSoAWKmDRRpMBCwAu4DP0l5wo0eBRqJIBoRjw4BLHjwJtew0ZMZx+BGHNFiyKgBM6AMwCGAVwAbeQUlfhQUTTANHgjpCH1rI3htc1cGDGgcSDBsDGJsPDAsAsJGMAk4EE9fQOCAd3VI6KjI5SgWBpbQxp58doAnbvDWlTaqQjwjDp6i0bmBkGJ5pfBJaQmphpXZmbHp7bWuoXaGrh4+Ht5+SGmuq8vxE4FV7gPhFnF+XEjLUTAwvpiKDQUiubAAGnK4OwnBAhFgkFIGH+mEgfAQXDK8TA0AIaGIcDIjkIOGw2DK5ES+AI2AxCFEKCKBFEeH4tzaqk4kB+Omm33ABh4ZgFImmKRFQrUOxuDXFO350vZ8zle1O3POKmi9xlQ1i-OGT31fUw3DQvIAzjxHvyuFR+bp5P0-HQxRhTcbreqdbauZp9RcbgB7HgQM5iRGuf4FR5UsiEPi8aSm0MsIA

https://user-images.githubusercontent.com/67515570/147778248-cb8c1614-962d-469c-929e-0cc59ede1d75.mp4

**Comment by pfalstad** [comment]
uncheck "aproximacao trapezoidal"
