### ISSUE TITLE
Bug - 555 Timer Chip - Internals

### ISSUE THREAD

**Issue by ArmoredRodent** [sharpie7/circuitjs1#702]
There is a small bug in 555 Timer Chip - Internals file.  The VCC input is 10V, but out is 5V.

Fixed by changing High Voltage of op-amps, NORs and NOT to 10V.   Not sure is all need to be adjusted.

**Comment by pfalstad** [comment]
That's been there forever and nobody noticed..  😄

**Comment by ArmoredRodent** [comment]
Thanks!  Everyone assumes your app is perfect!  

It is an excellent resource.  Thanks for creating it and more importantly, supporting it!
