### ISSUE TITLE
Bug: D Flip-Flop

### ISSUE THREAD

**Issue by ArmoredRodent** [sharpie7/circuitjs1#707]
Under Edit Component, there are two options for Reset Pin and Set Pin.  Reset Pin works and adds a R pin.

The (possible) bug: Set Pin adds a S pin AND a R pin.  Shouldn't it just add a S Pin?

Once Set Pin is set, the Reset Pin has no effect.

![image](https://user-images.githubusercontent.com/16496324/149954136-6e6bc72b-46a8-4e8c-bff3-ea95e4b9d707.png)

**Comment by pfalstad** [comment]
I was just trying to minimize the number of combinations I had to support.  I haven't seen any real-life D flip flops which have set pins but no reset pins.  If you don't like the reset pin, just don't use it.
