### ISSUE TITLE
Request- Osciloscope

### ISSUE THREAD

**Issue by LawnchairLarry** [sharpie7/circuitjs1#708]
Sound's a little strange because their are already so called osciloscopes implemented but in fact that are not real oscilosopes but data recorder. Usefull helpfull for most things but if you are simulating with a fast simulation rate a real osciloscope with adjustable triggerpoint and stuff liek that would be real great =)

**Comment by LawnchairLarry** [comment]
Do you know what i mean? A Real Osciloscope has a (more or less) steady picture of the wafeform. That would be great for some presentations.

**Comment by pfalstad** [comment]
Dup of #559.
