### ISSUE TITLE
Feature- Request

### ISSUE THREAD

**Issue by Tonigau** [sharpie7/circuitjs1#713]
A  controlled switch would be a handy component. I tried using the Nch MOSFET(th=10, beta=200) with 32A 63V 50khz PWM & getting converge errors (doesn't error with default MOSFET parameters)
So a simple controlled switch would be handy, no config just 3 terminals .

cheers

**Comment by pfalstad** [comment]
What about an Analog Switch?  Under Active Building Blocks

**Comment by Tonigau** [comment]
Hello, I looked at the Analog Switch but could not get it to work.
I tried again & found it needs > 35V from WaveGen to work.
Thanks for the suggestion.
Don't get the Convergence Fail now with the switch node, but I don't get correct duty control of inductor current ?



[Buck2_Current_In_Asw.txt](https://github.com/sharpie7/circuitjs1/files/7921993/Buck2_Current_In_Asw.txt)
[Buck2_Current_In_MOSFET.txt](https://github.com/sharpie7/circuitjs1/files/7921994/Buck2_Current_In_MOSFET.txt)


![50khz buck A_SW](https://user-images.githubusercontent.com/31194040/150708134-e3cef71f-3e73-4237-85b4-343ab4d9187f.png)
ckt w- Analog Switch

![circuit-Conv_Fail W-MOSFET](https://user-images.githubusercontent.com/31194040/150708150-b5c56c60-6d7a-409a-9de0-01985e61c4d4.png)
ckt w- MOSFET

**Comment by pfalstad** [comment]
I was going to ask why you have one side of the square wave generator connected to one of the switch terms.  Doesn't seem very useful or realistic.  Then I realized my example circuit does that!

What's the issue with the inductor current?

**Comment by Tonigau** [comment]
_>> one side of the square wave generator connected to one of the switch terminals...
    >> What's the issue with the inductor current?_
Sorted, just forgot to turn on brain first... circuit below ok
.
![50k Buck_Asw](https://user-images.githubusercontent.com/31194040/150748682-c0c6ff9d-3e7f-4b47-90d5-5ba9c2d4cb59.png)
