### ISSUE TITLE
Power and common pins for components.

### ISSUE THREAD

**Issue by Pau563** [sharpie7/circuitjs1#72]
Is it possible to get access for the power pins and other pins. Example: Circuits with different voltages to components. 
In the image using a 7 segment display I had to work around not having access to the common Anode or common Cathodes.  The only way to actually get it work to what I needed was to use Individual LED's.

![power pins access](https://cloud.githubusercontent.com/assets/25962046/23224808/b865b882-f96a-11e6-887d-ac2eda77e9c6.jpg)

**Comment by EmergencyTemporalShift** [comment]
I would recommend either a global or per component toggle so you don't have to deal with them if you don't want to. Also forward compatibility. Unrelated but, a custom segment display I think has been done before somewhere, you need to upload a binary image.

**Comment by pfalstad** [comment]
added in ddd9487663f5d2a302ea9ee1f01f90892ee33c9c (for 7 segment display)

**Comment by Pau563** [comment]
Thank You.
