### ISSUE TITLE
[Feature Request] Show the cursor simultaneously on all graphs

### ISSUE THREAD

**Issue by MikePryadko** [sharpie7/circuitjs1#721]
### Description
At the moment cursor is showing only on graph under mouse, but it's needed to compare levels from all graphs (own value-label for each curve in graph) in the same time.
It seems like not a hard work so, please, implement it :relaxed: thanks in advance
### Illustrations
Now:
![image](https://user-images.githubusercontent.com/31248040/151678262-3ae1401a-bcf0-4aa8-a908-97a1d9d08ab2.png)

Would like to see:
![image](https://user-images.githubusercontent.com/31248040/151678355-fcc64bda-554b-408e-ab62-0119f41dae99.png)

**Comment by pfalstad** [comment]
In the second picture, there's two plots in that scope that we could potentially show the value of.  I guess we could just pick one arbitrarily.

There are some scopes that are so small vertically (with multiple values stacked) that there's not enough room to do this, but we can just check for that and not do it in that case.
