### ISSUE TITLE
future:scope measurement duty cycle

### ISSUE THREAD

**Issue by annopnod** [sharpie7/circuitjs1#73]
add future scope can measurement duty cycle
![ddd](https://cloud.githubusercontent.com/assets/6957642/23328170/e13f6cfa-fb4d-11e6-9129-ea21bbc8b59f.JPG)

**Comment by yunuzk** [comment]
click: options > other options > edit the time steps size.

**Comment by pfalstad** [comment]
fixed in b025e68334a296858ef713623a9c18971d2bd44e
