### ISSUE TITLE
Request: Ganged Potentiometers

### ISSUE THREAD

**Issue by ashlynblack** [sharpie7/circuitjs1#735]
Could be implemented in a fashion similar to switches, where they can be assigned to groups.

**Comment by pfalstad** [comment]
We don't have those, but you can link variable resistors, which should be good enough for most uses.

https://tinyurl.com/y8jwo94m

**Comment by ashlynblack** [comment]
The fact I can assign multiple parameters on different scales to the same slider makes this work like a charm, thanks!
