### ISSUE TITLE
Module not compiling

### ISSUE THREAD

**Issue by ashlynblack** [sharpie7/circuitjs1#736]
I've done my best to follow the instructions however when I go to Run As > GWT Dev and navigate to the internally hosted page, it has the message "This module hasn't been compiled yet." Not sure what I am doing wrong
![Untitled](https://user-images.githubusercontent.com/49699995/158166232-fe566a4f-c7e7-46d6-be87-da0956dfb25b.png)
.

**Comment by pfalstad** [comment]
try Run As -> GWT Development Mode with Jetty

**Comment by ashlynblack** [comment]
Gosh I tried every which way yesterday and could not get it to work (including with Jetty.) I sit down this morning and it works first try. Thank you!

**Comment by ashlynblack** [comment]
The version I compiled is 2.4.2, do the later versions get pushed to Github after beta testing or something?

**Comment by pfalstad** [comment]
pull from https://github.com/pfalstad/circuitjs1 , that has the latest version.

**Comment by ashlynblack** [comment]
Fantastic, thank you so much! :D
