### ISSUE TITLE
Incorrect voltage with two voltage sources in one document

### ISSUE THREAD

**Issue by jbtls** [sharpie7/circuitjs1#737]
Hello, when I include two voltage sources in a document and build one series and one parallel circuit each, I get 5.6nV displayed at the second voltage source instead of 0V due to errors. If I remove one of the two sources, the error disappears. 

-> [Example Circuit](https://falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWcMBMcUHYMGZIA4UA2ATmIxAUgpABZsKBTAWjDACgB3EFwqsYlNzC9wKPFE5CRYMeEKjx2ScIVzwAkCmXyZ4sDRqqlXfYd3gD6wVpPyxe+dgSDjFw-bcgnL5Ze9r-VxV-HipAyVCvZykqD0g2ACc1fkEVOIp4pNMrT3SwODYANxjNPHFIlKgqmli4KqoYBCKvNFLFVsqG2lquhugmrmwOjSG+WXjB1o9RqMFM2kIzWRpF2aqnaDxiSRn-FcNwybHxfaM2IA)

**Comment by pfalstad** [comment]
This seems to be caused by roundoff error in the matrix.  Add explicit grounds to get rid of it.

https://tinyurl.com/y7fwhskv

**Comment by jbtls** [comment]
Thx, so this is not a bug but a feature? ;)

**Comment by pfalstad** [comment]
Well not a feature but not sure if it's a bug either.  The simulator is never going to be perfect at guessing where the ground is supposed to be.  I can probably fix the roundoff error issue though.

**Comment by jbtls** [comment]
Ah, ok. THX anyway for this great software. I use it often with my students.
