### ISSUE TITLE
Using '~' character with "add Text" will cause everything after the '~' and including it to not display

### ISSUE THREAD

**Issue by ericfont** [sharpie7/circuitjs1#742]
Using `~` character with "add Text" will cause everything after the `~` and including it to not display.

Seems like the expected behavior would be to display the `~` as well as the rest of the text.

I'm noticing this issue occurs with "Add Text", but does not occur with "Add Labeled Node".

**Comment by pfalstad** [comment]
that's a weird side effect of some localization trick we're doing...

**Comment by pfalstad** [comment]
use a ∼ (U+223C) instead, it looks the same but isn't.
