### ISSUE TITLE
Not work timer

### ISSUE THREAD

**Issue by Dezmont51** [sharpie7/circuitjs1#743]
Circuits -> 555 Timer Chip -> Square Wave Generator
it works incorrectly

**Comment by K0rrid0r** [comment]
web browses falstad

![image](https://user-images.githubusercontent.com/56724286/160280277-a947a073-4dfe-4d29-8899-05872afbd9c6.png)

older stand alone version

![image](https://user-images.githubusercontent.com/56724286/160280287-b2008e76-1b5f-47ae-a799-79f286f29c08.png)


yupp there is a bug

**Comment by pfalstad** [comment]
sigh...  I've already put out 2 new versions this week, here come a third one
