### ISSUE TITLE
If using sliders to control AC Voltage source's frequency with min of 0Hz, and slide the slider all the way to 0, then sliding slider back to > 0Hz results in broken simulation

### ISSUE THREAD

**Issue by ericfont** [sharpie7/circuitjs1#744]
In [this simple circuit](https://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWK0AsAOA7GMA2BBOQgJhQRQwGYMQsQkUK6BTAWmwCgA3EN-IkChRw8wfEEQz9I4cTjjIk0pdDAFVKfA0h92AJxFh+E-m0MChUEHMjsUkRiwpoU4yTyIJhg4UoD6YX0h-BhwwNEDoBAj4ALZfIkDfCnYAdxExYwMjNxs03n5vLPMfdgB7GQhpMBCwhWQYy34IZKdLADFKxpEQAEkAOwAHAFcAFwAdAGcANVKAGxGAQwBzJkmBpgWAaxYR0pZ1rfZW6Q6BSzB4aTZewdHJmfnl1Ym23SYARyGmPoBjAE8jmh2hATBAINd+sNxtM5osVpMACIAYUmpQAZmiJkwRuwgA) using an AC voltage source:

[bug-when-move-freq-to-zero-and-then-inc-20220327-1758.circuitjs.txt](https://github.com/sharpie7/circuitjs1/files/8358573/bug-when-move-freq-to-zero-and-then-inc-20220327-1758.circuitjs.txt)

I right clicked the AC voltage source and edited sliders to control AC Voltage source's frequency with min of 0Hz.  If I then slide the slider all the way to 0, then sliding slider back to > 0Hz results in broken simulation:
 
![image](https://user-images.githubusercontent.com/6502474/160302701-0b2743ed-b1fe-42a2-8c6a-763f1e3b2cd1.png)

The AC voltage should be on at the positive frequency, but somehow is not outputting voltage.  Strangely it appears like current is flowing, even though the circuit is not being simulated.  I have to reset the simulation for the actual simulation to work again.

(v2.6.5js)

**Comment by pfalstad** [comment]
I think there's a division by zero error somewhere.  for now, set the minimum frequency to something nonzero, like 1 Hz.
