### ISSUE TITLE
feature request - Multiple pole and multiple throw switches

### ISSUE THREAD

**Issue by danbisson** [sharpie7/circuitjs1#746]
Is it possible to add multiple pole and multiple throw switches? i.e. double pole, double throw.

**Comment by pfalstad** [comment]
Yes.  Under Passive Components, select Add SPDT Switch.  That will create a 2 throw switch.  Right click it, Edit, you can set the # of Throws to whatever you want.

For multi-pole switches, create multiple SPDT switches, right click each one, Edit, change the switch group to the same nonzero number (for example, 1).

**Comment by danbisson** [comment]
Thank you!
