### ISSUE TITLE
unable to change minimum slider value for a resistor

### ISSUE THREAD

**Issue by ericfont** [sharpie7/circuitjs1#753]
In [this circuit](https://github.com/sharpie7/circuitjs1/files/8413504/circuit-20220404-1833.circuitjs.txt), I am unable to change this 7k feedback resistor's minimum slider value:

![unable-to-change-min-value-for-range-from-slider](https://user-images.githubusercontent.com/6502474/161642801-812fe0bb-5553-4d50-8bcd-829bf113671f.png)

If I try to change it's minimum slider value to 1k instead of 1, then nothing happens.  Note that this resistor slider is shared by that 7.9k resistor too, which does have 1k as its minimum slider value.

**Comment by ericfont** [comment]
(on version 2.6.9js)

**Comment by pfalstad** [comment]
workaround: set the "Share Slider" popup to "New Slider", set the min/max value, change the "Share Slider" popup back to "bottom-resistance"
