### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by ChromicQuanta** [sharpie7/circuitjs1#761]
It randomly freezes when I use it
circuitjs1-0.js:2598 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Tkb.Ukb [as _e] (circuitjs1-0.js:2598)
    at Tkb.iV [as Qf] (circuitjs1-0.js:2595)
    at u2 (circuitjs1-0.js:2514)
    at b1 (circuitjs1-0.js:2493)
    at M3 (circuitjs1-0.js:2584)
    at L4.M4 [as ce] (circuitjs1-0.js:2596)
    at oh (circuitjs1-0.js:275)
    at Zg (circuitjs1-0.js:891)
    at ah (circuitjs1-0.js:1364)
    at eval (circuitjs1-0.js:1945)
    at d (circuitjs1-0.js:1905)
^Error happenes when I connect wires sometimes

**Comment by pfalstad** [comment]
Is there anything in the console when that happens?

**Comment by ChromicQuanta** [comment]
> circuitjs1-0.js:2598 Uncaught TypeError: Cannot read properties of undefined (reading '0')
> at Tkb.Ukb [as _e] (circuitjs1-0.js:2598)
> at Tkb.iV [as Qf] (circuitjs1-0.js:2595)
> at u2 (circuitjs1-0.js:2514)
> at b1 (circuitjs1-0.js:2493)
> at M3 (circuitjs1-0.js:2584)
> at L4.M4 [as ce] (circuitjs1-0.js:2596)
> at oh (circuitjs1-0.js:275)
> at Zg (circuitjs1-0.js:891)
> at ah (circuitjs1-0.js:1364)
> at eval (circuitjs1-0.js:1945)
> at d (circuitjs1-0.js:1905)

**Comment by pfalstad** [comment]
Offline or web?  What version?

**Comment by ChromicQuanta** [comment]
http://falstad.com/circuit/

**Comment by ChromicQuanta** [comment]
Online I think

**Comment by pfalstad** [comment]
could you post the circuit?

File->Export As Link
copy to clipboard
paste it here
