### ISSUE TITLE
Feature Request: Linking of large-size simulations

### ISSUE THREAD

**Issue by TimFFischer** [sharpie7/circuitjs1#772]
My students developed digital circuits of SPI, I2C periperals, which use multiple subcircuits. I would like to implement these into a webpage in order to describe and explain these. Unluckily, the URL export of some simulations exceed the 2048 character limit, even in the compressed ctz data format. Theoretically, it is possible to save it locally of via Dropbox. 

But is there a way to "autoload" simulations e.g. from an public shared dropbox file or from an other txt link (like from a txt stored in github)?

**Comment by pfalstad** [comment]
github pages will also work, apparently.
