### ISSUE TITLE
VCO internals

### ISSUE THREAD

**Issue by Awen2345** [sharpie7/circuitjs1#778]
![Screenshot_2022-06-18-19-13-39-82.jpg](https://user-images.githubusercontent.com/87870432/174437084-0d485305-851e-4eba-947d-96347b3934a2.jpg)
Please give me internal schematic of vco

**Comment by pfalstad** [comment]
It doesn't have a schematic.  It's implementing using java code.

https://github.com/sharpie7/circuitjs1/blob/master/src/com/lushprojects/circuitjs1/client/VCOElm.java
