### ISSUE TITLE
2 Terminal Variable Voltage Source

### ISSUE THREAD

**Issue by jjdnd** [sharpie7/circuitjs1#784]
any chance of a 2 terminal veritable voltage source as oppose to a veritable voltage source that is fixed to ground

**Comment by pfalstad** [comment]
There is one.  See Inputs and Sources -> Add Voltage Source (2 terminal)

**Comment by jjdnd** [comment]
i don't understand?

there is a variable voltage source with one terminal that has a slider on the right that adjusts the voltage.

i don't see how you can do that with a 2 terminal voltage source as it has no slider

**Comment by pfalstad** [comment]
oh a variable voltage.  right slight a normal 2 terminal voltage source, select "Sliders...", check "Voltage", fill in the desired min and max value, click OK
