### ISSUE TITLE
Still unable to export current data through Data export. Pl. Help

### ISSUE THREAD

**Issue by rrcmks** [sharpie7/circuitjs1#785]
My previous request
The circuit simulator is an amazing program.
I love it many features. Thanks to the contributors.
I am exporting Voltage data through Data Export in Output options.
But I wish to export Current as well as Resistance by the same way.
I tried a lot of ways but I can't succeed.
Please help to sort out this.
Thanks in advance
M K Saba

Base on this my previous quote  I am writng now
Hope you are fine.
Thanks for your support.
As quoted....
Still I am unable to export Current data by data export it only export V.

I used these two methods, mentioned by you.

https://tinyurl.com/ydh23v39
https://tinyurl.com/yde53ccj

Still it does not work. It only exports V at all points.

Please provide a solution for this.

**Comment by pfalstad** [comment]
Hi, here is an example of how to use it.

https://tinyurl.com/2gfgrg7t

I took the op-amp relaxation oscillator example and used the method I sent you before to convert the current through the capacitor to a voltage.  Then I use the data export to export that voltage.  So that gives me the current data.

Let me know if that works for you.

**Comment by rrcmks** [comment]
> Hi, here is an example of how to use it.
> 
> https://tinyurl.com/2gfgrg7t
> 
> I took the op-amp relaxation oscillator example and used the method I sent you before to convert the current through the capacitor to a voltage. Then I use the data export to export that voltage. So that gives me the current data.
> 
> Let me know if that works for you.

Dear pfalstad,
Thank you so much for your reply.
I tried and work around other ways too since yesterday.
Just checked the op-amp oscillaotr based circuit.
Still it exports only V.
This is the output.

https://tinyurl.com/26lxkvsk

**Thank you for your reply.**
And I am still working with simple and basic circutis to simulte 'I' to export the data.

**Comment by pfalstad** [comment]
What I'm doing here is converting the current to a voltage.  The data exporter only exports voltages.  So you have to convert the current to a voltage in order to export it.  Look at the output file.  It contains the current data.
