### ISSUE TITLE
feature request: search box for the draw menu

### ISSUE THREAD

**Issue by lshachar** [sharpie7/circuitjs1#787]
Hi!

They say a picture is worth a thousand words... I think this one is very self explenatory
![image](https://user-images.githubusercontent.com/13820621/181483588-61d22692-7978-4cdb-8d5b-cb6fd53d5c27.png)
I find myself getting lost searching for an item (or not knowing if it's there at all). 
A search box could be very useful!

@pfalstad, your simulator was a great part of how I learned electronics. Thank you so much for that!
and thank you to a whole slew of developers for contributing code and moving the simulator out of Java!

**Comment by pfalstad** [comment]
Do Edit->Find Component, or press slash ( / )

**Comment by lshachar** [comment]
(Facepalm)

Thank you!
