### ISSUE TITLE
Change the project name to circuitjs from circuitjs1

### ISSUE THREAD

**Issue by IPlayZed** [sharpie7/circuitjs1#790]
The **1** at the end is unneeded in my opinion. It would improve a lot on the user experience if it was not there.

**Comment by pfalstad** [comment]
How would that change the user experience?

**Comment by IPlayZed** [comment]
Obviously the issue is half joking, but on the other half it really is strange that it is not only **circuitjs**. Why is that?

**Comment by pfalstad** [comment]
No idea.  Only Iain knows for sure.
