### ISSUE TITLE
Scope display freezes after undocking

### ISSUE THREAD

**Issue by Vort** [sharpie7/circuitjs1#794]
1. Open default oscillator schematic.
2. Make sure that simulation is running.
3. Right click on any of the scopes and select "Undock Scope".

Now scope is moved to schematic and frozen.
It should be updated like when it was docked.

**Comment by pfalstad** [comment]
as a workaround, move or resize the undocked scope to get it unfrozen.

**Comment by Vort** [comment]
Works good in 2.7.2. Thank you.
However, I can't see source code for this version.
Is program still open source?

**Comment by pfalstad** [comment]
Yeah I forgot, sorry.
