### ISSUE TITLE
Output Node precision

### ISSUE THREAD

**Issue by jjdnd** [sharpie7/circuitjs1#798]
The Output node has a property for "Show Voltage" "Scale"
Is it possible to you add a property for "Decimal Precision" ?
so the text always stays the same length without flickering about and being difficult to read

**Comment by K0rrid0r** [comment]
i second this, would be a great add

**Comment by pfalstad** [comment]
I'll add an option for fixed precision (with trailing zeros).  You can change the precision (number of digits) in the Edit->Options dialog.
