### ISSUE TITLE
Feature Request: AC Current Source

### ISSUE THREAD

**Issue by Jacoba1100254352** [sharpie7/circuitjs1#803]
I see only a DC current source and need to use an AC current source. On one project I was able to use source transformation but for a second it is too complex, so an actual AC current source element would be awesome! Anyway, thank you for the awesome product! 🙂

**Comment by pfalstad** [comment]
You can make one with a VCCS.  Here is a 80Hz source.

https://tinyurl.com/2l4qar6g
