### ISSUE TITLE
how does clock work?

### ISSUE THREAD

**Issue by matelot** [sharpie7/circuitjs1#810]
If I add a clock as an input to one of the circuits and change the clock speed to 1cps how do I get the clock to cycle?

**Comment by pfalstad** [comment]
you want 1 cycle per second?  create a clock, right click on it and click Edit, then set the Frequency to 1.

If you're going to make a circuit that slow, you might want to select Options->Other Options and set the timestep to something larger, like 10m.

**Comment by matelot** [comment]
Thank you pfalstad, I don't want to sound ungrateful but if you read my question again you will see that I set the clock speed to 1. (1 cps clock per second)
The wire from the clock stays green and doesn't switch off.
![clock2](https://user-images.githubusercontent.com/3066989/196529682-232e4965-2a7d-47da-a6bf-32b17606b3d1.JPG)

**Comment by pfalstad** [comment]
How about the time step, did you update that?

you should probably send me the circuit with File->Export as Link

**Comment by matelot** [comment]
Thank you pfalstad changing the time step size did it.
