### ISSUE TITLE
Feature request: identifying objects

### ISSUE THREAD

**Issue by MikePryadko** [sharpie7/circuitjs1#815]
I open scheme from examples and trying to understand what is what - it's veeeeery hard. How should I guess what is it?
![image](https://user-images.githubusercontent.com/31248040/199272285-23e65f59-3a3f-4009-8775-5fbbf6d63421.png)

**Comment by leonllrmc** [comment]
I think it's a node that you can read the voltage from using the javascript API
 (` CircuitJS1.getNodeVoltage("NODENAME" )`, which returns a float (ex: 3.3))

P.S: sorry for the code poor fornating

**Comment by MikePryadko** [comment]
> I think it's a node that you can read the voltage

I’d like to have a tool/way for clear object identification, without guessing.
