### ISSUE TITLE
Minus numbers on no current

### ISSUE THREAD

**Issue by davidllwilliams** [sharpie7/circuitjs1#818]
Is it possible to record a current of 0A instead of -0A with the ammeter when there is no current through the branch?
Please see picture of problem:
![image](https://user-images.githubusercontent.com/53854473/200113378-21a25e06-8ab8-4cf0-9bd5-103c8400c1f9.png)

**Comment by pfalstad** [comment]
I couldn't get this to happen.  Do you have an example circuit?
