### ISSUE TITLE
Dependent Voltage/Current Sources

### ISSUE THREAD

**Issue by edgarasf123** [sharpie7/circuitjs1#82]
Would it be possible to add the following?

- Voltage dependent voltage source
- Voltage dependent current source
- Current dependent voltage source
- Current dependent current source

https://en.wikipedia.org/wiki/Dependent_source

**Comment by pfalstad** [comment]
I'm working on the vcvs and am planning to do vccs.  Not sure about the others.

**Comment by edgarasf123** [comment]
Hmm, is there a particular reason why you're not sure about adding current controlled sources?

**Comment by pfalstad** [comment]
Well, you can make a current controlled source with a voltage controlled source and a 1 ohm resistor to convert the current to a voltage.

**Comment by sharpie7** [comment]
Now added to the program.
