### ISSUE TITLE
Feature Request: Add a proper documentation for the javascript API

### ISSUE THREAD

**Issue by leonllrmc** [sharpie7/circuitjs1#826]
The fact that CircuitJS integrates a JavaScript API is good, but the problem is that the only explanation on it is the example [here](https://www.falstad.com/circuit/jsinterface.html) but even if it shows a use of the API, it isn't a precise description

**Comment by pfalstad** [comment]
Added

go to https://www.falstad.com/circuit/doc/

click "JavaScript Interface"
