### ISSUE TITLE
Add the CD4093 Schmitt-trigger NAND gate

### ISSUE THREAD

**Issue by erantapaa** [sharpie7/circuitjs1#829]
The Schmitt-trigger NAND gate is very useful for building timing circuits and I find it a lot more versatile than the 555. Just google "cd4093 circuits" for examples.

I suppose it could be added as a subcircuit as the Schmitt-trigger input and digital NAND gate are already available, but having it available for everyone to use by default would be nice addition to circuit1js.

**Comment by pfalstad** [comment]
I forgot we have this already.  Create a NAND gate, right click, Edit, check "Schmitt Inputs"
