### ISSUE TITLE
Features: Add SMD Layout

### ISSUE THREAD

**Issue by annopnod** [sharpie7/circuitjs1#83]
see image:
![screenshot from 2017-03-03 10 47 59](https://cloud.githubusercontent.com/assets/6957642/23537645/0f4b3afa-0000-11e7-93a9-4aa10408df5f.png)

**Comment by sharpie7** [comment]
The application is based on circuit schematics drawn using the standard techniques and the well-known component symbols. In my experience this is how electronic engineers visualize circuits. It doesn't try and do anything about the physical layout of real circuits.

The transistor symbol already supports rotation and mirror-image (Edit->Swap E/C) so all degrees of freedom of the standard symbol are supported.
