### ISSUE TITLE
latch latches on weird events

### ISSUE THREAD

**Issue by imcute-aaaa** [sharpie7/circuitjs1#831]
it doesn't turn off output when OE' is on!

**Comment by imcute-aaaa** [comment]
it needs to be pulled down >:(

**Comment by pfalstad** [comment]
So pull it down.

**Comment by imcute-aaaa** [comment]
oh ok :(
a bit uncomfortable seeing that much current in circuit lol

**Comment by imcute-aaaa** [comment]
also the latch latches on RISING EDGE????WHAAAA?
I need some ram and latches for my 6 bit subleq cpu

**Comment by imcute-aaaa** [comment]
i need to
a)make something that latches on high instead of rising edge
b)make rising edges

**Comment by pfalstad** [comment]
I thought that the point of the output enable on the RAM chip is to so you can connect something else to the bus while the output is disabled.  But I suppose you might need to have the RAM output actual zeros when output is disabled.  Is that what you need?  I could fix that.

So you need a transparent latch?

**Comment by pfalstad** [comment]
Here, transparent 4-bit latch
https://tinyurl.com/2fmhrkju

**Comment by imcute-aaaa** [comment]
cannot access tinyurl :(
can u paste text here?
Yes I need it to make zeros or it will mess up the bus

**Comment by pfalstad** [comment]
You can't access tinyurl? Why not?

http://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWcMBMcUHYMGZIA4UA2ATmIxAUgoqoQFMBaMMAKAEIQAXAJwEMA7AM4AHXtzr9OAHUEAbXpwDGACyggAkpAA06sDpQ7sWgMKyA1iADy2y3ssHL2LnyGjxkmfKWqAggCFjABEwKQBHfyCpfgB+WOjIGQjAsKSoljQ8EBQEQnBCKlwAFjyqKh4BETEJaTkFFWpSihYAGSyckqyUYrB8tQgAM15ZQToGlrbcsGIUTu7ptSpB4dGkSHHs3JQu2Z2qAaGRsdaNiZ2TvZAlw9X19pQ8TK3i+8zGq5WoFgBZEGwEGZ6BTw3V6VBQ0AQ31+-3A82wwNhMzBEKhfxmT1+CIxyMhPzRp3hz3aOJYQA

Usually if the RAM is disabled, then something else is driving the bus, so you don't need or want pulldowns..

**Comment by imcute-aaaa** [comment]
If something else is NOT using the bus,i might want to put the ram onto the bus(not when something else IS using the bus)

**Comment by imcute-aaaa** [comment]
Thank you,although using a quicker pulse generator to make lots of rising edges worked well
