### ISSUE TITLE
Feature request: Being able to group switches

### ISSUE THREAD

**Issue by K0rrid0r** [sharpie7/circuitjs1#834]
I'm trying to recall if I have seen this before or not in falstad. I do have a vague memory of seeing that it was possible to have switches grouped so when one closes (or opens) all the other switches linked to that group are also affected.

This is true for bigger switches in the real world, here is an example from my job.

![image](https://user-images.githubusercontent.com/56724286/211899653-b61a2bf2-d8be-416c-bf05-73b3cd266c8b.png)

and here it is in the schematic:

![image](https://user-images.githubusercontent.com/56724286/211901711-68b44e79-1800-4612-9e70-7c7451b279ca.png)

So yeah, it would be cool if this was also possible in falstad like in this example:

![image](https://user-images.githubusercontent.com/56724286/211901890-37e2c163-355d-4bec-b53c-f631ef4e327a.png)

Close the top switch and the lower one follows. This could be done in the edit window by applying a group name to a bunch of switches i guess.

/F

**Comment by pfalstad** [comment]
This is possible for SPDT switches but not SPST switches.

**Comment by K0rrid0r** [comment]
How is that possible for SPDT switches? As i understand it i can only switch an SPDT with applying power to the trigger.

Alright well maybe there could be an addition of a DPST switch, but as you see in the example there are physical switches that switch much more by physically moving a main switch (this you know of course)

![image](https://user-images.githubusercontent.com/56724286/211904001-9288f674-d865-4904-a534-efedb707abb5.png)

I think grouping was a much easier solution.

**Comment by K0rrid0r** [comment]
maybe you mean something like this

![image](https://user-images.githubusercontent.com/56724286/211906481-7aa81e14-3715-4133-a289-00dd554a8970.png)

EDIT: yeah i guess in the context of falstad this works fine as a hacky solution hehe

**Comment by pfalstad** [comment]
Yes.

So a two SPDT linked switches would be a DPDT switch.

**Comment by K0rrid0r** [comment]
Yeah

I saw it the other day in a schematic like this, that's a physical on off switch for a power supply

![image](https://user-images.githubusercontent.com/56724286/211910764-25994094-0a48-4fc5-b04b-9360d872c35e.png)

But just like in the relay component window it could also be possible to add more switches to that switch configuration and then i guess it dosen't really have name except a big multilinked switch.

**Comment by K0rrid0r** [comment]
Commenting here again, i think falstad really needs a way to group switches or at least have these three available.

![image](https://user-images.githubusercontent.com/56724286/220710917-e3e9cb5d-4c41-4491-8944-f9ff6835c100.png)

(SPST already there of course)

The DPST have many real world usages, also in simulation id say, im just making a simulation right now where the only solution to a problem is a DPST.

**Comment by pfalstad** [comment]
An DPDT is a solution.

I was looking again at the "hacky solution" picture you posted above and I'm not sure we're talking about the same thing.  Are those relays?  I was talking about linked SPDT switches.

You can create several SPDT switches and right click each one, edit, and change the "Switch Group" to a shared value.  Sorry if I wasn't clear about that.

https://tinyurl.com/2m37kpe7

DPDT switches can be used as DPST.  Just ignore the extra terminals.

**Comment by K0rrid0r** [comment]
Ahhhh there it was, i had been looking for that function for ages, remember seeing it in some other simulation long ago. Thanks. Consider adding this "Switch Group" window to the SPST also. ( just for correctness ;) )

And also that hacky solution was completely wrong since that was cmos analog switches. 

Thanks!

**Comment by pfalstad** [comment]
SPST switches can be linked now too.
