### ISSUE TITLE
Feature request: zoom into location where the mouse cursor is

### ISSUE THREAD

**Issue by kubark42** [sharpie7/circuitjs1#835]
Currently: When mouse wheel/two finger zooming, the zoom centers about the center of the screen
Desired: When mouse wheel/two finger zooming, the zoom centers about the current location of the mouse cursor

This is done in many CAD programs, and I have grown to love it. In addition to making it very easy to inspect a component of interest, it makes it much easier to pan-- because you can see zoom out in one location and zoom in another.

**Comment by K0rrid0r** [comment]
really good idea!
