### ISSUE TITLE
Copy of custom logic do not work

### ISSUE THREAD

**Issue by hjanetzek** [sharpie7/circuitjs1#837]
In this circuit only the first (rightmost) custom logic instance is evaluated correctly. The copies don't work, not even when creating a new instance and copying the model configuration. 

[custom-logic-bug.zip](https://github.com/sharpie7/circuitjs1/files/10465253/custom-logic-bug.zip)

Awesome work btw! this program really helps me getting started with electronics (:

**Comment by pfalstad** [comment]
Hi, you have two many question marks in the first line of the model.  You have "??????????1" which is 10 question marks.  There are 10 inputs, so the 1 matches the first output (0).  So as soon as output 0 becomes high, then the outputs go into a high-impedance state and stay there no matter what the inputs are.

Also the rightmost custom logic instance has a slightly different model where the outputs are all 0, not _.  So it doesn't have that problem.

**Comment by hjanetzek** [comment]
Oh thank you! :)
