### ISSUE TITLE
Question / Feature Request: Analog Filter mode in the desktop versions

### ISSUE THREAD

**Issue by mordae** [sharpie7/circuitjs1#840]
Hi, is it possible to use the analog filter mode in the downloaded desktop version?
If yes, how? If not, it would be nice to have it.

**Comment by pfalstad** [comment]
I added this: https://www.falstad.com/afilter/offline/

**Comment by mordae** [comment]
Thanks! I am on Linux, though. :sweat_smile:
Can I build it myself?

**Comment by pfalstad** [comment]
ok I added a linux one, let me know if it works.
https://www.falstad.com/afilter/offline/

**Comment by mordae** [comment]
Perfectly! You are my hero.

I love how I can explore ideas super quickly with these tools. Way faster than setting up a SPICE simulation. Having them offline make it easier to open and save files and thus to keep a library of designs and be able to borrow from them. So thanks again!
