### ISSUE TITLE
How do I export electric current values?

### ISSUE THREAD

**Issue by VadimKanarsky** [sharpie7/circuitjs1#848]
For a circuit study, I need both voltage and current data. But only voltages can be exported(
![image](https://user-images.githubusercontent.com/126089304/220828456-868f6453-8ee5-45c5-a509-89dc6fa4d81a.png)

**Comment by pfalstad** [comment]
You can use a CCVS to convert current to voltage and then export it, like this: https://tinyurl.com/2n4amu72

**Comment by VadimKanarsky** [comment]
@pfalstad, you are amazing! Thanks for this decision)

**Comment by VadimKanarsky** [comment]
@pfalstad, Please tell me if the export data files can be saved automatically?

**Comment by pfalstad** [comment]
No, sorry
