### ISSUE TITLE
Feature - Math operations in scope

### ISSUE THREAD

**Issue by easyas314159** [sharpie7/circuitjs1#86]
It would be rather useful for analysis to be able to perform math operations (+, -, *, /) on signals in the scope. Either using some extension of 'combine', or by adding the operators as Voltage based helper components that could be added to the scope. In the case of Voltage based helper components, a component to convert current directly to a Voltage would also be useful.

I have had a couple of instances recently where I was doing some distortion analysis where this would have been extremely helpful.

**Comment by pfalstad** [comment]
I'm working on a component that lets you perform math operations on its inputs, so once that is ready you could use that to generate values that could be scoped.

**Comment by pfalstad** [comment]
ok now you can use a VCVS (or CCVS) to generate voltages which you can then plot in a scope.
