### ISSUE TITLE
[Feature req] more features for 7-segment display

### ISSUE THREAD

**Issue by marcus0514** [sharpie7/circuitjs1#87]
Displaying mathematical numbers in 7-segment doesn't feel complete without decimals, nor digital clocks without colons. LEDs look very off trying to use them as decimal points. 7-segment displays should be more editable components -- there should be options where you can add a decimal point pin, colon pin, what not.

**Comment by Felthry** [comment]
Could go all the way and add an option to make it a 14- or 16-segment display, too. Could just be a checkbox in the element settings.

**Comment by pfalstad** [comment]
added in ddd9487663f5d2a302ea9ee1f01f90892ee33c9c
