### ISSUE TITLE
Bug - "Some nodes are unconnected!" when trying to create subcircuit

### ISSUE THREAD

**Issue by nemvince** [sharpie7/circuitjs1#879]
When trying to create a subcircuit from 4 connected master-slave flip flops i get the error "Some nodes are unconnected!".

Circuit:
[https://tinyurl.com/2kxttf76](https://tinyurl.com/2kxttf76)
[circuit-20230713-2057.circuitjs.txt](https://github.com/sharpie7/circuitjs1/files/12044383/circuit-20230713-2057.circuitjs.txt)

**Comment by pfalstad** [comment]
I labeled the unconnected node...  https://tinyurl.com/2jkhq6jv

nothing determines the voltage of this node.  You can attach it to ground and that will fix the problem.

**Comment by nemvince** [comment]
Thank you!
