### ISSUE TITLE
Lamp problems

### ISSUE THREAD

**Issue by reitho** [sharpie7/circuitjs1#89]
Hello,

I am using your great tool in an austrian vocational school for electrical engineering. For a short time, when using the lamp (beta), I get a _nan/infinite matrix!_: [circuit](http://tinyurl.com/jjcmp86).

Thank you so much for your support!

Kind regards,
Thomas Reitinger

**Comment by pfalstad** [comment]
Thanks, I have a fix for this which will be released soon.

BTW, if you want a German version of the simulator and are willing to translate strings, let me know.

**Comment by reitho** [comment]
Thanks for fast response :) So I will wait for the fix...

German version would be so cool. Maybe you can remember that we already had a conversation about that. I really would be happy to work on a german version. Just send how you need the data...

Bye, Thomas

**Comment by pfalstad** [comment]
Thanks, I sent you an email about that.  I hope your email address hasn't changed since 2014.  :)

**Comment by sharpie7** [comment]
Now appears to be fixed!
