### ISSUE TITLE
Macarm standalone download broken?

### ISSUE THREAD

**Issue by dirkvdb** [sharpie7/circuitjs1#904]
![image](https://github.com/sharpie7/circuitjs1/assets/1011958/149c7019-a078-4ec0-a667-0b0b88e09a1f)

I can't open the standalone arm version on mac. I get the error from the screenshot.

MacOS sonoma 14.1
Apple M2 Pro

**Comment by pfalstad** [comment]
Yes, I didn't build that correctly, apparently.  I don't have an ARM mac to test it on.  Someone said they fixed it by running this command in terminal:

xattr -cr Electron.app

**Comment by dirkvdb** [comment]
That did the trick. Thanks for the response!
