### ISSUE TITLE
Offline macOS Arm version is corrupted

### ISSUE THREAD

**Issue by OneCodeCZ** [sharpie7/circuitjs1#922]
There is only one file "Elektron" in DMG. After opening it Mac says: “Electron” is damaged and can’t be opened. You should eject the disk image. Intel version works just fine.

**Comment by pfalstad** [comment]
Yes, I didn't build that correctly, apparently. I don't have an ARM mac to test it on. Someone said they fixed it by running this command in terminal:

xattr -cr Electron.app

**Comment by OneCodeCZ** [comment]
I did not build it. I got it from your Website: https://www.falstad.com/circuit/offline/CircuitJS1-macarm.dmg

**Comment by OneCodeCZ** [comment]
The command "xattr -cr Electron.app" fixed it. I hope I get better performance. Thanks.

**Comment by pfalstad** [comment]
Glad that worked.  I don't think it will affect performance much.  I would think it would have the same performance as using the website with Chrome.
