### ISSUE TITLE
Feature Request: Wire Junction Points

### ISSUE THREAD

**Issue by SparkyNZ** [sharpie7/circuitjs1#932]
It seems as though we can only connect a wire from point A to point B. Can we please introduce a "junction point" that can be added to an existing wire so its easier to connect other wires and components to that wire/rail.

**Comment by pfalstad** [comment]
use ctrl-click (cmd-click on mac) to split a wire.

**Comment by SparkyNZ** [comment]
Excellent Pau!

Hey - I just want you to know that this is the best free circuit tool I
have found so far. I am only a dabbler in electronics but it is perfect for
my needs!

Thank you so much
Paul
