### ISSUE TITLE
Most recent version

### ISSUE THREAD

**Issue by vovodroid** [sharpie7/circuitjs1#933]
Hi @pfalstad and @sharpie7 !

Which site has more recent simulator version - original http://www.falstad.com/circuit/ or http://lushprojects.com/circuitjs/?

Thanks.

**Comment by pfalstad** [comment]
falstad.com

**Comment by vovodroid** [comment]
And where is actual source code? Here or in your fork https://github.com/pfalstad/circuitjs1? Or may be in some other repo?
Thanks.

**Comment by pfalstad** [comment]
in my fork
https://github.com/pfalstad/circuitjs1
