### ISSUE TITLE
Bug: Transformers

### ISSUE THREAD

**Issue by lucascanciojc** [sharpie7/circuitjs1#934]
Greetings Paul Falstad and sharpie7. I'm here to warn you about an issue (a bug) regarding transformer. A transformer will have its output equal to 0 volts if its entrance is a DC source. But, on the circuit simulator, that's not happening. The simulator is giving the user the result as if the entrance isn't a DC source, and that's where the bug is. Besides, this simulator is the one I use the most and until now I have only encountered this bug, keep up the great work!

**Comment by pfalstad** [comment]
That's discussed here:

https://www.falstad.com/circuit/e-transformerdc.html
